! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Global Data Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : small_f90_Global.f90
! Time                 : Thu Jan 27 17:32:38 2022
! Working directory    : /home/kyriacos/CyprusInstitute/kpp/small_fortran_single
! Equation file        : small_f90.kpp
! Output root filename : small_f90
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE small_f90_Global

  USE small_f90_Parameters, ONLY: sp, dp, NSPEC, NVAR, NFIX, NREACT
  PUBLIC
  SAVE


! Declaration of global variables

! C - Concentration of all species
  REAL(kind=sp) :: C(NSPEC)
! VAR - Concentrations of variable species (global)
  REAL(kind=sp) :: VAR(NVAR)
! FIX - Concentrations of fixed species (global)
  REAL(kind=sp) :: FIX(NFIX)
! VAR, FIX are chunks of array C
      EQUIVALENCE( C(1),VAR(1) )
      EQUIVALENCE( C(6),FIX(1) )
! E - Error of all species
  REAL(kind=sp) :: E(NSPEC)
! RCONST - Rate constants (global)
  REAL(kind=sp) :: RCONST(NREACT)
! TIME - Current integration time
  REAL(kind=dp) :: TIME
! SUN - Sunlight intensity between [0,1]
  REAL(kind=sp) :: SUN
! TEMP - Temperature
  REAL(kind=sp) :: TEMP
! RTOLS - (scalar) Relative tolerance
  REAL(kind=sp) :: RTOLS
! TSTART - Integration start time
  REAL(kind=sp) :: TSTART
! TEND - Integration end time
  REAL(kind=sp) :: TEND
! DT - Integration step
  REAL(kind=sp) :: DT
! ATOL - Absolute tolerance
  REAL(kind=sp) :: ATOL(NVAR)
! RTOL - Relative tolerance
  REAL(kind=sp) :: RTOL(NVAR)
! STEPMIN - Lower bound for integration step
  REAL(kind=sp) :: STEPMIN
! STEPMAX - Upper bound for integration step
  REAL(kind=sp) :: STEPMAX
! CFACTOR - Conversion factor for concentration units
  REAL(kind=sp) :: CFACTOR
! DDMTYPE - DDM sensitivity w.r.t.: 0=init.val., 1=params
  INTEGER :: DDMTYPE

! INLINED global variable declarations

! INLINED global variable declarations


END MODULE small_f90_Global

