C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C                                                                  
C Parameter Header File                                            
C                                                                  
C Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  
C       (http://www.cs.vt.edu/~asandu/Software/KPP)                
C KPP is distributed under GPL, the general public licence         
C       (http://www.gnu.org/copyleft/gpl.html)                     
C (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           
C (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            
C     With important contributions from:                           
C        M. Damian, Villanova University, USA                      
C        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
C                                                                  
C File                 : small_ref_Parameters.h                    
C Time                 : Fri Sep  2 14:40:04 2022                  
C Working directory    : /home/kyriacos/CyprusInstitute/KPP/small_ref
C Equation file        : small_ref.kpp                             
C Output root filename : small_ref                                 
C                                                                  
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




C NSPEC - Number of chemical species                               
      INTEGER NSPEC
      PARAMETER ( NSPEC = 7 )
C NVAR - Number of Variable species                                
      INTEGER NVAR
      PARAMETER ( NVAR = 5 )
C NVARACT - Number of Active species                               
      INTEGER NVARACT
      PARAMETER ( NVARACT = 5 )
C NFIX - Number of Fixed species                                   
      INTEGER NFIX
      PARAMETER ( NFIX = 2 )
C NREACT - Number of reactions                                     
      INTEGER NREACT
      PARAMETER ( NREACT = 10 )
C NVARST - Starting of variables in conc. vect.                    
      INTEGER NVARST
      PARAMETER ( NVARST = 1 )
C NFIXST - Starting of fixed in conc. vect.                        
      INTEGER NFIXST
      PARAMETER ( NFIXST = 6 )
C NONZERO - Number of nonzero entries in Jacobian                  
      INTEGER NONZERO
      PARAMETER ( NONZERO = 1 )
C LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
      INTEGER LU_NONZERO
      PARAMETER ( LU_NONZERO = 1 )
C CNVAR - (NVAR+1) Number of elements in compressed row format     
      INTEGER CNVAR
      PARAMETER ( CNVAR = 6 )
C CNEQN - (NREACT+1) Number stoicm elements in compressed col format
      INTEGER CNEQN
      PARAMETER ( CNEQN = 11 )
C NHESS - Length of Sparse Hessian                                 
      INTEGER NHESS
      PARAMETER ( NHESS = 10 )
C NLOOKAT - Number of species to look at                           
      INTEGER NLOOKAT
      PARAMETER ( NLOOKAT = 7 )
C NMONITOR - Number of species to monitor                          
      INTEGER NMONITOR
      PARAMETER ( NMONITOR = 6 )
C NMASS - Number of atoms to check mass balance                    
      INTEGER NMASS
      PARAMETER ( NMASS = 1 )

C Index declaration for variable species in C and VAR              
C   VAR(ind_spc) = C(ind_spc)                                      

      INTEGER ind_O1D
      PARAMETER ( ind_O1D = 1 )
      INTEGER ind_O
      PARAMETER ( ind_O = 2 )
      INTEGER ind_O3
      PARAMETER ( ind_O3 = 3 )
      INTEGER ind_NO
      PARAMETER ( ind_NO = 4 )
      INTEGER ind_NO2
      PARAMETER ( ind_NO2 = 5 )

C Index declaration for fixed species in C                         
C   C(ind_spc)                                                     

      INTEGER ind_M
      PARAMETER ( ind_M = 6 )
      INTEGER ind_O2
      PARAMETER ( ind_O2 = 7 )

C Index declaration for fixed species in FIX                       
C    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)                 

      INTEGER indf_M
      PARAMETER ( indf_M = 1 )
      INTEGER indf_O2
      PARAMETER ( indf_O2 = 2 )

C NJVRP - Length of sparse Jacobian JVRP                           
      INTEGER NJVRP
      PARAMETER ( NJVRP = 13 )

C NSTOICM - Length of Sparse Stoichiometric Matrix                 
      INTEGER NSTOICM
      PARAMETER ( NSTOICM = 22 )
