C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C                                                                  
C The ODE Jacobian of Chemical Model File                          
C                                                                  
C Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  
C       (http://www.cs.vt.edu/~asandu/Software/KPP)                
C KPP is distributed under GPL, the general public licence         
C       (http://www.gnu.org/copyleft/gpl.html)                     
C (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           
C (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            
C     With important contributions from:                           
C        M. Damian, Villanova University, USA                      
C        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
C                                                                  
C File                 : chapman_ref_Jacobian.f                    
C Time                 : Fri Sep  2 14:39:56 2022                  
C Working directory    : /home/kyriacos/CyprusInstitute/KPP/chapman_ref
C Equation file        : chapman_ref.kpp                           
C Output root filename : chapman_ref                               
C                                                                  
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C                                                                  
C Jac - the Jacobian of Variables                                  
C   Arguments :                                                    
C      V         - Concentrations of variable species (local)      
C      F         - Concentrations of fixed species (local)         
C      RCT       - Rate constants (local)                          
C      JV        - full Jacobian of variables                      
C                                                                  
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      SUBROUTINE Jac ( V, F, RCT, JV )

      IMPLICIT NONE
      INCLUDE 'chapman_ref_Parameters.h'

C V - Concentrations of variable species (local)                   
      REAL*8 V(NVAR)
C F - Concentrations of fixed species (local)                      
      REAL*8 F(NFIX)
C RCT - Rate constants (local)                                     
      REAL*8 RCT(NREACT)
C JV - full Jacobian of variables                                  
      REAL*8 JV(NVAR,NVAR)


C Local variables                                                  
C B - Temporary array                                              
      REAL*8 B(11)

C B(2) = dA(2)/dV(1)                                               
      B(2) = RCT(2)*F(1)
C B(4) = dA(3)/dV(2)                                               
      B(4) = RCT(3)
C B(5) = dA(4)/dV(1)                                               
      B(5) = RCT(4)*V(2)
C B(6) = dA(4)/dV(2)                                               
      B(6) = RCT(4)*V(1)
C B(7) = dA(5)/dV(2)                                               
      B(7) = RCT(5)*V(3)
C B(8) = dA(5)/dV(3)                                               
      B(8) = RCT(5)*V(2)
C B(9) = dA(6)/dV(1)                                               
      B(9) = RCT(6)*V(4)
C B(10) = dA(6)/dV(4)                                              
      B(10) = RCT(6)*V(1)
C B(11) = dA(7)/dV(4)                                              
      B(11) = RCT(7)

C Construct the Jacobian terms from B's                            
      JV(1,1) = -B(2)-B(5)-B(9)
      JV(1,2) = B(4)-B(6)
      JV(1,4) = -B(10)+B(11)
      JV(2,1) = B(2)-B(5)
      JV(2,2) = -B(4)-B(6)-B(7)
      JV(2,3) = -B(8)
      JV(3,1) = B(9)
      JV(3,2) = -B(7)
      JV(3,3) = -B(8)
      JV(3,4) = B(10)+B(11)
      JV(4,1) = -B(9)
      JV(4,2) = B(7)
      JV(4,3) = B(8)
      JV(4,4) = -B(10)-B(11)
      RETURN
      END

C End of Jac function                                              
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C                                                                  
C Jac_Vec - function for sparse multiplication: square Jacobian times vector
C   Arguments :                                                    
C      JV        - full Jacobian of variables                      
C      UV        - User vector for variables                       
C      JUV       - Jacobian times user vector                      
C                                                                  
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      SUBROUTINE Jac_Vec ( JV, UV, JUV )

      IMPLICIT NONE
      INCLUDE 'chapman_ref_Parameters.h'

C JV - full Jacobian of variables                                  
      REAL*8 JV(NVAR,NVAR)
C UV - User vector for variables                                   
      REAL*8 UV(NVAR)
C JUV - Jacobian times user vector                                 
      REAL*8 JUV(NVAR)

      JUV(1) = JV(1,1)*UV(1)+JV(1,2)*UV(2)+JV(1,4)*UV(4)
      JUV(2) = JV(2,1)*UV(1)+JV(2,2)*UV(2)+JV(2,3)*UV(3)
      JUV(3) = JV(3,1)*UV(1)+JV(3,2)*UV(2)+JV(3,3)*UV(3)+JV(3,4)*UV(4)
      JUV(4) = JV(4,1)*UV(1)+JV(4,2)*UV(2)+JV(4,3)*UV(3)+JV(4,4)*UV(4)
      RETURN
      END

C End of Jac_Vec function                                          
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C                                                                  
C JacTR_Vec - sparse multiplication: square Jacobian transposed times vector
C   Arguments :                                                    
C      JV        - full Jacobian of variables                      
C      UV        - User vector for variables                       
C      JTUV      - Jacobian transposed times user vector           
C                                                                  
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      SUBROUTINE JacTR_Vec ( JV, UV, JTUV )

      IMPLICIT NONE
      INCLUDE 'chapman_ref_Parameters.h'

C JV - full Jacobian of variables                                  
      REAL*8 JV(NVAR,NVAR)
C UV - User vector for variables                                   
      REAL*8 UV(NVAR)
C JTUV - Jacobian transposed times user vector                     
      REAL*8 JTUV(NVAR)

      JTUV(1) = JV(1,1)*UV(1)+JV(2,1)*UV(2)+JV(3,1)*UV(3)+JV(4,1)
     &         *UV(4)
      JTUV(2) = JV(1,2)*UV(1)+JV(2,2)*UV(2)+JV(3,2)*UV(3)+JV(4,2)
     &         *UV(4)
      JTUV(3) = JV(2,3)*UV(2)+JV(3,3)*UV(3)+JV(4,3)*UV(4)
      JTUV(4) = JV(1,4)*UV(1)+JV(3,4)*UV(3)+JV(4,4)*UV(4)
      RETURN
      END

C End of JacTR_Vec function                                        
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


