C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C                                                                  
C Initialization of Utility Data Structures                        
C                                                                  
C Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  
C       (http://www.cs.vt.edu/~asandu/Software/KPP)                
C KPP is distributed under GPL, the general public licence         
C       (http://www.gnu.org/copyleft/gpl.html)                     
C (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           
C (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            
C     With important contributions from:                           
C        M. Damian, Villanova University, USA                      
C        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
C                                                                  
C File                 : chapman_ref_Monitor.f                     
C Time                 : Wed Mar  9 12:16:03 2022                  
C Working directory    : /home/kyriacos/CyprusInstitute/kpp/chapman_ref
C Equation file        : chapman_ref.kpp                           
C Output root filename : chapman_ref                               
C                                                                  
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



      BLOCK DATA MONITOR_DATA

      INCLUDE 'chapman_ref_Parameters.h'
      INCLUDE 'chapman_ref_Global.h'
      INTEGER i


      DATA SPC_NAMES /
     *'O1D','O','O3','NO','NO2',
     *'M','O2' / 


      DATA LOOKAT /
     *  1,  2,  3,  4,  5,  6,  7 / 


      DATA MONITOR /
     *  1,  2,  3,  4,  5,  7 / 


      DATA SMASS /
     *'N' / 


      DATA EQN_NAMES /
     *'                                 O2 --> 2 O     ',
     *'                             O + O2 --> O3      ',
     *'                                 O3 --> O + O2  ',
     *'                             O + O3 --> 2 O2    ',
     *'                                 O3 --> O1D + O2',
     *'                            O1D + M --> O + M   ',
     *'                           O1D + O3 --> 2 O2    ',
     *'                            O3 + NO --> NO2 + O2',
     *'                            O + NO2 --> NO + O2 ',
     *'                                NO2 --> O + NO  '
     * / 


C INLINED global variables                                         

C End INLINED global variables                                     

      END


