C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C                                                                  
C The Stoichiometric Chemical Model File                           
C                                                                  
C Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  
C       (http://www.cs.vt.edu/~asandu/Software/KPP)                
C KPP is distributed under GPL, the general public licence         
C       (http://www.gnu.org/copyleft/gpl.html)                     
C (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           
C (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            
C     With important contributions from:                           
C        M. Damian, Villanova University, USA                      
C        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
C                                                                  
C File                 : cbm4_ref_Stoichiom.f                      
C Time                 : Fri Sep  2 14:39:53 2022                  
C Working directory    : /home/kyriacos/CyprusInstitute/KPP/cbm4_ref
C Equation file        : cbm4_ref.kpp                              
C Output root filename : cbm4_ref                                  
C                                                                  
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C                                                                  
C ReactantProd - Reactant Products in each equation                
C   Arguments :                                                    
C      V         - Concentrations of variable species (local)      
C      F         - Concentrations of fixed species (local)         
C      ARP       - Reactant product in each equation               
C                                                                  
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      SUBROUTINE ReactantProd ( V, F, ARP )

      IMPLICIT NONE
      INCLUDE 'cbm4_ref_Parameters.h'

C V - Concentrations of variable species (local)                   
      REAL*8 V(NVAR)
C F - Concentrations of fixed species (local)                      
      REAL*8 F(NFIX)
C ARP - Reactant product in each equation                          
      REAL*8 ARP(NREACT)


C Reactant Products in each equation are useful in the             
C     stoichiometric formulation of mass action law                
      ARP(1) = V(26)
      ARP(2) = V(29)
      ARP(3) = V(25)*V(31)
      ARP(4) = V(26)*V(29)
      ARP(5) = V(26)*V(29)
      ARP(6) = V(29)*V(31)
      ARP(7) = V(25)*V(26)
      ARP(8) = V(25)
      ARP(9) = V(25)
      ARP(10) = V(1)
      ARP(11) = V(1)*F(1)
      ARP(12) = V(25)*V(27)
      ARP(13) = V(25)*V(28)
      ARP(14) = V(30)
      ARP(15) = V(30)*V(31)
      ARP(16) = V(26)*V(30)
      ARP(17) = V(26)*V(30)
      ARP(18) = V(6)*F(1)
      ARP(19) = V(6)
      ARP(20) = V(31)*V(31)
      ARP(21) = V(26)*V(31)*F(1)
      ARP(22) = V(27)*V(31)
      ARP(23) = V(9)
      ARP(24) = V(9)*V(27)
      ARP(25) = V(9)*V(9)
      ARP(26) = V(26)*V(27)
      ARP(27) = V(12)*V(27)
      ARP(28) = V(28)*V(31)
      ARP(29) = V(26)*V(28)
      ARP(30) = V(10)
      ARP(31) = V(10)*V(27)
      ARP(32) = V(28)*V(28)
      ARP(33) = V(28)*V(28)*F(1)
      ARP(34) = V(2)
      ARP(35) = V(2)*V(27)
      ARP(36) = V(16)*V(27)
      ARP(37) = V(21)*V(27)
      ARP(38) = V(21)
      ARP(39) = V(21)
      ARP(40) = V(21)*V(29)
      ARP(41) = V(21)*V(30)
      ARP(42) = V(24)*V(29)
      ARP(43) = V(24)*V(27)
      ARP(44) = V(24)*V(30)
      ARP(45) = V(24)
      ARP(46) = V(31)*V(32)
      ARP(47) = V(26)*V(32)
      ARP(48) = V(3)
      ARP(49) = V(32)*V(32)
      ARP(50) = V(28)*V(32)
      ARP(51) = V(27)
      ARP(52) = V(20)*V(27)
      ARP(53) = V(13)
      ARP(54) = V(13)
      ARP(55) = V(13)*V(26)
      ARP(56) = V(23)*V(29)
      ARP(57) = V(23)*V(27)
      ARP(58) = V(23)*V(25)
      ARP(59) = V(23)*V(30)
      ARP(60) = V(17)*V(29)
      ARP(61) = V(17)*V(27)
      ARP(62) = V(17)*V(25)
      ARP(63) = V(5)*V(27)
      ARP(64) = V(11)*V(31)
      ARP(65) = V(11)
      ARP(66) = V(14)*V(27)
      ARP(67) = V(14)*V(30)
      ARP(68) = V(4)*V(26)
      ARP(69) = V(7)*V(27)
      ARP(70) = V(19)*V(27)
      ARP(71) = V(19)
      ARP(72) = V(19)*V(25)
      ARP(73) = V(15)*V(27)
      ARP(74) = V(15)
      ARP(75) = V(22)*V(29)
      ARP(76) = V(22)*V(27)
      ARP(77) = V(22)*V(25)
      ARP(78) = V(22)*V(30)
      ARP(79) = V(18)*V(31)
      ARP(80) = V(18)*V(18)
      ARP(81) = V(8)*V(31)
      RETURN
      END

C End of ReactantProd function                                     
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C                                                                  
C JacReactantProd - Jacobian of Reactant Products vector           
C   Arguments :                                                    
C      V         - Concentrations of variable species (local)      
C      F         - Concentrations of fixed species (local)         
C      JVRP      - d ARP(1:NREACT)/d VAR (1:NVAR)                  
C                                                                  
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      SUBROUTINE JacReactantProd ( V, F, JVRP )

      IMPLICIT NONE
      INCLUDE 'cbm4_ref_Parameters.h'

C V - Concentrations of variable species (local)                   
      REAL*8 V(NVAR)
C F - Concentrations of fixed species (local)                      
      REAL*8 F(NFIX)
C JVRP - d ARP(1:NREACT)/d VAR (1:NVAR)                            
      REAL*8 JVRP(NJVRP)


C Reactant Products in each equation are useful in the             
C    stoichiometric formulation of mass action law                 
C Below we compute the Jacobian of the Reactant Products vector    
C    w.r.t. variable species: d ARP(1:NREACT) / d Var(1:NVAR)      

C JVRP(1) = dARP(1)/dV(26)                                         
      JVRP(1) = 1
C JVRP(2) = dARP(2)/dV(29)                                         
      JVRP(2) = 1
C JVRP(3) = dARP(3)/dV(25)                                         
      JVRP(3) = V(31)
C JVRP(4) = dARP(3)/dV(31)                                         
      JVRP(4) = V(25)
C JVRP(5) = dARP(4)/dV(26)                                         
      JVRP(5) = V(29)
C JVRP(6) = dARP(4)/dV(29)                                         
      JVRP(6) = V(26)
C JVRP(7) = dARP(5)/dV(26)                                         
      JVRP(7) = V(29)
C JVRP(8) = dARP(5)/dV(29)                                         
      JVRP(8) = V(26)
C JVRP(9) = dARP(6)/dV(29)                                         
      JVRP(9) = V(31)
C JVRP(10) = dARP(6)/dV(31)                                        
      JVRP(10) = V(29)
C JVRP(11) = dARP(7)/dV(25)                                        
      JVRP(11) = V(26)
C JVRP(12) = dARP(7)/dV(26)                                        
      JVRP(12) = V(25)
C JVRP(13) = dARP(8)/dV(25)                                        
      JVRP(13) = 1
C JVRP(14) = dARP(9)/dV(25)                                        
      JVRP(14) = 1
C JVRP(15) = dARP(10)/dV(1)                                        
      JVRP(15) = 1
C JVRP(16) = dARP(11)/dV(1)                                        
      JVRP(16) = F(1)
C JVRP(17) = dARP(12)/dV(25)                                       
      JVRP(17) = V(27)
C JVRP(18) = dARP(12)/dV(27)                                       
      JVRP(18) = V(25)
C JVRP(19) = dARP(13)/dV(25)                                       
      JVRP(19) = V(28)
C JVRP(20) = dARP(13)/dV(28)                                       
      JVRP(20) = V(25)
C JVRP(21) = dARP(14)/dV(30)                                       
      JVRP(21) = 1
C JVRP(22) = dARP(15)/dV(30)                                       
      JVRP(22) = V(31)
C JVRP(23) = dARP(15)/dV(31)                                       
      JVRP(23) = V(30)
C JVRP(24) = dARP(16)/dV(26)                                       
      JVRP(24) = V(30)
C JVRP(25) = dARP(16)/dV(30)                                       
      JVRP(25) = V(26)
C JVRP(26) = dARP(17)/dV(26)                                       
      JVRP(26) = V(30)
C JVRP(27) = dARP(17)/dV(30)                                       
      JVRP(27) = V(26)
C JVRP(28) = dARP(18)/dV(6)                                        
      JVRP(28) = F(1)
C JVRP(29) = dARP(19)/dV(6)                                        
      JVRP(29) = 1
C JVRP(30) = dARP(20)/dV(31)                                       
      JVRP(30) = 2*V(31)
C JVRP(31) = dARP(21)/dV(26)                                       
      JVRP(31) = V(31)*F(1)
C JVRP(32) = dARP(21)/dV(31)                                       
      JVRP(32) = V(26)*F(1)
C JVRP(33) = dARP(22)/dV(27)                                       
      JVRP(33) = V(31)
C JVRP(34) = dARP(22)/dV(31)                                       
      JVRP(34) = V(27)
C JVRP(35) = dARP(23)/dV(9)                                        
      JVRP(35) = 1
C JVRP(36) = dARP(24)/dV(9)                                        
      JVRP(36) = V(27)
C JVRP(37) = dARP(24)/dV(27)                                       
      JVRP(37) = V(9)
C JVRP(38) = dARP(25)/dV(9)                                        
      JVRP(38) = 2*V(9)
C JVRP(39) = dARP(26)/dV(26)                                       
      JVRP(39) = V(27)
C JVRP(40) = dARP(26)/dV(27)                                       
      JVRP(40) = V(26)
C JVRP(41) = dARP(27)/dV(12)                                       
      JVRP(41) = V(27)
C JVRP(42) = dARP(27)/dV(27)                                       
      JVRP(42) = V(12)
C JVRP(43) = dARP(28)/dV(28)                                       
      JVRP(43) = V(31)
C JVRP(44) = dARP(28)/dV(31)                                       
      JVRP(44) = V(28)
C JVRP(45) = dARP(29)/dV(26)                                       
      JVRP(45) = V(28)
C JVRP(46) = dARP(29)/dV(28)                                       
      JVRP(46) = V(26)
C JVRP(47) = dARP(30)/dV(10)                                       
      JVRP(47) = 1
C JVRP(48) = dARP(31)/dV(10)                                       
      JVRP(48) = V(27)
C JVRP(49) = dARP(31)/dV(27)                                       
      JVRP(49) = V(10)
C JVRP(50) = dARP(32)/dV(28)                                       
      JVRP(50) = 2*V(28)
C JVRP(51) = dARP(33)/dV(28)                                       
      JVRP(51) = 2*V(28)*F(1)
C JVRP(52) = dARP(34)/dV(2)                                        
      JVRP(52) = 1
C JVRP(53) = dARP(35)/dV(2)                                        
      JVRP(53) = V(27)
C JVRP(54) = dARP(35)/dV(27)                                       
      JVRP(54) = V(2)
C JVRP(55) = dARP(36)/dV(16)                                       
      JVRP(55) = V(27)
C JVRP(56) = dARP(36)/dV(27)                                       
      JVRP(56) = V(16)
C JVRP(57) = dARP(37)/dV(21)                                       
      JVRP(57) = V(27)
C JVRP(58) = dARP(37)/dV(27)                                       
      JVRP(58) = V(21)
C JVRP(59) = dARP(38)/dV(21)                                       
      JVRP(59) = 1
C JVRP(60) = dARP(39)/dV(21)                                       
      JVRP(60) = 1
C JVRP(61) = dARP(40)/dV(21)                                       
      JVRP(61) = V(29)
C JVRP(62) = dARP(40)/dV(29)                                       
      JVRP(62) = V(21)
C JVRP(63) = dARP(41)/dV(21)                                       
      JVRP(63) = V(30)
C JVRP(64) = dARP(41)/dV(30)                                       
      JVRP(64) = V(21)
C JVRP(65) = dARP(42)/dV(24)                                       
      JVRP(65) = V(29)
C JVRP(66) = dARP(42)/dV(29)                                       
      JVRP(66) = V(24)
C JVRP(67) = dARP(43)/dV(24)                                       
      JVRP(67) = V(27)
C JVRP(68) = dARP(43)/dV(27)                                       
      JVRP(68) = V(24)
C JVRP(69) = dARP(44)/dV(24)                                       
      JVRP(69) = V(30)
C JVRP(70) = dARP(44)/dV(30)                                       
      JVRP(70) = V(24)
C JVRP(71) = dARP(45)/dV(24)                                       
      JVRP(71) = 1
C JVRP(72) = dARP(46)/dV(31)                                       
      JVRP(72) = V(32)
C JVRP(73) = dARP(46)/dV(32)                                       
      JVRP(73) = V(31)
C JVRP(74) = dARP(47)/dV(26)                                       
      JVRP(74) = V(32)
C JVRP(75) = dARP(47)/dV(32)                                       
      JVRP(75) = V(26)
C JVRP(76) = dARP(48)/dV(3)                                        
      JVRP(76) = 1
C JVRP(77) = dARP(49)/dV(32)                                       
      JVRP(77) = 2*V(32)
C JVRP(78) = dARP(50)/dV(28)                                       
      JVRP(78) = V(32)
C JVRP(79) = dARP(50)/dV(32)                                       
      JVRP(79) = V(28)
C JVRP(80) = dARP(51)/dV(27)                                       
      JVRP(80) = 1
C JVRP(81) = dARP(52)/dV(20)                                       
      JVRP(81) = V(27)
C JVRP(82) = dARP(52)/dV(27)                                       
      JVRP(82) = V(20)
C JVRP(83) = dARP(53)/dV(13)                                       
      JVRP(83) = 1
C JVRP(84) = dARP(54)/dV(13)                                       
      JVRP(84) = 1
C JVRP(85) = dARP(55)/dV(13)                                       
      JVRP(85) = V(26)
C JVRP(86) = dARP(55)/dV(26)                                       
      JVRP(86) = V(13)
C JVRP(87) = dARP(56)/dV(23)                                       
      JVRP(87) = V(29)
C JVRP(88) = dARP(56)/dV(29)                                       
      JVRP(88) = V(23)
C JVRP(89) = dARP(57)/dV(23)                                       
      JVRP(89) = V(27)
C JVRP(90) = dARP(57)/dV(27)                                       
      JVRP(90) = V(23)
C JVRP(91) = dARP(58)/dV(23)                                       
      JVRP(91) = V(25)
C JVRP(92) = dARP(58)/dV(25)                                       
      JVRP(92) = V(23)
C JVRP(93) = dARP(59)/dV(23)                                       
      JVRP(93) = V(30)
C JVRP(94) = dARP(59)/dV(30)                                       
      JVRP(94) = V(23)
C JVRP(95) = dARP(60)/dV(17)                                       
      JVRP(95) = V(29)
C JVRP(96) = dARP(60)/dV(29)                                       
      JVRP(96) = V(17)
C JVRP(97) = dARP(61)/dV(17)                                       
      JVRP(97) = V(27)
C JVRP(98) = dARP(61)/dV(27)                                       
      JVRP(98) = V(17)
C JVRP(99) = dARP(62)/dV(17)                                       
      JVRP(99) = V(25)
C JVRP(100) = dARP(62)/dV(25)                                      
      JVRP(100) = V(17)
C JVRP(101) = dARP(63)/dV(5)                                       
      JVRP(101) = V(27)
C JVRP(102) = dARP(63)/dV(27)                                      
      JVRP(102) = V(5)
C JVRP(103) = dARP(64)/dV(11)                                      
      JVRP(103) = V(31)
C JVRP(104) = dARP(64)/dV(31)                                      
      JVRP(104) = V(11)
C JVRP(105) = dARP(65)/dV(11)                                      
      JVRP(105) = 1
C JVRP(106) = dARP(66)/dV(14)                                      
      JVRP(106) = V(27)
C JVRP(107) = dARP(66)/dV(27)                                      
      JVRP(107) = V(14)
C JVRP(108) = dARP(67)/dV(14)                                      
      JVRP(108) = V(30)
C JVRP(109) = dARP(67)/dV(30)                                      
      JVRP(109) = V(14)
C JVRP(110) = dARP(68)/dV(4)                                       
      JVRP(110) = V(26)
C JVRP(111) = dARP(68)/dV(26)                                      
      JVRP(111) = V(4)
C JVRP(112) = dARP(69)/dV(7)                                       
      JVRP(112) = V(27)
C JVRP(113) = dARP(69)/dV(27)                                      
      JVRP(113) = V(7)
C JVRP(114) = dARP(70)/dV(19)                                      
      JVRP(114) = V(27)
C JVRP(115) = dARP(70)/dV(27)                                      
      JVRP(115) = V(19)
C JVRP(116) = dARP(71)/dV(19)                                      
      JVRP(116) = 1
C JVRP(117) = dARP(72)/dV(19)                                      
      JVRP(117) = V(25)
C JVRP(118) = dARP(72)/dV(25)                                      
      JVRP(118) = V(19)
C JVRP(119) = dARP(73)/dV(15)                                      
      JVRP(119) = V(27)
C JVRP(120) = dARP(73)/dV(27)                                      
      JVRP(120) = V(15)
C JVRP(121) = dARP(74)/dV(15)                                      
      JVRP(121) = 1
C JVRP(122) = dARP(75)/dV(22)                                      
      JVRP(122) = V(29)
C JVRP(123) = dARP(75)/dV(29)                                      
      JVRP(123) = V(22)
C JVRP(124) = dARP(76)/dV(22)                                      
      JVRP(124) = V(27)
C JVRP(125) = dARP(76)/dV(27)                                      
      JVRP(125) = V(22)
C JVRP(126) = dARP(77)/dV(22)                                      
      JVRP(126) = V(25)
C JVRP(127) = dARP(77)/dV(25)                                      
      JVRP(127) = V(22)
C JVRP(128) = dARP(78)/dV(22)                                      
      JVRP(128) = V(30)
C JVRP(129) = dARP(78)/dV(30)                                      
      JVRP(129) = V(22)
C JVRP(130) = dARP(79)/dV(18)                                      
      JVRP(130) = V(31)
C JVRP(131) = dARP(79)/dV(31)                                      
      JVRP(131) = V(18)
C JVRP(132) = dARP(80)/dV(18)                                      
      JVRP(132) = 2*V(18)
C JVRP(133) = dARP(81)/dV(8)                                       
      JVRP(133) = V(31)
C JVRP(134) = dARP(81)/dV(31)                                      
      JVRP(134) = V(8)
      RETURN
      END

C End of JacReactantProd function                                  
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



C Begin Derivative w.r.t. Rate Coefficients                        

C ------------------------------------------------------------------------------
C Subroutine for the derivative of Fun with respect to rate coefficients
C -----------------------------------------------------------------------------

      SUBROUTINE  dFun_dRcoeff( V, F, NCOEFF, JCOEFF, DFDR )
       
      IMPLICIT NONE 
      INCLUDE 'cbm4_ref_Parameters.h'
      INCLUDE 'cbm4_ref_Sparse.h'

C V - Concentrations of variable/radical/fixed species            
      REAL*8 V(NVAR), F(NFIX)
C NCOEFF - the number of rate coefficients with respect to which we differentiate
      INTEGER NCOEFF       
C JCOEFF - a vector of integers containing the indices of reactions (rate
C          coefficients) with respect to which we differentiate
      INTEGER JCOEFF(NCOEFF)       
C DFDR  - a matrix containg derivative values; specifically, 
C         column j contains d Fun(1:NVAR) / d RCT( JCOEFF(j) )
C         for each 1 <= j <= NCOEFF
C         This matrix is stored in a column-wise linearized format
      REAL*8 DFDR(NVAR*NCOEFF)

C Local vector with reactant products
      REAL*8 A_RPROD(NREACT)
      REAL*8 aj
      INTEGER i,j,k
      
C Compute the reactant products of all reactions     
      CALL ReactantProd ( V, F, A_RPROD )

C Compute the derivatives by multiplying column JCOEFF(j) of the stoichiometric matrix with A_RPROD       
      DO j=1,NCOEFF
C                  Initialize the j-th column of derivative matrix to zero       
         DO i=1,NVAR
           DFDR(i+NVAR*(j-1)) = 0.0D0
         END DO
C                  Column JCOEFF(j) in the stoichiometric matrix times the
C                  reactant product  of the JCOEFF(j)-th reaction      
C                  give the j-th column of the derivative matrix   
         aj = A_RPROD(JCOEFF(j))
         DO k=CCOL_STOICM(JCOEFF(j)),CCOL_STOICM(JCOEFF(j)+1)-1
           DFDR(IROW_STOICM(k)+NVAR*(j-1)) = STOICM(k)*aj
         END DO
      END DO
      
      RETURN
      END

C End Derivative w.r.t. Rate Coefficients                          


C Begin Jacobian Derivative w.r.t. Rate Coefficients               

C ------------------------------------------------------------------------------
C Subroutine for the derivative of Jac with respect to rate coefficients
C Times a user vector
C -----------------------------------------------------------------------------

      SUBROUTINE  dJac_dRcoeff( V, F, U, NCOEFF, JCOEFF, DJDR )
       
      IMPLICIT NONE 
      INCLUDE 'cbm4_ref_Parameters.h'
      INCLUDE 'cbm4_ref_Sparse.h'

C V - Concentrations of variable/radical/fixed species            
      REAL*8 V(NVAR), F(NFIX)
C U - User-supplied Vector           
      REAL*8 U(NVAR)
C NCOEFF - the number of rate coefficients with respect to which we differentiate
      INTEGER NCOEFF       
C JCOEFF - a vector of integers containing the indices of reactions (rate
C          coefficients) with respect to which we differentiate
      INTEGER JCOEFF(NCOEFF)       
C DFDR  - a matrix containg derivative values; specifically, 
C         column j contains d Jac(1:NVAR) / d RCT( JCOEFF(j) ) * U
C                     for each 1 <= j <= NCOEFF
C         This matrix is stored in a column-wise linearized format
      REAL*8 DJDR(NVAR*NCOEFF)

C Local vector for Jacobian of reactant products
      REAL*8 JV_RPROD(NJVRP)
      REAL*8 aj
      INTEGER i,j,k
      
C Compute the Jacobian of all reactant products   
      CALL JacReactantProd( V, F, JV_RPROD )

C Compute the derivatives by multiplying column JCOEFF(j) of the stoichiometric matrix with A_PROD       
      DO j=1,NCOEFF
C                  Initialize the j-th column of derivative matrix to zero       
         DO i=1,NVAR
           DJDR(i+NVAR*(j-1)) = 0.0D0
         END DO
C                  Column JCOEFF(j) in the stoichiometric matrix times the
C                  ( Gradient of reactant product of the JCOEFF(j)-th reaction X user vector )    
C                  give the j-th column of the derivative matrix   
C
C          Row JCOEFF(j) of JV_RPROD times the user vector
         aj = 0.d0
         DO k=CROW_JVRP(JCOEFF(j)),CROW_JVRP(JCOEFF(j)+1)-1
	    aj = aj + JV_RPROD(k)*U(ICOL_JVRP(k))
	 END DO
C          Column JCOEFF(j) of Stoichiom. matrix times aj         
         DO k=CCOL_STOICM(JCOEFF(j)),CCOL_STOICM(JCOEFF(j)+1)-1
           DJDR(IROW_STOICM(k)+NVAR*(j-1)) = STOICM(k)*aj
         END DO
      END DO
      
      RETURN
      END

C End Jacobian Derivative w.r.t. Rate Coefficients                 

