C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C                                                                  
C Hessian File                                                     
C                                                                  
C Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  
C       (http://www.cs.vt.edu/~asandu/Software/KPP)                
C KPP is distributed under GPL, the general public licence         
C       (http://www.gnu.org/copyleft/gpl.html)                     
C (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           
C (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            
C     With important contributions from:                           
C        M. Damian, Villanova University, USA                      
C        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
C                                                                  
C File                 : cbm4_ref_Hessian.f                        
C Time                 : Wed Mar  9 12:15:57 2022                  
C Working directory    : /home/kyriacos/CyprusInstitute/kpp/cbm4_ref
C Equation file        : cbm4_ref.kpp                              
C Output root filename : cbm4_ref                                  
C                                                                  
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C                                                                  
C Hessian - function for Hessian (Jac derivative w.r.t. variables) 
C   Arguments :                                                    
C      V         - Concentrations of variable species (local)      
C      F         - Concentrations of fixed species (local)         
C      RCT       - Rate constants (local)                          
C      HESS      - Hessian of Var (i.e. the 3-tensor d Jac / d Var)
C                                                                  
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      SUBROUTINE Hessian ( V, F, RCT, HESS )

      IMPLICIT NONE
      INCLUDE 'cbm4_ref_Parameters.h'

C V - Concentrations of variable species (local)                   
      REAL*8 V(NVAR)
C F - Concentrations of fixed species (local)                      
      REAL*8 F(NFIX)
C RCT - Rate constants (local)                                     
      REAL*8 RCT(NREACT)
C HESS - Hessian of Var (i.e. the 3-tensor d Jac / d Var)          
      REAL*8 HESS(NHESS)

C --------------------------------------------------------         
C Note: HESS is represented in coordinate sparse format:           
C       HESS(m) = d^2 f_i / dv_j dv_k = d Jac_{i,j} / dv_k         
C       where i = IHESS_I(m), j = IHESS_J(m), k = IHESS_K(m).      
C --------------------------------------------------------         
C Note: d^2 f_i / dv_j dv_k = d^2 f_i / dv_k dv_j,                 
C       therefore only the terms d^2 f_i / dv_j dv_k               
C       with j <= k are computed and stored in HESS.               
C --------------------------------------------------------         

C Local variables                                                  
C D2A - Second derivatives of equation rates                       
      REAL*8 D2A(59)

C Computation of the second derivatives of equation rates          
C D2A(1) = d^2 A(3) / dV(25)dV(31)                                 
      D2A(1) = RCT(3)
C D2A(2) = d^2 A(4) / dV(26)dV(29)                                 
      D2A(2) = 9.3e-12
C D2A(3) = d^2 A(5) / dV(26)dV(29)                                 
      D2A(3) = RCT(5)
C D2A(4) = d^2 A(6) / dV(29)dV(31)                                 
      D2A(4) = RCT(6)
C D2A(5) = d^2 A(7) / dV(25)dV(26)                                 
      D2A(5) = RCT(7)
C D2A(6) = d^2 A(12) / dV(25)dV(27)                                
      D2A(6) = RCT(12)
C D2A(7) = d^2 A(13) / dV(25)dV(28)                                
      D2A(7) = RCT(13)
C D2A(8) = d^2 A(15) / dV(30)dV(31)                                
      D2A(8) = RCT(15)
C D2A(9) = d^2 A(16) / dV(26)dV(30)                                
      D2A(9) = RCT(16)
C D2A(10) = d^2 A(17) / dV(26)dV(30)                               
      D2A(10) = RCT(17)
C D2A(11) = d^2 A(20)/{dV(31)dV(31)}                               
      D2A(11) = RCT(20)*2
C D2A(12) = d^2 A(21) / dV(26)dV(31)                               
      D2A(12) = 4.39999e-40*F(1)
C D2A(13) = d^2 A(22) / dV(27)dV(31)                               
      D2A(13) = RCT(22)
C D2A(14) = d^2 A(24) / dV(9)dV(27)                                
      D2A(14) = 6.6e-12
C D2A(15) = d^2 A(25)/{dV(9)dV(9)}                                 
      D2A(15) = 1e-20*2
C D2A(16) = d^2 A(26) / dV(26)dV(27)                               
      D2A(16) = RCT(26)
C D2A(17) = d^2 A(27) / dV(12)dV(27)                               
      D2A(17) = RCT(27)
C D2A(18) = d^2 A(28) / dV(28)dV(31)                               
      D2A(18) = RCT(28)
C D2A(19) = d^2 A(29) / dV(26)dV(28)                               
      D2A(19) = RCT(29)
C D2A(20) = d^2 A(31) / dV(10)dV(27)                               
      D2A(20) = RCT(31)
C D2A(21) = d^2 A(32)/{dV(28)dV(28)}                               
      D2A(21) = RCT(32)*2
C D2A(22) = d^2 A(33)/{dV(28)dV(28)}                               
      D2A(22) = RCT(33)*2*F(1)
C D2A(23) = d^2 A(35) / dV(2)dV(27)                                
      D2A(23) = RCT(35)
C D2A(24) = d^2 A(36) / dV(16)dV(27)                               
      D2A(24) = 2.2e-13
C D2A(25) = d^2 A(37) / dV(21)dV(27)                               
      D2A(25) = 1e-11
C D2A(26) = d^2 A(40) / dV(21)dV(29)                               
      D2A(26) = RCT(40)
C D2A(27) = d^2 A(41) / dV(21)dV(30)                               
      D2A(27) = 6.3e-16
C D2A(28) = d^2 A(42) / dV(24)dV(29)                               
      D2A(28) = RCT(42)
C D2A(29) = d^2 A(43) / dV(24)dV(27)                               
      D2A(29) = RCT(43)
C D2A(30) = d^2 A(44) / dV(24)dV(30)                               
      D2A(30) = 2.5e-15
C D2A(31) = d^2 A(46) / dV(31)dV(32)                               
      D2A(31) = RCT(46)
C D2A(32) = d^2 A(47) / dV(26)dV(32)                               
      D2A(32) = RCT(47)
C D2A(33) = d^2 A(49)/{dV(32)dV(32)}                               
      D2A(33) = 2e-12*2
C D2A(34) = d^2 A(50) / dV(28)dV(32)                               
      D2A(34) = 6.5e-12
C D2A(35) = d^2 A(52) / dV(20)dV(27)                               
      D2A(35) = 8.1e-13
C D2A(36) = d^2 A(55) / dV(13)dV(26)                               
      D2A(36) = 1.5e-11
C D2A(37) = d^2 A(56) / dV(23)dV(29)                               
      D2A(37) = RCT(56)
C D2A(38) = d^2 A(57) / dV(23)dV(27)                               
      D2A(38) = RCT(57)
C D2A(39) = d^2 A(58) / dV(23)dV(25)                               
      D2A(39) = RCT(58)
C D2A(40) = d^2 A(59) / dV(23)dV(30)                               
      D2A(40) = 7.7e-15
C D2A(41) = d^2 A(60) / dV(17)dV(29)                               
      D2A(41) = RCT(60)
C D2A(42) = d^2 A(61) / dV(17)dV(27)                               
      D2A(42) = RCT(61)
C D2A(43) = d^2 A(62) / dV(17)dV(25)                               
      D2A(43) = RCT(62)
C D2A(44) = d^2 A(63) / dV(5)dV(27)                                
      D2A(44) = RCT(63)
C D2A(45) = d^2 A(64) / dV(11)dV(31)                               
      D2A(45) = 8.1e-12
C D2A(46) = d^2 A(66) / dV(14)dV(27)                               
      D2A(46) = 4.1e-11
C D2A(47) = d^2 A(67) / dV(14)dV(30)                               
      D2A(47) = 2.2e-11
C D2A(48) = d^2 A(68) / dV(4)dV(26)                                
      D2A(48) = 1.4e-11
C D2A(49) = d^2 A(69) / dV(7)dV(27)                                
      D2A(49) = RCT(69)
C D2A(50) = d^2 A(70) / dV(19)dV(27)                               
      D2A(50) = 3e-11
C D2A(51) = d^2 A(72) / dV(19)dV(25)                               
      D2A(51) = RCT(72)
C D2A(52) = d^2 A(73) / dV(15)dV(27)                               
      D2A(52) = 1.7e-11
C D2A(53) = d^2 A(75) / dV(22)dV(29)                               
      D2A(53) = 1.8e-11
C D2A(54) = d^2 A(76) / dV(22)dV(27)                               
      D2A(54) = 9.6e-11
C D2A(55) = d^2 A(77) / dV(22)dV(25)                               
      D2A(55) = 1.2e-17
C D2A(56) = d^2 A(78) / dV(22)dV(30)                               
      D2A(56) = 3.2e-13
C D2A(57) = d^2 A(79) / dV(18)dV(31)                               
      D2A(57) = 8.1e-12
C D2A(58) = d^2 A(80)/{dV(18)dV(18)}                               
      D2A(58) = RCT(80)*2
C D2A(59) = d^2 A(81) / dV(8)dV(31)                                
      D2A(59) = 6.8e-13

C Computation of the Jacobian derivative                           
C HESS(1) = d^2 Vdot(2)/{dV(2)dV(27)} = d^2 Vdot(2)/{dV(27)dV(2)}  
      HESS(1) = -D2A(23)
C HESS(2) = d^2 Vdot(2)/{dV(28)dV(28)} = d^2 Vdot(2)/{dV(28)dV(28)}
      HESS(2) = D2A(21)+D2A(22)
C HESS(3) = d^2 Vdot(3)/{dV(26)dV(32)} = d^2 Vdot(3)/{dV(32)dV(26)}
      HESS(3) = D2A(32)
C HESS(4) = d^2 Vdot(4)/{dV(4)dV(26)} = d^2 Vdot(4)/{dV(26)dV(4)}  
      HESS(4) = -D2A(48)
C HESS(5) = d^2 Vdot(4)/{dV(14)dV(27)} = d^2 Vdot(4)/{dV(27)dV(14)}
      HESS(5) = 0.4*D2A(46)
C HESS(6) = d^2 Vdot(4)/{dV(14)dV(30)} = d^2 Vdot(4)/{dV(30)dV(14)}
      HESS(6) = D2A(47)
C HESS(7) = d^2 Vdot(5)/{dV(5)dV(27)} = d^2 Vdot(5)/{dV(27)dV(5)}  
      HESS(7) = -D2A(44)
C HESS(8) = d^2 Vdot(6)/{dV(26)dV(30)} = d^2 Vdot(6)/{dV(30)dV(26)}
      HESS(8) = D2A(10)
C HESS(9) = d^2 Vdot(7)/{dV(7)dV(27)} = d^2 Vdot(7)/{dV(27)dV(7)}  
      HESS(9) = -D2A(49)
C HESS(10) = d^2 Vdot(8)/{dV(8)dV(31)} = d^2 Vdot(8)/{dV(31)dV(8)} 
      HESS(10) = -D2A(59)
C HESS(11) = d^2 Vdot(8)/{dV(20)dV(27)} = d^2 Vdot(8)/{dV(27)dV(20)}
      HESS(11) = 0.13*D2A(35)
C HESS(12) = d^2 Vdot(8)/{dV(22)dV(27)} = d^2 Vdot(8)/{dV(27)dV(22)}
      HESS(12) = 0.13*D2A(54)
C HESS(13) = d^2 Vdot(8)/{dV(22)dV(30)} = d^2 Vdot(8)/{dV(30)dV(22)}
      HESS(13) = D2A(56)
C HESS(14) = d^2 Vdot(8)/{dV(23)dV(29)} = d^2 Vdot(8)/{dV(29)dV(23)}
      HESS(14) = 0.02*D2A(37)
C HESS(15) = d^2 Vdot(8)/{dV(23)dV(30)} = d^2 Vdot(8)/{dV(30)dV(23)}
      HESS(15) = 0.09*D2A(40)
C HESS(16) = d^2 Vdot(9)/{dV(9)dV(9)} = d^2 Vdot(9)/{dV(9)dV(9)}   
      HESS(16) = -2*D2A(15)
C HESS(17) = d^2 Vdot(9)/{dV(9)dV(27)} = d^2 Vdot(9)/{dV(27)dV(9)} 
      HESS(17) = -D2A(14)
C HESS(18) = d^2 Vdot(9)/{dV(26)dV(31)} = d^2 Vdot(9)/{dV(31)dV(26)}
      HESS(18) = 2*D2A(12)
C HESS(19) = d^2 Vdot(9)/{dV(27)dV(31)} = d^2 Vdot(9)/{dV(31)dV(27)}
      HESS(19) = D2A(13)
C HESS(20) = d^2 Vdot(10)/{dV(10)dV(27)} = d^2 Vdot(10)/{dV(27)dV(10)}
      HESS(20) = -D2A(20)
C HESS(21) = d^2 Vdot(10)/{dV(26)dV(28)} = d^2 Vdot(10)/{dV(28)dV(26)}
      HESS(21) = D2A(19)
C HESS(22) = d^2 Vdot(11)/{dV(5)dV(27)} = d^2 Vdot(11)/{dV(27)dV(5)}
      HESS(22) = 0.56*D2A(44)
C HESS(23) = d^2 Vdot(11)/{dV(7)dV(27)} = d^2 Vdot(11)/{dV(27)dV(7)}
      HESS(23) = 0.3*D2A(49)
C HESS(24) = d^2 Vdot(11)/{dV(11)dV(31)} = d^2 Vdot(11)/{dV(31)dV(11)}
      HESS(24) = -D2A(45)
C HESS(25) = d^2 Vdot(12)/{dV(12)dV(27)} = d^2 Vdot(12)/{dV(27)dV(12)}
      HESS(25) = -D2A(17)
C HESS(26) = d^2 Vdot(12)/{dV(14)dV(30)} = d^2 Vdot(12)/{dV(30)dV(14)}
      HESS(26) = D2A(47)
C HESS(27) = d^2 Vdot(12)/{dV(21)dV(30)} = d^2 Vdot(12)/{dV(30)dV(21)}
      HESS(27) = D2A(27)
C HESS(28) = d^2 Vdot(12)/{dV(24)dV(30)} = d^2 Vdot(12)/{dV(30)dV(24)}
      HESS(28) = D2A(30)
C HESS(29) = d^2 Vdot(12)/{dV(26)dV(27)} = d^2 Vdot(12)/{dV(27)dV(26)}
      HESS(29) = D2A(16)
C HESS(30) = d^2 Vdot(13)/{dV(13)dV(26)} = d^2 Vdot(13)/{dV(26)dV(13)}
      HESS(30) = -D2A(36)
C HESS(31) = d^2 Vdot(13)/{dV(20)dV(27)} = d^2 Vdot(13)/{dV(27)dV(20)}
      HESS(31) = 0.76*D2A(35)
C HESS(32) = d^2 Vdot(14)/{dV(5)dV(27)} = d^2 Vdot(14)/{dV(27)dV(5)}
      HESS(32) = 0.36*D2A(44)
C HESS(33) = d^2 Vdot(14)/{dV(7)dV(27)} = d^2 Vdot(14)/{dV(27)dV(7)}
      HESS(33) = 0.2*D2A(49)
C HESS(34) = d^2 Vdot(14)/{dV(14)dV(27)} = d^2 Vdot(14)/{dV(27)dV(14)}
      HESS(34) = -D2A(46)
C HESS(35) = d^2 Vdot(14)/{dV(14)dV(30)} = d^2 Vdot(14)/{dV(30)dV(14)}
      HESS(35) = -D2A(47)
C HESS(36) = d^2 Vdot(15)/{dV(7)dV(27)} = d^2 Vdot(15)/{dV(27)dV(7)}
      HESS(36) = 0.8*D2A(49)
C HESS(37) = d^2 Vdot(15)/{dV(15)dV(27)} = d^2 Vdot(15)/{dV(27)dV(15)}
      HESS(37) = -D2A(52)
C HESS(38) = d^2 Vdot(15)/{dV(19)dV(25)} = d^2 Vdot(15)/{dV(25)dV(19)}
      HESS(38) = 0.2*D2A(51)
C HESS(39) = d^2 Vdot(15)/{dV(22)dV(25)} = d^2 Vdot(15)/{dV(25)dV(22)}
      HESS(39) = 0.2*D2A(55)
C HESS(40) = d^2 Vdot(15)/{dV(22)dV(27)} = d^2 Vdot(15)/{dV(27)dV(22)}
      HESS(40) = 0.4*D2A(54)
C HESS(41) = d^2 Vdot(16)/{dV(16)dV(27)} = d^2 Vdot(16)/{dV(27)dV(16)}
      HESS(41) = -D2A(24)
C HESS(42) = d^2 Vdot(16)/{dV(17)dV(25)} = d^2 Vdot(16)/{dV(25)dV(17)}
      HESS(42) = 0.42*D2A(43)
C HESS(43) = d^2 Vdot(16)/{dV(17)dV(29)} = d^2 Vdot(16)/{dV(29)dV(17)}
      HESS(43) = D2A(41)
C HESS(44) = d^2 Vdot(16)/{dV(19)dV(25)} = d^2 Vdot(16)/{dV(25)dV(19)}
      HESS(44) = 0.69*D2A(51)
C HESS(45) = d^2 Vdot(16)/{dV(19)dV(27)} = d^2 Vdot(16)/{dV(27)dV(19)}
      HESS(45) = 2*D2A(50)
C HESS(46) = d^2 Vdot(16)/{dV(21)dV(27)} = d^2 Vdot(16)/{dV(27)dV(21)}
      HESS(46) = D2A(25)
C HESS(47) = d^2 Vdot(16)/{dV(21)dV(29)} = d^2 Vdot(16)/{dV(29)dV(21)}
      HESS(47) = D2A(26)
C HESS(48) = d^2 Vdot(16)/{dV(21)dV(30)} = d^2 Vdot(16)/{dV(30)dV(21)}
      HESS(48) = D2A(27)
C HESS(49) = d^2 Vdot(16)/{dV(22)dV(25)} = d^2 Vdot(16)/{dV(25)dV(22)}
      HESS(49) = 0.06*D2A(55)
C HESS(50) = d^2 Vdot(16)/{dV(22)dV(29)} = d^2 Vdot(16)/{dV(29)dV(22)}
      HESS(50) = 0.5*D2A(53)
C HESS(51) = d^2 Vdot(16)/{dV(23)dV(25)} = d^2 Vdot(16)/{dV(25)dV(23)}
      HESS(51) = 0.33*D2A(39)
C HESS(52) = d^2 Vdot(16)/{dV(23)dV(29)} = d^2 Vdot(16)/{dV(29)dV(23)}
      HESS(52) = 0.3*D2A(37)
C HESS(53) = d^2 Vdot(17)/{dV(17)dV(25)} = d^2 Vdot(17)/{dV(25)dV(17)}
      HESS(53) = -D2A(43)
C HESS(54) = d^2 Vdot(17)/{dV(17)dV(27)} = d^2 Vdot(17)/{dV(27)dV(17)}
      HESS(54) = -D2A(42)
C HESS(55) = d^2 Vdot(17)/{dV(17)dV(29)} = d^2 Vdot(17)/{dV(29)dV(17)}
      HESS(55) = -D2A(41)
C HESS(56) = d^2 Vdot(17)/{dV(22)dV(25)} = d^2 Vdot(17)/{dV(25)dV(22)}
      HESS(56) = 0.55*D2A(55)
C HESS(57) = d^2 Vdot(17)/{dV(22)dV(27)} = d^2 Vdot(17)/{dV(27)dV(22)}
      HESS(57) = D2A(54)
C HESS(58) = d^2 Vdot(17)/{dV(22)dV(29)} = d^2 Vdot(17)/{dV(29)dV(22)}
      HESS(58) = 0.45*D2A(53)
C HESS(59) = d^2 Vdot(18)/{dV(5)dV(27)} = d^2 Vdot(18)/{dV(27)dV(5)}
      HESS(59) = 0.08*D2A(44)
C HESS(60) = d^2 Vdot(18)/{dV(7)dV(27)} = d^2 Vdot(18)/{dV(27)dV(7)}
      HESS(60) = 0.5*D2A(49)
C HESS(61) = d^2 Vdot(18)/{dV(14)dV(27)} = d^2 Vdot(18)/{dV(27)dV(14)}
      HESS(61) = 0.6*D2A(46)
C HESS(62) = d^2 Vdot(18)/{dV(15)dV(27)} = d^2 Vdot(18)/{dV(27)dV(15)}
      HESS(62) = D2A(52)
C HESS(63) = d^2 Vdot(18)/{dV(17)dV(27)} = d^2 Vdot(18)/{dV(27)dV(17)}
      HESS(63) = D2A(42)
C HESS(64) = d^2 Vdot(18)/{dV(17)dV(29)} = d^2 Vdot(18)/{dV(29)dV(17)}
      HESS(64) = 0.7*D2A(41)
C HESS(65) = d^2 Vdot(18)/{dV(18)dV(18)} = d^2 Vdot(18)/{dV(18)dV(18)}
      HESS(65) = -2*D2A(58)
C HESS(66) = d^2 Vdot(18)/{dV(18)dV(31)} = d^2 Vdot(18)/{dV(31)dV(18)}
      HESS(66) = -D2A(57)
C HESS(67) = d^2 Vdot(18)/{dV(19)dV(25)} = d^2 Vdot(18)/{dV(25)dV(19)}
      HESS(67) = 0.03*D2A(51)
C HESS(68) = d^2 Vdot(18)/{dV(19)dV(27)} = d^2 Vdot(18)/{dV(27)dV(19)}
      HESS(68) = D2A(50)
C HESS(69) = d^2 Vdot(18)/{dV(20)dV(27)} = d^2 Vdot(18)/{dV(27)dV(20)}
      HESS(69) = 0.87*D2A(35)
C HESS(70) = d^2 Vdot(18)/{dV(22)dV(27)} = d^2 Vdot(18)/{dV(27)dV(22)}
      HESS(70) = D2A(54)
C HESS(71) = d^2 Vdot(18)/{dV(22)dV(29)} = d^2 Vdot(18)/{dV(29)dV(22)}
      HESS(71) = 0.5*D2A(53)
C HESS(72) = d^2 Vdot(18)/{dV(23)dV(25)} = d^2 Vdot(18)/{dV(25)dV(23)}
      HESS(72) = 0.22*D2A(39)
C HESS(73) = d^2 Vdot(18)/{dV(23)dV(27)} = d^2 Vdot(18)/{dV(27)dV(23)}
      HESS(73) = D2A(38)
C HESS(74) = d^2 Vdot(18)/{dV(23)dV(29)} = d^2 Vdot(18)/{dV(29)dV(23)}
      HESS(74) = 0.28*D2A(37)
C HESS(75) = d^2 Vdot(18)/{dV(23)dV(30)} = d^2 Vdot(18)/{dV(30)dV(23)}
      HESS(75) = 0.91*D2A(40)
C HESS(76) = d^2 Vdot(18)/{dV(28)dV(32)} = d^2 Vdot(18)/{dV(32)dV(28)}
      HESS(76) = 0.79*D2A(34)
C HESS(77) = d^2 Vdot(18)/{dV(31)dV(32)} = d^2 Vdot(18)/{dV(32)dV(31)}
      HESS(77) = D2A(31)
C HESS(78) = d^2 Vdot(18)/{dV(32)dV(32)} = d^2 Vdot(18)/{dV(32)dV(32)}
      HESS(78) = 2*D2A(33)
C HESS(79) = d^2 Vdot(19)/{dV(11)dV(31)} = d^2 Vdot(19)/{dV(31)dV(11)}
      HESS(79) = 0.9*D2A(45)
C HESS(80) = d^2 Vdot(19)/{dV(14)dV(27)} = d^2 Vdot(19)/{dV(27)dV(14)}
      HESS(80) = 0.3*D2A(46)
C HESS(81) = d^2 Vdot(19)/{dV(19)dV(25)} = d^2 Vdot(19)/{dV(25)dV(19)}
      HESS(81) = -D2A(51)
C HESS(82) = d^2 Vdot(19)/{dV(19)dV(27)} = d^2 Vdot(19)/{dV(27)dV(19)}
      HESS(82) = -D2A(50)
C HESS(83) = d^2 Vdot(20)/{dV(7)dV(27)} = d^2 Vdot(20)/{dV(27)dV(7)}
      HESS(83) = 1.1*D2A(49)
C HESS(84) = d^2 Vdot(20)/{dV(20)dV(27)} = d^2 Vdot(20)/{dV(27)dV(20)}
      HESS(84) = -1.11*D2A(35)
C HESS(85) = d^2 Vdot(20)/{dV(22)dV(25)} = d^2 Vdot(20)/{dV(25)dV(22)}
      HESS(85) = 0.1*D2A(55)
C HESS(86) = d^2 Vdot(20)/{dV(22)dV(29)} = d^2 Vdot(20)/{dV(29)dV(22)}
      HESS(86) = 0.9*D2A(53)
C HESS(87) = d^2 Vdot(20)/{dV(23)dV(25)} = d^2 Vdot(20)/{dV(25)dV(23)}
      HESS(87) = -D2A(39)
C HESS(88) = d^2 Vdot(20)/{dV(23)dV(27)} = d^2 Vdot(20)/{dV(27)dV(23)}
      HESS(88) = -D2A(38)
C HESS(89) = d^2 Vdot(20)/{dV(23)dV(29)} = d^2 Vdot(20)/{dV(29)dV(23)}
      HESS(89) = 0.22*D2A(37)
C HESS(90) = d^2 Vdot(20)/{dV(23)dV(30)} = d^2 Vdot(20)/{dV(30)dV(23)}
      HESS(90) = -D2A(40)
C HESS(91) = d^2 Vdot(21)/{dV(17)dV(25)} = d^2 Vdot(21)/{dV(25)dV(17)}
      HESS(91) = D2A(43)
C HESS(92) = d^2 Vdot(21)/{dV(17)dV(27)} = d^2 Vdot(21)/{dV(27)dV(17)}
      HESS(92) = 1.56*D2A(42)
C HESS(93) = d^2 Vdot(21)/{dV(17)dV(29)} = d^2 Vdot(21)/{dV(29)dV(17)}
      HESS(93) = D2A(41)
C HESS(94) = d^2 Vdot(21)/{dV(19)dV(25)} = d^2 Vdot(21)/{dV(25)dV(19)}
      HESS(94) = 0.7*D2A(51)
C HESS(95) = d^2 Vdot(21)/{dV(19)dV(27)} = d^2 Vdot(21)/{dV(27)dV(19)}
      HESS(95) = D2A(50)
C HESS(96) = d^2 Vdot(21)/{dV(21)dV(27)} = d^2 Vdot(21)/{dV(27)dV(21)}
      HESS(96) = -D2A(25)
C HESS(97) = d^2 Vdot(21)/{dV(21)dV(29)} = d^2 Vdot(21)/{dV(29)dV(21)}
      HESS(97) = -D2A(26)
C HESS(98) = d^2 Vdot(21)/{dV(21)dV(30)} = d^2 Vdot(21)/{dV(30)dV(21)}
      HESS(98) = -D2A(27)
C HESS(99) = d^2 Vdot(21)/{dV(22)dV(25)} = d^2 Vdot(21)/{dV(25)dV(22)}
      HESS(99) = D2A(55)
C HESS(100) = d^2 Vdot(21)/{dV(22)dV(27)} = d^2 Vdot(21)/{dV(27)dV(22)}
      HESS(100) = D2A(54)
C HESS(101) = d^2 Vdot(21)/{dV(23)dV(25)} = d^2 Vdot(21)/{dV(25)dV(23)}
      HESS(101) = 0.74*D2A(39)
C HESS(102) = d^2 Vdot(21)/{dV(23)dV(27)} = d^2 Vdot(21)/{dV(27)dV(23)}
      HESS(102) = D2A(38)
C HESS(103) = d^2 Vdot(21)/{dV(23)dV(29)} = d^2 Vdot(21)/{dV(29)dV(23)}
      HESS(103) = 0.2*D2A(37)
C HESS(104) = d^2 Vdot(21)/{dV(23)dV(30)} = d^2 Vdot(21)/{dV(30)dV(23)}
      HESS(104) = D2A(40)
C HESS(105) = d^2 Vdot(21)/{dV(28)dV(32)} = d^2 Vdot(21)/{dV(32)dV(28)}
      HESS(105) = 0.79*D2A(34)
C HESS(106) = d^2 Vdot(21)/{dV(31)dV(32)} = d^2 Vdot(21)/{dV(32)dV(31)}
      HESS(106) = D2A(31)
C HESS(107) = d^2 Vdot(21)/{dV(32)dV(32)} = d^2 Vdot(21)/{dV(32)dV(32)}
      HESS(107) = 2*D2A(33)
C HESS(108) = d^2 Vdot(22)/{dV(22)dV(25)} = d^2 Vdot(22)/{dV(25)dV(22)}
      HESS(108) = -D2A(55)
C HESS(109) = d^2 Vdot(22)/{dV(22)dV(27)} = d^2 Vdot(22)/{dV(27)dV(22)}
      HESS(109) = -D2A(54)
C HESS(110) = d^2 Vdot(22)/{dV(22)dV(29)} = d^2 Vdot(22)/{dV(29)dV(22)}
      HESS(110) = -D2A(53)
C HESS(111) = d^2 Vdot(22)/{dV(22)dV(30)} = d^2 Vdot(22)/{dV(30)dV(22)}
      HESS(111) = -D2A(56)
C HESS(112) = d^2 Vdot(23)/{dV(22)dV(29)} = d^2 Vdot(23)/{dV(29)dV(22)}
      HESS(112) = 0.55*D2A(53)
C HESS(113) = d^2 Vdot(23)/{dV(23)dV(25)} = d^2 Vdot(23)/{dV(25)dV(23)}
      HESS(113) = -D2A(39)
C HESS(114) = d^2 Vdot(23)/{dV(23)dV(27)} = d^2 Vdot(23)/{dV(27)dV(23)}
      HESS(114) = -D2A(38)
C HESS(115) = d^2 Vdot(23)/{dV(23)dV(29)} = d^2 Vdot(23)/{dV(29)dV(23)}
      HESS(115) = -D2A(37)
C HESS(116) = d^2 Vdot(23)/{dV(23)dV(30)} = d^2 Vdot(23)/{dV(30)dV(23)}
      HESS(116) = -D2A(40)
C HESS(117) = d^2 Vdot(24)/{dV(17)dV(27)} = d^2 Vdot(24)/{dV(27)dV(17)}
      HESS(117) = 0.22*D2A(42)
C HESS(118) = d^2 Vdot(24)/{dV(19)dV(25)} = d^2 Vdot(24)/{dV(25)dV(19)}
      HESS(118) = 0.03*D2A(51)
C HESS(119) = d^2 Vdot(24)/{dV(20)dV(27)} = d^2 Vdot(24)/{dV(27)dV(20)}
      HESS(119) = 0.11*D2A(35)
C HESS(120) = d^2 Vdot(24)/{dV(22)dV(25)} = d^2 Vdot(24)/{dV(25)dV(22)}
      HESS(120) = 0.4*D2A(55)
C HESS(121) = d^2 Vdot(24)/{dV(22)dV(27)} = d^2 Vdot(24)/{dV(27)dV(22)}
      HESS(121) = 0.2*D2A(54)
C HESS(122) = d^2 Vdot(24)/{dV(22)dV(29)} = d^2 Vdot(24)/{dV(29)dV(22)}
      HESS(122) = 0.8*D2A(53)
C HESS(123) = d^2 Vdot(24)/{dV(23)dV(25)} = d^2 Vdot(24)/{dV(25)dV(23)}
      HESS(123) = 0.5*D2A(39)
C HESS(124) = d^2 Vdot(24)/{dV(23)dV(27)} = d^2 Vdot(24)/{dV(27)dV(23)}
      HESS(124) = D2A(38)
C HESS(125) = d^2 Vdot(24)/{dV(23)dV(29)} = d^2 Vdot(24)/{dV(29)dV(23)}
      HESS(125) = 0.63*D2A(37)
C HESS(126) = d^2 Vdot(24)/{dV(23)dV(30)} = d^2 Vdot(24)/{dV(30)dV(23)}
      HESS(126) = D2A(40)
C HESS(127) = d^2 Vdot(24)/{dV(24)dV(27)} = d^2 Vdot(24)/{dV(27)dV(24)}
      HESS(127) = -D2A(29)
C HESS(128) = d^2 Vdot(24)/{dV(24)dV(29)} = d^2 Vdot(24)/{dV(29)dV(24)}
      HESS(128) = -D2A(28)
C HESS(129) = d^2 Vdot(24)/{dV(24)dV(30)} = d^2 Vdot(24)/{dV(30)dV(24)}
      HESS(129) = -D2A(30)
C HESS(130) = d^2 Vdot(25)/{dV(17)dV(25)} = d^2 Vdot(25)/{dV(25)dV(17)}
      HESS(130) = -D2A(43)
C HESS(131) = d^2 Vdot(25)/{dV(19)dV(25)} = d^2 Vdot(25)/{dV(25)dV(19)}
      HESS(131) = -D2A(51)
C HESS(132) = d^2 Vdot(25)/{dV(22)dV(25)} = d^2 Vdot(25)/{dV(25)dV(22)}
      HESS(132) = -D2A(55)
C HESS(133) = d^2 Vdot(25)/{dV(23)dV(25)} = d^2 Vdot(25)/{dV(25)dV(23)}
      HESS(133) = -D2A(39)
C HESS(134) = d^2 Vdot(25)/{dV(25)dV(26)} = d^2 Vdot(25)/{dV(26)dV(25)}
      HESS(134) = -D2A(5)
C HESS(135) = d^2 Vdot(25)/{dV(25)dV(27)} = d^2 Vdot(25)/{dV(27)dV(25)}
      HESS(135) = -D2A(6)
C HESS(136) = d^2 Vdot(25)/{dV(25)dV(28)} = d^2 Vdot(25)/{dV(28)dV(25)}
      HESS(136) = -D2A(7)
C HESS(137) = d^2 Vdot(25)/{dV(25)dV(31)} = d^2 Vdot(25)/{dV(31)dV(25)}
      HESS(137) = -D2A(1)
C HESS(138) = d^2 Vdot(26)/{dV(4)dV(26)} = d^2 Vdot(26)/{dV(26)dV(4)}
      HESS(138) = -D2A(48)
C HESS(139) = d^2 Vdot(26)/{dV(9)dV(9)} = d^2 Vdot(26)/{dV(9)dV(9)}
      HESS(139) = D2A(15)
C HESS(140) = d^2 Vdot(26)/{dV(9)dV(27)} = d^2 Vdot(26)/{dV(27)dV(9)}
      HESS(140) = D2A(14)
C HESS(141) = d^2 Vdot(26)/{dV(10)dV(27)} = d^2 Vdot(26)/{dV(27)dV(10)}
      HESS(141) = D2A(20)
C HESS(142) = d^2 Vdot(26)/{dV(11)dV(31)} = d^2 Vdot(26)/{dV(31)dV(11)}
      HESS(142) = 0.9*D2A(45)
C HESS(143) = d^2 Vdot(26)/{dV(13)dV(26)} = d^2 Vdot(26)/{dV(26)dV(13)}
      HESS(143) = -D2A(36)
C HESS(144) = d^2 Vdot(26)/{dV(18)dV(31)} = d^2 Vdot(26)/{dV(31)dV(18)}
      HESS(144) = D2A(57)
C HESS(145) = d^2 Vdot(26)/{dV(23)dV(30)} = d^2 Vdot(26)/{dV(30)dV(23)}
      HESS(145) = D2A(40)
C HESS(146) = d^2 Vdot(26)/{dV(25)dV(26)} = d^2 Vdot(26)/{dV(26)dV(25)}
      HESS(146) = -D2A(5)
C HESS(147) = d^2 Vdot(26)/{dV(25)dV(31)} = d^2 Vdot(26)/{dV(31)dV(25)}
      HESS(147) = D2A(1)
C HESS(148) = d^2 Vdot(26)/{dV(26)dV(27)} = d^2 Vdot(26)/{dV(27)dV(26)}
      HESS(148) = -D2A(16)
C HESS(149) = d^2 Vdot(26)/{dV(26)dV(28)} = d^2 Vdot(26)/{dV(28)dV(26)}
      HESS(149) = -D2A(19)
C HESS(150) = d^2 Vdot(26)/{dV(26)dV(29)} = d^2 Vdot(26)/{dV(29)dV(26)}
      HESS(150) = -D2A(2)-D2A(3)
C HESS(151) = d^2 Vdot(26)/{dV(26)dV(30)} = d^2 Vdot(26)/{dV(30)dV(26)}
      HESS(151) = -D2A(10)
C HESS(152) = d^2 Vdot(26)/{dV(26)dV(31)} = d^2 Vdot(26)/{dV(31)dV(26)}
      HESS(152) = -D2A(12)
C HESS(153) = d^2 Vdot(26)/{dV(26)dV(32)} = d^2 Vdot(26)/{dV(32)dV(26)}
      HESS(153) = -D2A(32)
C HESS(154) = d^2 Vdot(26)/{dV(28)dV(31)} = d^2 Vdot(26)/{dV(31)dV(28)}
      HESS(154) = D2A(18)
C HESS(155) = d^2 Vdot(26)/{dV(29)dV(31)} = d^2 Vdot(26)/{dV(31)dV(29)}
      HESS(155) = D2A(4)
C HESS(156) = d^2 Vdot(26)/{dV(30)dV(31)} = d^2 Vdot(26)/{dV(31)dV(30)}
      HESS(156) = 2*D2A(8)
C HESS(157) = d^2 Vdot(26)/{dV(31)dV(31)} = d^2 Vdot(26)/{dV(31)dV(31)}
      HESS(157) = 2*D2A(11)
C HESS(158) = d^2 Vdot(26)/{dV(31)dV(32)} = d^2 Vdot(26)/{dV(32)dV(31)}
      HESS(158) = D2A(31)
C HESS(159) = d^2 Vdot(27)/{dV(2)dV(27)} = d^2 Vdot(27)/{dV(27)dV(2)}
      HESS(159) = -D2A(23)
C HESS(160) = d^2 Vdot(27)/{dV(5)dV(27)} = d^2 Vdot(27)/{dV(27)dV(5)}
      HESS(160) = -D2A(44)
C HESS(161) = d^2 Vdot(27)/{dV(7)dV(27)} = d^2 Vdot(27)/{dV(27)dV(7)}
      HESS(161) = -D2A(49)
C HESS(162) = d^2 Vdot(27)/{dV(9)dV(27)} = d^2 Vdot(27)/{dV(27)dV(9)}
      HESS(162) = -D2A(14)
C HESS(163) = d^2 Vdot(27)/{dV(10)dV(27)} = d^2 Vdot(27)/{dV(27)dV(10)}
      HESS(163) = -D2A(20)
C HESS(164) = d^2 Vdot(27)/{dV(12)dV(27)} = d^2 Vdot(27)/{dV(27)dV(12)}
      HESS(164) = -D2A(17)
C HESS(165) = d^2 Vdot(27)/{dV(14)dV(27)} = d^2 Vdot(27)/{dV(27)dV(14)}
      HESS(165) = -D2A(46)
C HESS(166) = d^2 Vdot(27)/{dV(15)dV(27)} = d^2 Vdot(27)/{dV(27)dV(15)}
      HESS(166) = -D2A(52)
C HESS(167) = d^2 Vdot(27)/{dV(16)dV(27)} = d^2 Vdot(27)/{dV(27)dV(16)}
      HESS(167) = -D2A(24)
C HESS(168) = d^2 Vdot(27)/{dV(17)dV(27)} = d^2 Vdot(27)/{dV(27)dV(17)}
      HESS(168) = -D2A(42)
C HESS(169) = d^2 Vdot(27)/{dV(17)dV(29)} = d^2 Vdot(27)/{dV(29)dV(17)}
      HESS(169) = 0.3*D2A(41)
C HESS(170) = d^2 Vdot(27)/{dV(19)dV(25)} = d^2 Vdot(27)/{dV(25)dV(19)}
      HESS(170) = 0.08*D2A(51)
C HESS(171) = d^2 Vdot(27)/{dV(19)dV(27)} = d^2 Vdot(27)/{dV(27)dV(19)}
      HESS(171) = -D2A(50)
C HESS(172) = d^2 Vdot(27)/{dV(20)dV(27)} = d^2 Vdot(27)/{dV(27)dV(20)}
      HESS(172) = -D2A(35)
C HESS(173) = d^2 Vdot(27)/{dV(21)dV(27)} = d^2 Vdot(27)/{dV(27)dV(21)}
      HESS(173) = -D2A(25)
C HESS(174) = d^2 Vdot(27)/{dV(21)dV(29)} = d^2 Vdot(27)/{dV(29)dV(21)}
      HESS(174) = D2A(26)
C HESS(175) = d^2 Vdot(27)/{dV(22)dV(25)} = d^2 Vdot(27)/{dV(25)dV(22)}
      HESS(175) = 0.1*D2A(55)
C HESS(176) = d^2 Vdot(27)/{dV(22)dV(27)} = d^2 Vdot(27)/{dV(27)dV(22)}
      HESS(176) = -D2A(54)
C HESS(177) = d^2 Vdot(27)/{dV(23)dV(25)} = d^2 Vdot(27)/{dV(25)dV(23)}
      HESS(177) = 0.1*D2A(39)
C HESS(178) = d^2 Vdot(27)/{dV(23)dV(27)} = d^2 Vdot(27)/{dV(27)dV(23)}
      HESS(178) = -D2A(38)
C HESS(179) = d^2 Vdot(27)/{dV(23)dV(29)} = d^2 Vdot(27)/{dV(29)dV(23)}
      HESS(179) = 0.2*D2A(37)
C HESS(180) = d^2 Vdot(27)/{dV(24)dV(27)} = d^2 Vdot(27)/{dV(27)dV(24)}
      HESS(180) = -D2A(29)
C HESS(181) = d^2 Vdot(27)/{dV(24)dV(29)} = d^2 Vdot(27)/{dV(29)dV(24)}
      HESS(181) = D2A(28)
C HESS(182) = d^2 Vdot(27)/{dV(25)dV(27)} = d^2 Vdot(27)/{dV(27)dV(25)}
      HESS(182) = -D2A(6)
C HESS(183) = d^2 Vdot(27)/{dV(25)dV(28)} = d^2 Vdot(27)/{dV(28)dV(25)}
      HESS(183) = D2A(7)
C HESS(184) = d^2 Vdot(27)/{dV(26)dV(27)} = d^2 Vdot(27)/{dV(27)dV(26)}
      HESS(184) = -D2A(16)
C HESS(185) = d^2 Vdot(27)/{dV(27)dV(31)} = d^2 Vdot(27)/{dV(31)dV(27)}
      HESS(185) = -D2A(13)
C HESS(186) = d^2 Vdot(27)/{dV(28)dV(31)} = d^2 Vdot(27)/{dV(31)dV(28)}
      HESS(186) = D2A(18)
C HESS(187) = d^2 Vdot(27)/{dV(28)dV(32)} = d^2 Vdot(27)/{dV(32)dV(28)}
      HESS(187) = 0.79*D2A(34)
C HESS(188) = d^2 Vdot(28)/{dV(2)dV(27)} = d^2 Vdot(28)/{dV(27)dV(2)}
      HESS(188) = D2A(23)
C HESS(189) = d^2 Vdot(28)/{dV(5)dV(27)} = d^2 Vdot(28)/{dV(27)dV(5)}
      HESS(189) = 0.44*D2A(44)
C HESS(190) = d^2 Vdot(28)/{dV(7)dV(27)} = d^2 Vdot(28)/{dV(27)dV(7)}
      HESS(190) = 0.7*D2A(49)
C HESS(191) = d^2 Vdot(28)/{dV(11)dV(31)} = d^2 Vdot(28)/{dV(31)dV(11)}
      HESS(191) = 0.9*D2A(45)
C HESS(192) = d^2 Vdot(28)/{dV(14)dV(27)} = d^2 Vdot(28)/{dV(27)dV(14)}
      HESS(192) = 0.6*D2A(46)
C HESS(193) = d^2 Vdot(28)/{dV(16)dV(27)} = d^2 Vdot(28)/{dV(27)dV(16)}
      HESS(193) = D2A(24)
C HESS(194) = d^2 Vdot(28)/{dV(17)dV(25)} = d^2 Vdot(28)/{dV(25)dV(17)}
      HESS(194) = 0.12*D2A(43)
C HESS(195) = d^2 Vdot(28)/{dV(17)dV(27)} = d^2 Vdot(28)/{dV(27)dV(17)}
      HESS(195) = D2A(42)
C HESS(196) = d^2 Vdot(28)/{dV(17)dV(29)} = d^2 Vdot(28)/{dV(29)dV(17)}
      HESS(196) = 1.7*D2A(41)
C HESS(197) = d^2 Vdot(28)/{dV(19)dV(25)} = d^2 Vdot(28)/{dV(25)dV(19)}
      HESS(197) = 0.76*D2A(51)
C HESS(198) = d^2 Vdot(28)/{dV(19)dV(27)} = d^2 Vdot(28)/{dV(27)dV(19)}
      HESS(198) = 2*D2A(50)
C HESS(199) = d^2 Vdot(28)/{dV(20)dV(27)} = d^2 Vdot(28)/{dV(27)dV(20)}
      HESS(199) = 0.11*D2A(35)
C HESS(200) = d^2 Vdot(28)/{dV(21)dV(27)} = d^2 Vdot(28)/{dV(27)dV(21)}
      HESS(200) = D2A(25)
C HESS(201) = d^2 Vdot(28)/{dV(21)dV(29)} = d^2 Vdot(28)/{dV(29)dV(21)}
      HESS(201) = D2A(26)
C HESS(202) = d^2 Vdot(28)/{dV(21)dV(30)} = d^2 Vdot(28)/{dV(30)dV(21)}
      HESS(202) = D2A(27)
C HESS(203) = d^2 Vdot(28)/{dV(22)dV(25)} = d^2 Vdot(28)/{dV(25)dV(22)}
      HESS(203) = 0.44*D2A(55)
C HESS(204) = d^2 Vdot(28)/{dV(22)dV(27)} = d^2 Vdot(28)/{dV(27)dV(22)}
      HESS(204) = 0.67*D2A(54)
C HESS(205) = d^2 Vdot(28)/{dV(22)dV(29)} = d^2 Vdot(28)/{dV(29)dV(22)}
      HESS(205) = 0.6*D2A(53)
C HESS(206) = d^2 Vdot(28)/{dV(23)dV(25)} = d^2 Vdot(28)/{dV(25)dV(23)}
      HESS(206) = 0.44*D2A(39)
C HESS(207) = d^2 Vdot(28)/{dV(23)dV(27)} = d^2 Vdot(28)/{dV(27)dV(23)}
      HESS(207) = D2A(38)
C HESS(208) = d^2 Vdot(28)/{dV(23)dV(29)} = d^2 Vdot(28)/{dV(29)dV(23)}
      HESS(208) = 0.38*D2A(37)
C HESS(209) = d^2 Vdot(28)/{dV(25)dV(27)} = d^2 Vdot(28)/{dV(27)dV(25)}
      HESS(209) = D2A(6)
C HESS(210) = d^2 Vdot(28)/{dV(25)dV(28)} = d^2 Vdot(28)/{dV(28)dV(25)}
      HESS(210) = -D2A(7)
C HESS(211) = d^2 Vdot(28)/{dV(26)dV(28)} = d^2 Vdot(28)/{dV(28)dV(26)}
      HESS(211) = -D2A(19)
C HESS(212) = d^2 Vdot(28)/{dV(28)dV(28)} = d^2 Vdot(28)/{dV(28)dV(28)}
      HESS(212) = -2*D2A(21)-2*D2A(22)
C HESS(213) = d^2 Vdot(28)/{dV(28)dV(31)} = d^2 Vdot(28)/{dV(31)dV(28)}
      HESS(213) = -D2A(18)
C HESS(214) = d^2 Vdot(28)/{dV(28)dV(32)} = d^2 Vdot(28)/{dV(32)dV(28)}
      HESS(214) = -0.21*D2A(34)
C HESS(215) = d^2 Vdot(28)/{dV(31)dV(32)} = d^2 Vdot(28)/{dV(32)dV(31)}
      HESS(215) = D2A(31)
C HESS(216) = d^2 Vdot(28)/{dV(32)dV(32)} = d^2 Vdot(28)/{dV(32)dV(32)}
      HESS(216) = 2*D2A(33)
C HESS(217) = d^2 Vdot(29)/{dV(17)dV(29)} = d^2 Vdot(29)/{dV(29)dV(17)}
      HESS(217) = -D2A(41)
C HESS(218) = d^2 Vdot(29)/{dV(21)dV(29)} = d^2 Vdot(29)/{dV(29)dV(21)}
      HESS(218) = -D2A(26)
C HESS(219) = d^2 Vdot(29)/{dV(22)dV(29)} = d^2 Vdot(29)/{dV(29)dV(22)}
      HESS(219) = -D2A(53)
C HESS(220) = d^2 Vdot(29)/{dV(23)dV(29)} = d^2 Vdot(29)/{dV(29)dV(23)}
      HESS(220) = -D2A(37)
C HESS(221) = d^2 Vdot(29)/{dV(24)dV(29)} = d^2 Vdot(29)/{dV(29)dV(24)}
      HESS(221) = -D2A(28)
C HESS(222) = d^2 Vdot(29)/{dV(26)dV(29)} = d^2 Vdot(29)/{dV(29)dV(26)}
      HESS(222) = -D2A(2)-D2A(3)
C HESS(223) = d^2 Vdot(29)/{dV(29)dV(31)} = d^2 Vdot(29)/{dV(31)dV(29)}
      HESS(223) = -D2A(4)
C HESS(224) = d^2 Vdot(30)/{dV(12)dV(27)} = d^2 Vdot(30)/{dV(27)dV(12)}
      HESS(224) = D2A(17)
C HESS(225) = d^2 Vdot(30)/{dV(14)dV(30)} = d^2 Vdot(30)/{dV(30)dV(14)}
      HESS(225) = -D2A(47)
C HESS(226) = d^2 Vdot(30)/{dV(21)dV(30)} = d^2 Vdot(30)/{dV(30)dV(21)}
      HESS(226) = -D2A(27)
C HESS(227) = d^2 Vdot(30)/{dV(22)dV(30)} = d^2 Vdot(30)/{dV(30)dV(22)}
      HESS(227) = -D2A(56)
C HESS(228) = d^2 Vdot(30)/{dV(23)dV(30)} = d^2 Vdot(30)/{dV(30)dV(23)}
      HESS(228) = -D2A(40)
C HESS(229) = d^2 Vdot(30)/{dV(24)dV(30)} = d^2 Vdot(30)/{dV(30)dV(24)}
      HESS(229) = -D2A(30)
C HESS(230) = d^2 Vdot(30)/{dV(25)dV(26)} = d^2 Vdot(30)/{dV(26)dV(25)}
      HESS(230) = D2A(5)
C HESS(231) = d^2 Vdot(30)/{dV(26)dV(29)} = d^2 Vdot(30)/{dV(29)dV(26)}
      HESS(231) = D2A(3)
C HESS(232) = d^2 Vdot(30)/{dV(26)dV(30)} = d^2 Vdot(30)/{dV(30)dV(26)}
      HESS(232) = -D2A(9)-D2A(10)
C HESS(233) = d^2 Vdot(30)/{dV(30)dV(31)} = d^2 Vdot(30)/{dV(31)dV(30)}
      HESS(233) = -D2A(8)
C HESS(234) = d^2 Vdot(31)/{dV(8)dV(31)} = d^2 Vdot(31)/{dV(31)dV(8)}
      HESS(234) = -D2A(59)
C HESS(235) = d^2 Vdot(31)/{dV(9)dV(9)} = d^2 Vdot(31)/{dV(9)dV(9)}
      HESS(235) = D2A(15)
C HESS(236) = d^2 Vdot(31)/{dV(11)dV(31)} = d^2 Vdot(31)/{dV(31)dV(11)}
      HESS(236) = -D2A(45)
C HESS(237) = d^2 Vdot(31)/{dV(18)dV(31)} = d^2 Vdot(31)/{dV(31)dV(18)}
      HESS(237) = -D2A(57)
C HESS(238) = d^2 Vdot(31)/{dV(25)dV(31)} = d^2 Vdot(31)/{dV(31)dV(25)}
      HESS(238) = -D2A(1)
C HESS(239) = d^2 Vdot(31)/{dV(26)dV(29)} = d^2 Vdot(31)/{dV(29)dV(26)}
      HESS(239) = D2A(2)
C HESS(240) = d^2 Vdot(31)/{dV(26)dV(30)} = d^2 Vdot(31)/{dV(30)dV(26)}
      HESS(240) = D2A(9)
C HESS(241) = d^2 Vdot(31)/{dV(26)dV(31)} = d^2 Vdot(31)/{dV(31)dV(26)}
      HESS(241) = -D2A(12)
C HESS(242) = d^2 Vdot(31)/{dV(27)dV(31)} = d^2 Vdot(31)/{dV(31)dV(27)}
      HESS(242) = -D2A(13)
C HESS(243) = d^2 Vdot(31)/{dV(28)dV(31)} = d^2 Vdot(31)/{dV(31)dV(28)}
      HESS(243) = -D2A(18)
C HESS(244) = d^2 Vdot(31)/{dV(29)dV(31)} = d^2 Vdot(31)/{dV(31)dV(29)}
      HESS(244) = -D2A(4)
C HESS(245) = d^2 Vdot(31)/{dV(30)dV(31)} = d^2 Vdot(31)/{dV(31)dV(30)}
      HESS(245) = -D2A(8)
C HESS(246) = d^2 Vdot(31)/{dV(31)dV(31)} = d^2 Vdot(31)/{dV(31)dV(31)}
      HESS(246) = -2*D2A(11)
C HESS(247) = d^2 Vdot(31)/{dV(31)dV(32)} = d^2 Vdot(31)/{dV(32)dV(31)}
      HESS(247) = -D2A(31)
C HESS(248) = d^2 Vdot(32)/{dV(15)dV(27)} = d^2 Vdot(32)/{dV(27)dV(15)}
      HESS(248) = D2A(52)
C HESS(249) = d^2 Vdot(32)/{dV(19)dV(25)} = d^2 Vdot(32)/{dV(25)dV(19)}
      HESS(249) = 0.62*D2A(51)
C HESS(250) = d^2 Vdot(32)/{dV(19)dV(27)} = d^2 Vdot(32)/{dV(27)dV(19)}
      HESS(250) = D2A(50)
C HESS(251) = d^2 Vdot(32)/{dV(22)dV(27)} = d^2 Vdot(32)/{dV(27)dV(22)}
      HESS(251) = 0.2*D2A(54)
C HESS(252) = d^2 Vdot(32)/{dV(24)dV(27)} = d^2 Vdot(32)/{dV(27)dV(24)}
      HESS(252) = D2A(29)
C HESS(253) = d^2 Vdot(32)/{dV(24)dV(29)} = d^2 Vdot(32)/{dV(29)dV(24)}
      HESS(253) = D2A(28)
C HESS(254) = d^2 Vdot(32)/{dV(24)dV(30)} = d^2 Vdot(32)/{dV(30)dV(24)}
      HESS(254) = D2A(30)
C HESS(255) = d^2 Vdot(32)/{dV(26)dV(32)} = d^2 Vdot(32)/{dV(32)dV(26)}
      HESS(255) = -D2A(32)
C HESS(256) = d^2 Vdot(32)/{dV(28)dV(32)} = d^2 Vdot(32)/{dV(32)dV(28)}
      HESS(256) = -D2A(34)
C HESS(257) = d^2 Vdot(32)/{dV(31)dV(32)} = d^2 Vdot(32)/{dV(32)dV(31)}
      HESS(257) = -D2A(31)
C HESS(258) = d^2 Vdot(32)/{dV(32)dV(32)} = d^2 Vdot(32)/{dV(32)dV(32)}
      HESS(258) = -2*D2A(33)
      RETURN
      END

C End of Hessian function                                          
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C                                                                  
C HessTR_Vec - Hessian transposed times user vectors               
C   Arguments :                                                    
C      HESS      - Hessian of Var (i.e. the 3-tensor d Jac / d Var)
C      U1        - User vector                                     
C      U2        - User vector                                     
C      HTU       - Transposed Hessian times user vectors: (Hess x U2)^T * U1 = [d (Jac^T*U1)/d Var] * U2 
C                                                                  
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      SUBROUTINE HessTR_Vec ( HESS, U1, U2, HTU )

      IMPLICIT NONE
      INCLUDE 'cbm4_ref_Parameters.h'

C HESS - Hessian of Var (i.e. the 3-tensor d Jac / d Var)          
      REAL*8 HESS(NHESS)
C U1 - User vector                                                 
      REAL*8 U1(NVAR)
C U2 - User vector                                                 
      REAL*8 U2(NVAR)
C HTU - Transposed Hessian times user vectors: (Hess x U2)^T * U1 = [d (Jac^T*U1)/d Var] * U2 
      REAL*8 HTU(NVAR)

C Compute the vector HTU =(Hess x U2)^T * U1 = d (Jac^T*U1)/d Var * U2 
      HTU(1) = 0
      HTU(2) = HESS(1)*(U1(2)*U2(27))+HESS(159)*(U1(27)*U2(27))
     &        +HESS(188)*(U1(28)*U2(27))
      HTU(3) = 0
      HTU(4) = HESS(4)*(U1(4)*U2(26))+HESS(138)*(U1(26)*U2(26))
      HTU(5) = HESS(7)*(U1(5)*U2(27))+HESS(22)*(U1(11)*U2(27))
     &        +HESS(32)*(U1(14)*U2(27))+HESS(59)*(U1(18)*U2(27))
     &        +HESS(160)*(U1(27)*U2(27))+HESS(189)*(U1(28)*U2(27))
      HTU(6) = 0
      HTU(7) = HESS(9)*(U1(7)*U2(27))+HESS(23)*(U1(11)*U2(27))
     &        +HESS(33)*(U1(14)*U2(27))+HESS(36)*(U1(15)*U2(27))
     &        +HESS(60)*(U1(18)*U2(27))+HESS(83)*(U1(20)*U2(27))
     &        +HESS(161)*(U1(27)*U2(27))+HESS(190)*(U1(28)*U2(27))
      HTU(8) = HESS(10)*(U1(8)*U2(31))+HESS(234)*(U1(31)*U2(31))
      HTU(9) = HESS(16)*(U1(9)*U2(9))+HESS(17)*(U1(9)*U2(27))
     &        +HESS(139)*(U1(26)*U2(9))+HESS(140)*(U1(26)*U2(27))
     &        +HESS(162)*(U1(27)*U2(27))+HESS(235)*(U1(31)*U2(9))
      HTU(10) = HESS(20)*(U1(10)*U2(27))+HESS(141)*(U1(26)*U2(27))
     &         +HESS(163)*(U1(27)*U2(27))
      HTU(11) = HESS(24)*(U1(11)*U2(31))+HESS(79)*(U1(19)*U2(31))
     &         +HESS(142)*(U1(26)*U2(31))+HESS(191)*(U1(28)*U2(31))
     &         +HESS(236)*(U1(31)*U2(31))
      HTU(12) = HESS(25)*(U1(12)*U2(27))+HESS(164)*(U1(27)*U2(27))
     &         +HESS(224)*(U1(30)*U2(27))
      HTU(13) = HESS(30)*(U1(13)*U2(26))+HESS(143)*(U1(26)*U2(26))
      HTU(14) = HESS(5)*(U1(4)*U2(27))+HESS(6)*(U1(4)*U2(30))+HESS(26)
     &         *(U1(12)*U2(30))+HESS(34)*(U1(14)*U2(27))+HESS(35)
     &         *(U1(14)*U2(30))+HESS(61)*(U1(18)*U2(27))+HESS(80)
     &         *(U1(19)*U2(27))+HESS(165)*(U1(27)*U2(27))+HESS(192)
     &         *(U1(28)*U2(27))+HESS(225)*(U1(30)*U2(30))
      HTU(15) = HESS(37)*(U1(15)*U2(27))+HESS(62)*(U1(18)*U2(27))
     &         +HESS(166)*(U1(27)*U2(27))+HESS(248)*(U1(32)*U2(27))
      HTU(16) = HESS(41)*(U1(16)*U2(27))+HESS(167)*(U1(27)*U2(27))
     &         +HESS(193)*(U1(28)*U2(27))
      HTU(17) = HESS(42)*(U1(16)*U2(25))+HESS(43)*(U1(16)*U2(29))
     &         +HESS(53)*(U1(17)*U2(25))+HESS(54)*(U1(17)*U2(27))
     &         +HESS(55)*(U1(17)*U2(29))+HESS(63)*(U1(18)*U2(27))
     &         +HESS(64)*(U1(18)*U2(29))+HESS(91)*(U1(21)*U2(25))
     &         +HESS(92)*(U1(21)*U2(27))+HESS(93)*(U1(21)*U2(29))
     &         +HESS(117)*(U1(24)*U2(27))+HESS(130)*(U1(25)*U2(25))
     &         +HESS(168)*(U1(27)*U2(27))+HESS(169)*(U1(27)*U2(29))
     &         +HESS(194)*(U1(28)*U2(25))+HESS(195)*(U1(28)*U2(27))
     &         +HESS(196)*(U1(28)*U2(29))+HESS(217)*(U1(29)*U2(29))
      HTU(18) = HESS(65)*(U1(18)*U2(18))+HESS(66)*(U1(18)*U2(31))
     &         +HESS(144)*(U1(26)*U2(31))+HESS(237)*(U1(31)*U2(31))
      HTU(19) = HESS(38)*(U1(15)*U2(25))+HESS(44)*(U1(16)*U2(25))
     &         +HESS(45)*(U1(16)*U2(27))+HESS(67)*(U1(18)*U2(25))
     &         +HESS(68)*(U1(18)*U2(27))+HESS(81)*(U1(19)*U2(25))
     &         +HESS(82)*(U1(19)*U2(27))+HESS(94)*(U1(21)*U2(25))
     &         +HESS(95)*(U1(21)*U2(27))+HESS(118)*(U1(24)*U2(25))
     &         +HESS(131)*(U1(25)*U2(25))+HESS(170)*(U1(27)*U2(25))
     &         +HESS(171)*(U1(27)*U2(27))+HESS(197)*(U1(28)*U2(25))
     &         +HESS(198)*(U1(28)*U2(27))+HESS(249)*(U1(32)*U2(25))
     &         +HESS(250)*(U1(32)*U2(27))
      HTU(20) = HESS(11)*(U1(8)*U2(27))+HESS(31)*(U1(13)*U2(27))
     &         +HESS(69)*(U1(18)*U2(27))+HESS(84)*(U1(20)*U2(27))
     &         +HESS(119)*(U1(24)*U2(27))+HESS(172)*(U1(27)*U2(27))
     &         +HESS(199)*(U1(28)*U2(27))
      HTU(21) = HESS(27)*(U1(12)*U2(30))+HESS(46)*(U1(16)*U2(27))
     &         +HESS(47)*(U1(16)*U2(29))+HESS(48)*(U1(16)*U2(30))
     &         +HESS(96)*(U1(21)*U2(27))+HESS(97)*(U1(21)*U2(29))
     &         +HESS(98)*(U1(21)*U2(30))+HESS(173)*(U1(27)*U2(27))
     &         +HESS(174)*(U1(27)*U2(29))+HESS(200)*(U1(28)*U2(27))
     &         +HESS(201)*(U1(28)*U2(29))+HESS(202)*(U1(28)*U2(30))
     &         +HESS(218)*(U1(29)*U2(29))+HESS(226)*(U1(30)*U2(30))
      HTU(22) = HESS(12)*(U1(8)*U2(27))+HESS(13)*(U1(8)*U2(30))
     &         +HESS(39)*(U1(15)*U2(25))+HESS(40)*(U1(15)*U2(27))
     &         +HESS(49)*(U1(16)*U2(25))+HESS(50)*(U1(16)*U2(29))
     &         +HESS(56)*(U1(17)*U2(25))+HESS(57)*(U1(17)*U2(27))
     &         +HESS(58)*(U1(17)*U2(29))+HESS(70)*(U1(18)*U2(27))
     &         +HESS(71)*(U1(18)*U2(29))+HESS(85)*(U1(20)*U2(25))
     &         +HESS(86)*(U1(20)*U2(29))+HESS(99)*(U1(21)*U2(25))
     &         +HESS(100)*(U1(21)*U2(27))+HESS(108)*(U1(22)*U2(25))
     &         +HESS(109)*(U1(22)*U2(27))+HESS(110)*(U1(22)*U2(29))
     &         +HESS(111)*(U1(22)*U2(30))+HESS(112)*(U1(23)*U2(29))
     &         +HESS(120)*(U1(24)*U2(25))+HESS(121)*(U1(24)*U2(27))
     &         +HESS(122)*(U1(24)*U2(29))+HESS(132)*(U1(25)*U2(25))
     &         +HESS(175)*(U1(27)*U2(25))+HESS(176)*(U1(27)*U2(27))
     &         +HESS(203)*(U1(28)*U2(25))+HESS(204)*(U1(28)*U2(27))
     &         +HESS(205)*(U1(28)*U2(29))+HESS(219)*(U1(29)*U2(29))
     &         +HESS(227)*(U1(30)*U2(30))+HESS(251)*(U1(32)*U2(27))
      HTU(23) = HESS(14)*(U1(8)*U2(29))+HESS(15)*(U1(8)*U2(30))
     &         +HESS(51)*(U1(16)*U2(25))+HESS(52)*(U1(16)*U2(29))
     &         +HESS(72)*(U1(18)*U2(25))+HESS(73)*(U1(18)*U2(27))
     &         +HESS(74)*(U1(18)*U2(29))+HESS(75)*(U1(18)*U2(30))
     &         +HESS(87)*(U1(20)*U2(25))+HESS(88)*(U1(20)*U2(27))
     &         +HESS(89)*(U1(20)*U2(29))+HESS(90)*(U1(20)*U2(30))
     &         +HESS(101)*(U1(21)*U2(25))+HESS(102)*(U1(21)*U2(27))
     &         +HESS(103)*(U1(21)*U2(29))+HESS(104)*(U1(21)*U2(30))
     &         +HESS(113)*(U1(23)*U2(25))+HESS(114)*(U1(23)*U2(27))
     &         +HESS(115)*(U1(23)*U2(29))+HESS(116)*(U1(23)*U2(30))
     &         +HESS(123)*(U1(24)*U2(25))+HESS(124)*(U1(24)*U2(27))
     &         +HESS(125)*(U1(24)*U2(29))+HESS(126)*(U1(24)*U2(30))
     &         +HESS(133)*(U1(25)*U2(25))+HESS(145)*(U1(26)*U2(30))
     &         +HESS(177)*(U1(27)*U2(25))+HESS(178)*(U1(27)*U2(27))
     &         +HESS(179)*(U1(27)*U2(29))+HESS(206)*(U1(28)*U2(25))
     &         +HESS(207)*(U1(28)*U2(27))+HESS(208)*(U1(28)*U2(29))
     &         +HESS(220)*(U1(29)*U2(29))+HESS(228)*(U1(30)*U2(30))
      HTU(24) = HESS(28)*(U1(12)*U2(30))+HESS(127)*(U1(24)*U2(27))
     &         +HESS(128)*(U1(24)*U2(29))+HESS(129)*(U1(24)*U2(30))
     &         +HESS(180)*(U1(27)*U2(27))+HESS(181)*(U1(27)*U2(29))
     &         +HESS(221)*(U1(29)*U2(29))+HESS(229)*(U1(30)*U2(30))
     &         +HESS(252)*(U1(32)*U2(27))+HESS(253)*(U1(32)*U2(29))
     &         +HESS(254)*(U1(32)*U2(30))
      HTU(25) = HESS(38)*(U1(15)*U2(19))+HESS(39)*(U1(15)*U2(22))
     &         +HESS(42)*(U1(16)*U2(17))+HESS(44)*(U1(16)*U2(19))
     &         +HESS(49)*(U1(16)*U2(22))+HESS(51)*(U1(16)*U2(23))
     &         +HESS(53)*(U1(17)*U2(17))+HESS(56)*(U1(17)*U2(22))
     &         +HESS(67)*(U1(18)*U2(19))+HESS(72)*(U1(18)*U2(23))
     &         +HESS(81)*(U1(19)*U2(19))+HESS(85)*(U1(20)*U2(22))
     &         +HESS(87)*(U1(20)*U2(23))+HESS(91)*(U1(21)*U2(17))
     &         +HESS(94)*(U1(21)*U2(19))+HESS(99)*(U1(21)*U2(22))
     &         +HESS(101)*(U1(21)*U2(23))+HESS(108)*(U1(22)*U2(22))
     &         +HESS(113)*(U1(23)*U2(23))+HESS(118)*(U1(24)*U2(19))
     &         +HESS(120)*(U1(24)*U2(22))+HESS(123)*(U1(24)*U2(23))
     &         +HESS(130)*(U1(25)*U2(17))+HESS(131)*(U1(25)*U2(19))
     &         +HESS(132)*(U1(25)*U2(22))+HESS(133)*(U1(25)*U2(23))
     &         +HESS(134)*(U1(25)*U2(26))+HESS(135)*(U1(25)*U2(27))
     &         +HESS(136)*(U1(25)*U2(28))+HESS(137)*(U1(25)*U2(31))
     &         +HESS(146)*(U1(26)*U2(26))+HESS(147)*(U1(26)*U2(31))
     &         +HESS(170)*(U1(27)*U2(19))+HESS(175)*(U1(27)*U2(22))
     &         +HESS(177)*(U1(27)*U2(23))+HESS(182)*(U1(27)*U2(27))
     &         +HESS(183)*(U1(27)*U2(28))+HESS(194)*(U1(28)*U2(17))
     &         +HESS(197)*(U1(28)*U2(19))+HESS(203)*(U1(28)*U2(22))
     &         +HESS(206)*(U1(28)*U2(23))+HESS(209)*(U1(28)*U2(27))
     &         +HESS(210)*(U1(28)*U2(28))+HESS(230)*(U1(30)*U2(26))
     &         +HESS(238)*(U1(31)*U2(31))+HESS(249)*(U1(32)*U2(19))
      HTU(26) = HESS(3)*(U1(3)*U2(32))+HESS(4)*(U1(4)*U2(4))+HESS(8)
     &         *(U1(6)*U2(30))+HESS(18)*(U1(9)*U2(31))+HESS(21)
     &         *(U1(10)*U2(28))+HESS(29)*(U1(12)*U2(27))+HESS(30)
     &         *(U1(13)*U2(13))+HESS(134)*(U1(25)*U2(25))+HESS(138)
     &         *(U1(26)*U2(4))+HESS(143)*(U1(26)*U2(13))+HESS(146)
     &         *(U1(26)*U2(25))+HESS(148)*(U1(26)*U2(27))+HESS(149)
     &         *(U1(26)*U2(28))+HESS(150)*(U1(26)*U2(29))+HESS(151)
     &         *(U1(26)*U2(30))+HESS(152)*(U1(26)*U2(31))+HESS(153)
     &         *(U1(26)*U2(32))+HESS(184)*(U1(27)*U2(27))+HESS(211)
     &         *(U1(28)*U2(28))+HESS(222)*(U1(29)*U2(29))+HESS(230)
     &         *(U1(30)*U2(25))+HESS(231)*(U1(30)*U2(29))+HESS(232)
     &         *(U1(30)*U2(30))+HESS(239)*(U1(31)*U2(29))+HESS(240)
     &         *(U1(31)*U2(30))+HESS(241)*(U1(31)*U2(31))+HESS(255)
     &         *(U1(32)*U2(32))
      HTU(27) = HESS(1)*(U1(2)*U2(2))+HESS(5)*(U1(4)*U2(14))+HESS(7)
     &         *(U1(5)*U2(5))+HESS(9)*(U1(7)*U2(7))+HESS(11)*(U1(8)
     &         *U2(20))+HESS(12)*(U1(8)*U2(22))+HESS(17)*(U1(9)*U2(9))
     &         +HESS(19)*(U1(9)*U2(31))+HESS(20)*(U1(10)*U2(10))
     &         +HESS(22)*(U1(11)*U2(5))+HESS(23)*(U1(11)*U2(7))
     &         +HESS(25)*(U1(12)*U2(12))+HESS(29)*(U1(12)*U2(26))
     &         +HESS(31)*(U1(13)*U2(20))+HESS(32)*(U1(14)*U2(5))
     &         +HESS(33)*(U1(14)*U2(7))+HESS(34)*(U1(14)*U2(14))
     &         +HESS(36)*(U1(15)*U2(7))+HESS(37)*(U1(15)*U2(15))
     &         +HESS(40)*(U1(15)*U2(22))+HESS(41)*(U1(16)*U2(16))
     &         +HESS(45)*(U1(16)*U2(19))+HESS(46)*(U1(16)*U2(21))
     &         +HESS(54)*(U1(17)*U2(17))+HESS(57)*(U1(17)*U2(22))
     &         +HESS(59)*(U1(18)*U2(5))+HESS(60)*(U1(18)*U2(7))
     &         +HESS(61)*(U1(18)*U2(14))+HESS(62)*(U1(18)*U2(15))
     &         +HESS(63)*(U1(18)*U2(17))+HESS(68)*(U1(18)*U2(19))
     &         +HESS(69)*(U1(18)*U2(20))+HESS(70)*(U1(18)*U2(22))
     &         +HESS(73)*(U1(18)*U2(23))+HESS(80)*(U1(19)*U2(14))
     &         +HESS(82)*(U1(19)*U2(19))+HESS(83)*(U1(20)*U2(7))
     &         +HESS(84)*(U1(20)*U2(20))+HESS(88)*(U1(20)*U2(23))
     &         +HESS(92)*(U1(21)*U2(17))+HESS(95)*(U1(21)*U2(19))
     &         +HESS(96)*(U1(21)*U2(21))+HESS(100)*(U1(21)*U2(22))
     &         +HESS(102)*(U1(21)*U2(23))+HESS(109)*(U1(22)*U2(22))
     &         +HESS(114)*(U1(23)*U2(23))+HESS(117)*(U1(24)*U2(17))
     &         +HESS(119)*(U1(24)*U2(20))+HESS(121)*(U1(24)*U2(22))
     &         +HESS(124)*(U1(24)*U2(23))+HESS(127)*(U1(24)*U2(24))
     &         +HESS(135)*(U1(25)*U2(25))+HESS(140)*(U1(26)*U2(9))
     &         +HESS(141)*(U1(26)*U2(10))+HESS(148)*(U1(26)*U2(26))
     &         +HESS(159)*(U1(27)*U2(2))+HESS(160)*(U1(27)*U2(5))
     &         +HESS(161)*(U1(27)*U2(7))+HESS(162)*(U1(27)*U2(9))
     &         +HESS(163)*(U1(27)*U2(10))+HESS(164)*(U1(27)*U2(12))
     &         +HESS(165)*(U1(27)*U2(14))+HESS(166)*(U1(27)*U2(15))
     &         +HESS(167)*(U1(27)*U2(16))+HESS(168)*(U1(27)*U2(17))
     &         +HESS(171)*(U1(27)*U2(19))+HESS(172)*(U1(27)*U2(20))
     &         +HESS(173)*(U1(27)*U2(21))+HESS(176)*(U1(27)*U2(22))
     &         +HESS(178)*(U1(27)*U2(23))+HESS(180)*(U1(27)*U2(24))
     &         +HESS(182)*(U1(27)*U2(25))+HESS(184)*(U1(27)*U2(26))
     &         +HESS(185)*(U1(27)*U2(31))+HESS(188)*(U1(28)*U2(2))
     &         +HESS(189)*(U1(28)*U2(5))+HESS(190)*(U1(28)*U2(7))
     &         +HESS(192)*(U1(28)*U2(14))+HESS(193)*(U1(28)*U2(16))
     &         +HESS(195)*(U1(28)*U2(17))+HESS(198)*(U1(28)*U2(19))
     &         +HESS(199)*(U1(28)*U2(20))+HESS(200)*(U1(28)*U2(21))
     &         +HESS(204)*(U1(28)*U2(22))+HESS(207)*(U1(28)*U2(23))
     &         +HESS(209)*(U1(28)*U2(25))+HESS(224)*(U1(30)*U2(12))
     &         +HESS(242)*(U1(31)*U2(31))+HESS(248)*(U1(32)*U2(15))
     &         +HESS(250)*(U1(32)*U2(19))+HESS(251)*(U1(32)*U2(22))
     &         +HESS(252)*(U1(32)*U2(24))
      HTU(28) = HESS(2)*(U1(2)*U2(28))+HESS(21)*(U1(10)*U2(26))
     &         +HESS(76)*(U1(18)*U2(32))+HESS(105)*(U1(21)*U2(32))
     &         +HESS(136)*(U1(25)*U2(25))+HESS(149)*(U1(26)*U2(26))
     &         +HESS(154)*(U1(26)*U2(31))+HESS(183)*(U1(27)*U2(25))
     &         +HESS(186)*(U1(27)*U2(31))+HESS(187)*(U1(27)*U2(32))
     &         +HESS(210)*(U1(28)*U2(25))+HESS(211)*(U1(28)*U2(26))
     &         +HESS(212)*(U1(28)*U2(28))+HESS(213)*(U1(28)*U2(31))
     &         +HESS(214)*(U1(28)*U2(32))+HESS(243)*(U1(31)*U2(31))
     &         +HESS(256)*(U1(32)*U2(32))
      HTU(29) = HESS(14)*(U1(8)*U2(23))+HESS(43)*(U1(16)*U2(17))
     &         +HESS(47)*(U1(16)*U2(21))+HESS(50)*(U1(16)*U2(22))
     &         +HESS(52)*(U1(16)*U2(23))+HESS(55)*(U1(17)*U2(17))
     &         +HESS(58)*(U1(17)*U2(22))+HESS(64)*(U1(18)*U2(17))
     &         +HESS(71)*(U1(18)*U2(22))+HESS(74)*(U1(18)*U2(23))
     &         +HESS(86)*(U1(20)*U2(22))+HESS(89)*(U1(20)*U2(23))
     &         +HESS(93)*(U1(21)*U2(17))+HESS(97)*(U1(21)*U2(21))
     &         +HESS(103)*(U1(21)*U2(23))+HESS(110)*(U1(22)*U2(22))
     &         +HESS(112)*(U1(23)*U2(22))+HESS(115)*(U1(23)*U2(23))
     &         +HESS(122)*(U1(24)*U2(22))+HESS(125)*(U1(24)*U2(23))
     &         +HESS(128)*(U1(24)*U2(24))+HESS(150)*(U1(26)*U2(26))
     &         +HESS(155)*(U1(26)*U2(31))+HESS(169)*(U1(27)*U2(17))
     &         +HESS(174)*(U1(27)*U2(21))+HESS(179)*(U1(27)*U2(23))
     &         +HESS(181)*(U1(27)*U2(24))+HESS(196)*(U1(28)*U2(17))
     &         +HESS(201)*(U1(28)*U2(21))+HESS(205)*(U1(28)*U2(22))
     &         +HESS(208)*(U1(28)*U2(23))+HESS(217)*(U1(29)*U2(17))
     &         +HESS(218)*(U1(29)*U2(21))+HESS(219)*(U1(29)*U2(22))
     &         +HESS(220)*(U1(29)*U2(23))+HESS(221)*(U1(29)*U2(24))
     &         +HESS(222)*(U1(29)*U2(26))+HESS(223)*(U1(29)*U2(31))
     &         +HESS(231)*(U1(30)*U2(26))+HESS(239)*(U1(31)*U2(26))
     &         +HESS(244)*(U1(31)*U2(31))+HESS(253)*(U1(32)*U2(24))
      HTU(30) = HESS(6)*(U1(4)*U2(14))+HESS(8)*(U1(6)*U2(26))+HESS(13)
     &         *(U1(8)*U2(22))+HESS(15)*(U1(8)*U2(23))+HESS(26)
     &         *(U1(12)*U2(14))+HESS(27)*(U1(12)*U2(21))+HESS(28)
     &         *(U1(12)*U2(24))+HESS(35)*(U1(14)*U2(14))+HESS(48)
     &         *(U1(16)*U2(21))+HESS(75)*(U1(18)*U2(23))+HESS(90)
     &         *(U1(20)*U2(23))+HESS(98)*(U1(21)*U2(21))+HESS(104)
     &         *(U1(21)*U2(23))+HESS(111)*(U1(22)*U2(22))+HESS(116)
     &         *(U1(23)*U2(23))+HESS(126)*(U1(24)*U2(23))+HESS(129)
     &         *(U1(24)*U2(24))+HESS(145)*(U1(26)*U2(23))+HESS(151)
     &         *(U1(26)*U2(26))+HESS(156)*(U1(26)*U2(31))+HESS(202)
     &         *(U1(28)*U2(21))+HESS(225)*(U1(30)*U2(14))+HESS(226)
     &         *(U1(30)*U2(21))+HESS(227)*(U1(30)*U2(22))+HESS(228)
     &         *(U1(30)*U2(23))+HESS(229)*(U1(30)*U2(24))+HESS(232)
     &         *(U1(30)*U2(26))+HESS(233)*(U1(30)*U2(31))+HESS(240)
     &         *(U1(31)*U2(26))+HESS(245)*(U1(31)*U2(31))+HESS(254)
     &         *(U1(32)*U2(24))
      HTU(31) = HESS(10)*(U1(8)*U2(8))+HESS(18)*(U1(9)*U2(26))
     &         +HESS(19)*(U1(9)*U2(27))+HESS(24)*(U1(11)*U2(11))
     &         +HESS(66)*(U1(18)*U2(18))+HESS(77)*(U1(18)*U2(32))
     &         +HESS(79)*(U1(19)*U2(11))+HESS(106)*(U1(21)*U2(32))
     &         +HESS(137)*(U1(25)*U2(25))+HESS(142)*(U1(26)*U2(11))
     &         +HESS(144)*(U1(26)*U2(18))+HESS(147)*(U1(26)*U2(25))
     &         +HESS(152)*(U1(26)*U2(26))+HESS(154)*(U1(26)*U2(28))
     &         +HESS(155)*(U1(26)*U2(29))+HESS(156)*(U1(26)*U2(30))
     &         +HESS(157)*(U1(26)*U2(31))+HESS(158)*(U1(26)*U2(32))
     &         +HESS(185)*(U1(27)*U2(27))+HESS(186)*(U1(27)*U2(28))
     &         +HESS(191)*(U1(28)*U2(11))+HESS(213)*(U1(28)*U2(28))
     &         +HESS(215)*(U1(28)*U2(32))+HESS(223)*(U1(29)*U2(29))
     &         +HESS(233)*(U1(30)*U2(30))+HESS(234)*(U1(31)*U2(8))
     &         +HESS(236)*(U1(31)*U2(11))+HESS(237)*(U1(31)*U2(18))
     &         +HESS(238)*(U1(31)*U2(25))+HESS(241)*(U1(31)*U2(26))
     &         +HESS(242)*(U1(31)*U2(27))+HESS(243)*(U1(31)*U2(28))
     &         +HESS(244)*(U1(31)*U2(29))+HESS(245)*(U1(31)*U2(30))
     &         +HESS(246)*(U1(31)*U2(31))+HESS(247)*(U1(31)*U2(32))
     &         +HESS(257)*(U1(32)*U2(32))
      HTU(32) = HESS(3)*(U1(3)*U2(26))+HESS(76)*(U1(18)*U2(28))
     &         +HESS(77)*(U1(18)*U2(31))+HESS(78)*(U1(18)*U2(32))
     &         +HESS(105)*(U1(21)*U2(28))+HESS(106)*(U1(21)*U2(31))
     &         +HESS(107)*(U1(21)*U2(32))+HESS(153)*(U1(26)*U2(26))
     &         +HESS(158)*(U1(26)*U2(31))+HESS(187)*(U1(27)*U2(28))
     &         +HESS(214)*(U1(28)*U2(28))+HESS(215)*(U1(28)*U2(31))
     &         +HESS(216)*(U1(28)*U2(32))+HESS(247)*(U1(31)*U2(31))
     &         +HESS(255)*(U1(32)*U2(26))+HESS(256)*(U1(32)*U2(28))
     &         +HESS(257)*(U1(32)*U2(31))+HESS(258)*(U1(32)*U2(32))
      RETURN
      END

C End of HessTR_Vec function                                       
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C                                                                  
C Hess_Vec - Hessian times user vectors                            
C   Arguments :                                                    
C      HESS      - Hessian of Var (i.e. the 3-tensor d Jac / d Var)
C      U1        - User vector                                     
C      U2        - User vector                                     
C      HU        - Hessian times user vectors: (Hess x U2) * U1 = [d (Jac*U1)/d Var] * U2
C                                                                  
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      SUBROUTINE Hess_Vec ( HESS, U1, U2, HU )

      IMPLICIT NONE
      INCLUDE 'cbm4_ref_Parameters.h'

C HESS - Hessian of Var (i.e. the 3-tensor d Jac / d Var)          
      REAL*8 HESS(NHESS)
C U1 - User vector                                                 
      REAL*8 U1(NVAR)
C U2 - User vector                                                 
      REAL*8 U2(NVAR)
C HU - Hessian times user vectors: (Hess x U2) * U1 = [d (Jac*U1)/d Var] * U2
      REAL*8 HU(NVAR)

C Compute the vector HU =(Hess x U2) * U1 = d (Jac*U1)/d Var * U2  
      HU(1) = 0
      HU(2) = HESS(1)*(U1(2)*U2(27))+HESS(1)*(U1(27)*U2(2))+HESS(2)
     &       *(U1(28)*U2(28))
      HU(3) = HESS(3)*(U1(26)*U2(32))+HESS(3)*(U1(32)*U2(26))
      HU(4) = HESS(4)*(U1(4)*U2(26))+HESS(4)*(U1(26)*U2(4))+HESS(5)
     &       *(U1(14)*U2(27))+HESS(5)*(U1(27)*U2(14))+HESS(6)*(U1(14)
     &       *U2(30))+HESS(6)*(U1(30)*U2(14))
      HU(5) = HESS(7)*(U1(5)*U2(27))+HESS(7)*(U1(27)*U2(5))
      HU(6) = HESS(8)*(U1(26)*U2(30))+HESS(8)*(U1(30)*U2(26))
      HU(7) = HESS(9)*(U1(7)*U2(27))+HESS(9)*(U1(27)*U2(7))
      HU(8) = HESS(10)*(U1(8)*U2(31))+HESS(10)*(U1(31)*U2(8))+HESS(11)
     &       *(U1(20)*U2(27))+HESS(11)*(U1(27)*U2(20))+HESS(12)
     &       *(U1(22)*U2(27))+HESS(12)*(U1(27)*U2(22))+HESS(13)
     &       *(U1(22)*U2(30))+HESS(13)*(U1(30)*U2(22))+HESS(14)
     &       *(U1(23)*U2(29))+HESS(14)*(U1(29)*U2(23))+HESS(15)
     &       *(U1(23)*U2(30))+HESS(15)*(U1(30)*U2(23))
      HU(9) = HESS(16)*(U1(9)*U2(9))+HESS(17)*(U1(9)*U2(27))+HESS(17)
     &       *(U1(27)*U2(9))+HESS(18)*(U1(26)*U2(31))+HESS(18)*(U1(31)
     &       *U2(26))+HESS(19)*(U1(27)*U2(31))+HESS(19)*(U1(31)
     &       *U2(27))
      HU(10) = HESS(20)*(U1(10)*U2(27))+HESS(20)*(U1(27)*U2(10))
     &        +HESS(21)*(U1(26)*U2(28))+HESS(21)*(U1(28)*U2(26))
      HU(11) = HESS(22)*(U1(5)*U2(27))+HESS(22)*(U1(27)*U2(5))
     &        +HESS(23)*(U1(7)*U2(27))+HESS(23)*(U1(27)*U2(7))
     &        +HESS(24)*(U1(11)*U2(31))+HESS(24)*(U1(31)*U2(11))
      HU(12) = HESS(25)*(U1(12)*U2(27))+HESS(25)*(U1(27)*U2(12))
     &        +HESS(26)*(U1(14)*U2(30))+HESS(26)*(U1(30)*U2(14))
     &        +HESS(27)*(U1(21)*U2(30))+HESS(27)*(U1(30)*U2(21))
     &        +HESS(28)*(U1(24)*U2(30))+HESS(28)*(U1(30)*U2(24))
     &        +HESS(29)*(U1(26)*U2(27))+HESS(29)*(U1(27)*U2(26))
      HU(13) = HESS(30)*(U1(13)*U2(26))+HESS(30)*(U1(26)*U2(13))
     &        +HESS(31)*(U1(20)*U2(27))+HESS(31)*(U1(27)*U2(20))
      HU(14) = HESS(32)*(U1(5)*U2(27))+HESS(32)*(U1(27)*U2(5))
     &        +HESS(33)*(U1(7)*U2(27))+HESS(33)*(U1(27)*U2(7))
     &        +HESS(34)*(U1(14)*U2(27))+HESS(34)*(U1(27)*U2(14))
     &        +HESS(35)*(U1(14)*U2(30))+HESS(35)*(U1(30)*U2(14))
      HU(15) = HESS(36)*(U1(7)*U2(27))+HESS(36)*(U1(27)*U2(7))
     &        +HESS(37)*(U1(15)*U2(27))+HESS(37)*(U1(27)*U2(15))
     &        +HESS(38)*(U1(19)*U2(25))+HESS(38)*(U1(25)*U2(19))
     &        +HESS(39)*(U1(22)*U2(25))+HESS(39)*(U1(25)*U2(22))
     &        +HESS(40)*(U1(22)*U2(27))+HESS(40)*(U1(27)*U2(22))
      HU(16) = HESS(41)*(U1(16)*U2(27))+HESS(41)*(U1(27)*U2(16))
     &        +HESS(42)*(U1(17)*U2(25))+HESS(42)*(U1(25)*U2(17))
     &        +HESS(43)*(U1(17)*U2(29))+HESS(43)*(U1(29)*U2(17))
     &        +HESS(44)*(U1(19)*U2(25))+HESS(44)*(U1(25)*U2(19))
     &        +HESS(45)*(U1(19)*U2(27))+HESS(45)*(U1(27)*U2(19))
     &        +HESS(46)*(U1(21)*U2(27))+HESS(46)*(U1(27)*U2(21))
     &        +HESS(47)*(U1(21)*U2(29))+HESS(47)*(U1(29)*U2(21))
     &        +HESS(48)*(U1(21)*U2(30))+HESS(48)*(U1(30)*U2(21))
     &        +HESS(49)*(U1(22)*U2(25))+HESS(49)*(U1(25)*U2(22))
     &        +HESS(50)*(U1(22)*U2(29))+HESS(50)*(U1(29)*U2(22))
     &        +HESS(51)*(U1(23)*U2(25))+HESS(51)*(U1(25)*U2(23))
     &        +HESS(52)*(U1(23)*U2(29))+HESS(52)*(U1(29)*U2(23))
      HU(17) = HESS(53)*(U1(17)*U2(25))+HESS(53)*(U1(25)*U2(17))
     &        +HESS(54)*(U1(17)*U2(27))+HESS(54)*(U1(27)*U2(17))
     &        +HESS(55)*(U1(17)*U2(29))+HESS(55)*(U1(29)*U2(17))
     &        +HESS(56)*(U1(22)*U2(25))+HESS(56)*(U1(25)*U2(22))
     &        +HESS(57)*(U1(22)*U2(27))+HESS(57)*(U1(27)*U2(22))
     &        +HESS(58)*(U1(22)*U2(29))+HESS(58)*(U1(29)*U2(22))
      HU(18) = HESS(59)*(U1(5)*U2(27))+HESS(59)*(U1(27)*U2(5))
     &        +HESS(60)*(U1(7)*U2(27))+HESS(60)*(U1(27)*U2(7))
     &        +HESS(61)*(U1(14)*U2(27))+HESS(61)*(U1(27)*U2(14))
     &        +HESS(62)*(U1(15)*U2(27))+HESS(62)*(U1(27)*U2(15))
     &        +HESS(63)*(U1(17)*U2(27))+HESS(63)*(U1(27)*U2(17))
     &        +HESS(64)*(U1(17)*U2(29))+HESS(64)*(U1(29)*U2(17))
     &        +HESS(65)*(U1(18)*U2(18))+HESS(66)*(U1(18)*U2(31))
     &        +HESS(66)*(U1(31)*U2(18))+HESS(67)*(U1(19)*U2(25))
     &        +HESS(67)*(U1(25)*U2(19))+HESS(68)*(U1(19)*U2(27))
     &        +HESS(68)*(U1(27)*U2(19))+HESS(69)*(U1(20)*U2(27))
     &        +HESS(69)*(U1(27)*U2(20))+HESS(70)*(U1(22)*U2(27))
     &        +HESS(70)*(U1(27)*U2(22))+HESS(71)*(U1(22)*U2(29))
     &        +HESS(71)*(U1(29)*U2(22))+HESS(72)*(U1(23)*U2(25))
     &        +HESS(72)*(U1(25)*U2(23))+HESS(73)*(U1(23)*U2(27))
     &        +HESS(73)*(U1(27)*U2(23))+HESS(74)*(U1(23)*U2(29))
     &        +HESS(74)*(U1(29)*U2(23))+HESS(75)*(U1(23)*U2(30))
     &        +HESS(75)*(U1(30)*U2(23))+HESS(76)*(U1(28)*U2(32))
     &        +HESS(76)*(U1(32)*U2(28))+HESS(77)*(U1(31)*U2(32))
     &        +HESS(77)*(U1(32)*U2(31))+HESS(78)*(U1(32)*U2(32))
      HU(19) = HESS(79)*(U1(11)*U2(31))+HESS(79)*(U1(31)*U2(11))
     &        +HESS(80)*(U1(14)*U2(27))+HESS(80)*(U1(27)*U2(14))
     &        +HESS(81)*(U1(19)*U2(25))+HESS(81)*(U1(25)*U2(19))
     &        +HESS(82)*(U1(19)*U2(27))+HESS(82)*(U1(27)*U2(19))
      HU(20) = HESS(83)*(U1(7)*U2(27))+HESS(83)*(U1(27)*U2(7))
     &        +HESS(84)*(U1(20)*U2(27))+HESS(84)*(U1(27)*U2(20))
     &        +HESS(85)*(U1(22)*U2(25))+HESS(85)*(U1(25)*U2(22))
     &        +HESS(86)*(U1(22)*U2(29))+HESS(86)*(U1(29)*U2(22))
     &        +HESS(87)*(U1(23)*U2(25))+HESS(87)*(U1(25)*U2(23))
     &        +HESS(88)*(U1(23)*U2(27))+HESS(88)*(U1(27)*U2(23))
     &        +HESS(89)*(U1(23)*U2(29))+HESS(89)*(U1(29)*U2(23))
     &        +HESS(90)*(U1(23)*U2(30))+HESS(90)*(U1(30)*U2(23))
      HU(21) = HESS(91)*(U1(17)*U2(25))+HESS(91)*(U1(25)*U2(17))
     &        +HESS(92)*(U1(17)*U2(27))+HESS(92)*(U1(27)*U2(17))
     &        +HESS(93)*(U1(17)*U2(29))+HESS(93)*(U1(29)*U2(17))
     &        +HESS(94)*(U1(19)*U2(25))+HESS(94)*(U1(25)*U2(19))
     &        +HESS(95)*(U1(19)*U2(27))+HESS(95)*(U1(27)*U2(19))
     &        +HESS(96)*(U1(21)*U2(27))+HESS(96)*(U1(27)*U2(21))
     &        +HESS(97)*(U1(21)*U2(29))+HESS(97)*(U1(29)*U2(21))
     &        +HESS(98)*(U1(21)*U2(30))+HESS(98)*(U1(30)*U2(21))
     &        +HESS(99)*(U1(22)*U2(25))+HESS(99)*(U1(25)*U2(22))
     &        +HESS(100)*(U1(22)*U2(27))+HESS(100)*(U1(27)*U2(22))
     &        +HESS(101)*(U1(23)*U2(25))+HESS(101)*(U1(25)*U2(23))
     &        +HESS(102)*(U1(23)*U2(27))+HESS(102)*(U1(27)*U2(23))
     &        +HESS(103)*(U1(23)*U2(29))+HESS(103)*(U1(29)*U2(23))
     &        +HESS(104)*(U1(23)*U2(30))+HESS(104)*(U1(30)*U2(23))
     &        +HESS(105)*(U1(28)*U2(32))+HESS(105)*(U1(32)*U2(28))
     &        +HESS(106)*(U1(31)*U2(32))+HESS(106)*(U1(32)*U2(31))
     &        +HESS(107)*(U1(32)*U2(32))
      HU(22) = HESS(108)*(U1(22)*U2(25))+HESS(108)*(U1(25)*U2(22))
     &        +HESS(109)*(U1(22)*U2(27))+HESS(109)*(U1(27)*U2(22))
     &        +HESS(110)*(U1(22)*U2(29))+HESS(110)*(U1(29)*U2(22))
     &        +HESS(111)*(U1(22)*U2(30))+HESS(111)*(U1(30)*U2(22))
      HU(23) = HESS(112)*(U1(22)*U2(29))+HESS(112)*(U1(29)*U2(22))
     &        +HESS(113)*(U1(23)*U2(25))+HESS(113)*(U1(25)*U2(23))
     &        +HESS(114)*(U1(23)*U2(27))+HESS(114)*(U1(27)*U2(23))
     &        +HESS(115)*(U1(23)*U2(29))+HESS(115)*(U1(29)*U2(23))
     &        +HESS(116)*(U1(23)*U2(30))+HESS(116)*(U1(30)*U2(23))
      HU(24) = HESS(117)*(U1(17)*U2(27))+HESS(117)*(U1(27)*U2(17))
     &        +HESS(118)*(U1(19)*U2(25))+HESS(118)*(U1(25)*U2(19))
     &        +HESS(119)*(U1(20)*U2(27))+HESS(119)*(U1(27)*U2(20))
     &        +HESS(120)*(U1(22)*U2(25))+HESS(120)*(U1(25)*U2(22))
     &        +HESS(121)*(U1(22)*U2(27))+HESS(121)*(U1(27)*U2(22))
     &        +HESS(122)*(U1(22)*U2(29))+HESS(122)*(U1(29)*U2(22))
     &        +HESS(123)*(U1(23)*U2(25))+HESS(123)*(U1(25)*U2(23))
     &        +HESS(124)*(U1(23)*U2(27))+HESS(124)*(U1(27)*U2(23))
     &        +HESS(125)*(U1(23)*U2(29))+HESS(125)*(U1(29)*U2(23))
     &        +HESS(126)*(U1(23)*U2(30))+HESS(126)*(U1(30)*U2(23))
     &        +HESS(127)*(U1(24)*U2(27))+HESS(127)*(U1(27)*U2(24))
     &        +HESS(128)*(U1(24)*U2(29))+HESS(128)*(U1(29)*U2(24))
     &        +HESS(129)*(U1(24)*U2(30))+HESS(129)*(U1(30)*U2(24))
      HU(25) = HESS(130)*(U1(17)*U2(25))+HESS(130)*(U1(25)*U2(17))
     &        +HESS(131)*(U1(19)*U2(25))+HESS(131)*(U1(25)*U2(19))
     &        +HESS(132)*(U1(22)*U2(25))+HESS(132)*(U1(25)*U2(22))
     &        +HESS(133)*(U1(23)*U2(25))+HESS(133)*(U1(25)*U2(23))
     &        +HESS(134)*(U1(25)*U2(26))+HESS(134)*(U1(26)*U2(25))
     &        +HESS(135)*(U1(25)*U2(27))+HESS(135)*(U1(27)*U2(25))
     &        +HESS(136)*(U1(25)*U2(28))+HESS(136)*(U1(28)*U2(25))
     &        +HESS(137)*(U1(25)*U2(31))+HESS(137)*(U1(31)*U2(25))
      HU(26) = HESS(138)*(U1(4)*U2(26))+HESS(138)*(U1(26)*U2(4))
     &        +HESS(139)*(U1(9)*U2(9))+HESS(140)*(U1(9)*U2(27))
     &        +HESS(140)*(U1(27)*U2(9))+HESS(141)*(U1(10)*U2(27))
     &        +HESS(141)*(U1(27)*U2(10))+HESS(142)*(U1(11)*U2(31))
     &        +HESS(142)*(U1(31)*U2(11))+HESS(143)*(U1(13)*U2(26))
     &        +HESS(143)*(U1(26)*U2(13))+HESS(144)*(U1(18)*U2(31))
     &        +HESS(144)*(U1(31)*U2(18))+HESS(145)*(U1(23)*U2(30))
     &        +HESS(145)*(U1(30)*U2(23))+HESS(146)*(U1(25)*U2(26))
     &        +HESS(146)*(U1(26)*U2(25))+HESS(147)*(U1(25)*U2(31))
     &        +HESS(147)*(U1(31)*U2(25))+HESS(148)*(U1(26)*U2(27))
     &        +HESS(148)*(U1(27)*U2(26))+HESS(149)*(U1(26)*U2(28))
     &        +HESS(149)*(U1(28)*U2(26))+HESS(150)*(U1(26)*U2(29))
     &        +HESS(150)*(U1(29)*U2(26))+HESS(151)*(U1(26)*U2(30))
     &        +HESS(151)*(U1(30)*U2(26))+HESS(152)*(U1(26)*U2(31))
     &        +HESS(152)*(U1(31)*U2(26))+HESS(153)*(U1(26)*U2(32))
     &        +HESS(153)*(U1(32)*U2(26))+HESS(154)*(U1(28)*U2(31))
     &        +HESS(154)*(U1(31)*U2(28))+HESS(155)*(U1(29)*U2(31))
     &        +HESS(155)*(U1(31)*U2(29))+HESS(156)*(U1(30)*U2(31))
     &        +HESS(156)*(U1(31)*U2(30))+HESS(157)*(U1(31)*U2(31))
     &        +HESS(158)*(U1(31)*U2(32))+HESS(158)*(U1(32)*U2(31))
      HU(27) = HESS(159)*(U1(2)*U2(27))+HESS(159)*(U1(27)*U2(2))
     &        +HESS(160)*(U1(5)*U2(27))+HESS(160)*(U1(27)*U2(5))
     &        +HESS(161)*(U1(7)*U2(27))+HESS(161)*(U1(27)*U2(7))
     &        +HESS(162)*(U1(9)*U2(27))+HESS(162)*(U1(27)*U2(9))
     &        +HESS(163)*(U1(10)*U2(27))+HESS(163)*(U1(27)*U2(10))
     &        +HESS(164)*(U1(12)*U2(27))+HESS(164)*(U1(27)*U2(12))
     &        +HESS(165)*(U1(14)*U2(27))+HESS(165)*(U1(27)*U2(14))
     &        +HESS(166)*(U1(15)*U2(27))+HESS(166)*(U1(27)*U2(15))
     &        +HESS(167)*(U1(16)*U2(27))+HESS(167)*(U1(27)*U2(16))
     &        +HESS(168)*(U1(17)*U2(27))+HESS(168)*(U1(27)*U2(17))
     &        +HESS(169)*(U1(17)*U2(29))+HESS(169)*(U1(29)*U2(17))
     &        +HESS(170)*(U1(19)*U2(25))+HESS(170)*(U1(25)*U2(19))
     &        +HESS(171)*(U1(19)*U2(27))+HESS(171)*(U1(27)*U2(19))
     &        +HESS(172)*(U1(20)*U2(27))+HESS(172)*(U1(27)*U2(20))
     &        +HESS(173)*(U1(21)*U2(27))+HESS(173)*(U1(27)*U2(21))
     &        +HESS(174)*(U1(21)*U2(29))+HESS(174)*(U1(29)*U2(21))
     &        +HESS(175)*(U1(22)*U2(25))+HESS(175)*(U1(25)*U2(22))
     &        +HESS(176)*(U1(22)*U2(27))+HESS(176)*(U1(27)*U2(22))
     &        +HESS(177)*(U1(23)*U2(25))+HESS(177)*(U1(25)*U2(23))
     &        +HESS(178)*(U1(23)*U2(27))+HESS(178)*(U1(27)*U2(23))
     &        +HESS(179)*(U1(23)*U2(29))+HESS(179)*(U1(29)*U2(23))
     &        +HESS(180)*(U1(24)*U2(27))+HESS(180)*(U1(27)*U2(24))
     &        +HESS(181)*(U1(24)*U2(29))+HESS(181)*(U1(29)*U2(24))
     &        +HESS(182)*(U1(25)*U2(27))+HESS(182)*(U1(27)*U2(25))
     &        +HESS(183)*(U1(25)*U2(28))+HESS(183)*(U1(28)*U2(25))
     &        +HESS(184)*(U1(26)*U2(27))+HESS(184)*(U1(27)*U2(26))
     &        +HESS(185)*(U1(27)*U2(31))+HESS(185)*(U1(31)*U2(27))
     &        +HESS(186)*(U1(28)*U2(31))+HESS(186)*(U1(31)*U2(28))
     &        +HESS(187)*(U1(28)*U2(32))+HESS(187)*(U1(32)*U2(28))
      HU(28) = HESS(188)*(U1(2)*U2(27))+HESS(188)*(U1(27)*U2(2))
     &        +HESS(189)*(U1(5)*U2(27))+HESS(189)*(U1(27)*U2(5))
     &        +HESS(190)*(U1(7)*U2(27))+HESS(190)*(U1(27)*U2(7))
     &        +HESS(191)*(U1(11)*U2(31))+HESS(191)*(U1(31)*U2(11))
     &        +HESS(192)*(U1(14)*U2(27))+HESS(192)*(U1(27)*U2(14))
     &        +HESS(193)*(U1(16)*U2(27))+HESS(193)*(U1(27)*U2(16))
     &        +HESS(194)*(U1(17)*U2(25))+HESS(194)*(U1(25)*U2(17))
     &        +HESS(195)*(U1(17)*U2(27))+HESS(195)*(U1(27)*U2(17))
     &        +HESS(196)*(U1(17)*U2(29))+HESS(196)*(U1(29)*U2(17))
     &        +HESS(197)*(U1(19)*U2(25))+HESS(197)*(U1(25)*U2(19))
     &        +HESS(198)*(U1(19)*U2(27))+HESS(198)*(U1(27)*U2(19))
     &        +HESS(199)*(U1(20)*U2(27))+HESS(199)*(U1(27)*U2(20))
     &        +HESS(200)*(U1(21)*U2(27))+HESS(200)*(U1(27)*U2(21))
     &        +HESS(201)*(U1(21)*U2(29))+HESS(201)*(U1(29)*U2(21))
     &        +HESS(202)*(U1(21)*U2(30))+HESS(202)*(U1(30)*U2(21))
     &        +HESS(203)*(U1(22)*U2(25))+HESS(203)*(U1(25)*U2(22))
     &        +HESS(204)*(U1(22)*U2(27))+HESS(204)*(U1(27)*U2(22))
     &        +HESS(205)*(U1(22)*U2(29))+HESS(205)*(U1(29)*U2(22))
     &        +HESS(206)*(U1(23)*U2(25))+HESS(206)*(U1(25)*U2(23))
     &        +HESS(207)*(U1(23)*U2(27))+HESS(207)*(U1(27)*U2(23))
     &        +HESS(208)*(U1(23)*U2(29))+HESS(208)*(U1(29)*U2(23))
     &        +HESS(209)*(U1(25)*U2(27))+HESS(209)*(U1(27)*U2(25))
     &        +HESS(210)*(U1(25)*U2(28))+HESS(210)*(U1(28)*U2(25))
     &        +HESS(211)*(U1(26)*U2(28))+HESS(211)*(U1(28)*U2(26))
     &        +HESS(212)*(U1(28)*U2(28))+HESS(213)*(U1(28)*U2(31))
     &        +HESS(213)*(U1(31)*U2(28))+HESS(214)*(U1(28)*U2(32))
     &        +HESS(214)*(U1(32)*U2(28))+HESS(215)*(U1(31)*U2(32))
     &        +HESS(215)*(U1(32)*U2(31))+HESS(216)*(U1(32)*U2(32))
      HU(29) = HESS(217)*(U1(17)*U2(29))+HESS(217)*(U1(29)*U2(17))
     &        +HESS(218)*(U1(21)*U2(29))+HESS(218)*(U1(29)*U2(21))
     &        +HESS(219)*(U1(22)*U2(29))+HESS(219)*(U1(29)*U2(22))
     &        +HESS(220)*(U1(23)*U2(29))+HESS(220)*(U1(29)*U2(23))
     &        +HESS(221)*(U1(24)*U2(29))+HESS(221)*(U1(29)*U2(24))
     &        +HESS(222)*(U1(26)*U2(29))+HESS(222)*(U1(29)*U2(26))
     &        +HESS(223)*(U1(29)*U2(31))+HESS(223)*(U1(31)*U2(29))
      HU(30) = HESS(224)*(U1(12)*U2(27))+HESS(224)*(U1(27)*U2(12))
     &        +HESS(225)*(U1(14)*U2(30))+HESS(225)*(U1(30)*U2(14))
     &        +HESS(226)*(U1(21)*U2(30))+HESS(226)*(U1(30)*U2(21))
     &        +HESS(227)*(U1(22)*U2(30))+HESS(227)*(U1(30)*U2(22))
     &        +HESS(228)*(U1(23)*U2(30))+HESS(228)*(U1(30)*U2(23))
     &        +HESS(229)*(U1(24)*U2(30))+HESS(229)*(U1(30)*U2(24))
     &        +HESS(230)*(U1(25)*U2(26))+HESS(230)*(U1(26)*U2(25))
     &        +HESS(231)*(U1(26)*U2(29))+HESS(231)*(U1(29)*U2(26))
     &        +HESS(232)*(U1(26)*U2(30))+HESS(232)*(U1(30)*U2(26))
     &        +HESS(233)*(U1(30)*U2(31))+HESS(233)*(U1(31)*U2(30))
      HU(31) = HESS(234)*(U1(8)*U2(31))+HESS(234)*(U1(31)*U2(8))
     &        +HESS(235)*(U1(9)*U2(9))+HESS(236)*(U1(11)*U2(31))
     &        +HESS(236)*(U1(31)*U2(11))+HESS(237)*(U1(18)*U2(31))
     &        +HESS(237)*(U1(31)*U2(18))+HESS(238)*(U1(25)*U2(31))
     &        +HESS(238)*(U1(31)*U2(25))+HESS(239)*(U1(26)*U2(29))
     &        +HESS(239)*(U1(29)*U2(26))+HESS(240)*(U1(26)*U2(30))
     &        +HESS(240)*(U1(30)*U2(26))+HESS(241)*(U1(26)*U2(31))
     &        +HESS(241)*(U1(31)*U2(26))+HESS(242)*(U1(27)*U2(31))
     &        +HESS(242)*(U1(31)*U2(27))+HESS(243)*(U1(28)*U2(31))
     &        +HESS(243)*(U1(31)*U2(28))+HESS(244)*(U1(29)*U2(31))
     &        +HESS(244)*(U1(31)*U2(29))+HESS(245)*(U1(30)*U2(31))
     &        +HESS(245)*(U1(31)*U2(30))+HESS(246)*(U1(31)*U2(31))
     &        +HESS(247)*(U1(31)*U2(32))+HESS(247)*(U1(32)*U2(31))
      HU(32) = HESS(248)*(U1(15)*U2(27))+HESS(248)*(U1(27)*U2(15))
     &        +HESS(249)*(U1(19)*U2(25))+HESS(249)*(U1(25)*U2(19))
     &        +HESS(250)*(U1(19)*U2(27))+HESS(250)*(U1(27)*U2(19))
     &        +HESS(251)*(U1(22)*U2(27))+HESS(251)*(U1(27)*U2(22))
     &        +HESS(252)*(U1(24)*U2(27))+HESS(252)*(U1(27)*U2(24))
     &        +HESS(253)*(U1(24)*U2(29))+HESS(253)*(U1(29)*U2(24))
     &        +HESS(254)*(U1(24)*U2(30))+HESS(254)*(U1(30)*U2(24))
     &        +HESS(255)*(U1(26)*U2(32))+HESS(255)*(U1(32)*U2(26))
     &        +HESS(256)*(U1(28)*U2(32))+HESS(256)*(U1(32)*U2(28))
     &        +HESS(257)*(U1(31)*U2(32))+HESS(257)*(U1(32)*U2(31))
     &        +HESS(258)*(U1(32)*U2(32))
      RETURN
      END

C End of Hess_Vec function                                         
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


