C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C                                                                  
C The Reaction Rates File                                          
C                                                                  
C Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  
C       (http://www.cs.vt.edu/~asandu/Software/KPP)                
C KPP is distributed under GPL, the general public licence         
C       (http://www.gnu.org/copyleft/gpl.html)                     
C (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           
C (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            
C     With important contributions from:                           
C        M. Damian, Villanova University, USA                      
C        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
C                                                                  
C File                 : cbm4_ref_Rates.f                          
C Time                 : Fri Sep  2 14:39:53 2022                  
C Working directory    : /home/kyriacos/CyprusInstitute/KPP/cbm4_ref
C Equation file        : cbm4_ref.kpp                              
C Output root filename : cbm4_ref                                  
C                                                                  
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




C Begin Rate Law Functions from KPP_HOME/util/UserRateLaws         

C  User-defined Rate Law functions
C  Note: the default argument type for rate laws, as read from the equations file, is single precision
C        but all the internal calculations are performed in REAL*8

C Arrhenius
      REAL*8 FUNCTION ARR( A0,B0,C0 )
      INCLUDE 'cbm4_ref_Parameters.h'
      INCLUDE 'cbm4_ref_Global.h'
                 
      REAL A0,B0,C0      
      ARR =  DBLE(A0) * EXP(-DBLE(B0)/TEMP) * (TEMP/300.0D0)**DBLE(C0)   
           
      RETURN
      END           


C Simplified Arrhenius, with two arguments
C Note: The argument B0 has a changed sign when compared to ARR
      REAL*8 FUNCTION ARR2( A0,B0 )
      INCLUDE 'cbm4_ref_Parameters.h'
      INCLUDE 'cbm4_ref_Global.h'
                 
      REAL A0,B0     
      ARR2 =  DBLE(A0) * EXP( DBLE(B0)/TEMP )   
           
      RETURN
      END           

      REAL*8 FUNCTION EP2(A0,C0,A2,C2,A3,C3)
      INCLUDE 'cbm4_ref_Parameters.h'                       
      INCLUDE 'cbm4_ref_Global.h'
      
      REAL A0,C0,A2,C2,A3,C3
      REAL*8 K0,K2,K3
      
      K0 = DBLE(A0) * EXP(-DBLE(C0)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      K3 = DBLE(A3) * EXP(-DBLE(C3)/TEMP)
      K3 = K3*CFACTOR*1.0d6
      EP2 = K0 + K3/(1.0d0+K3/K2 )
        
      RETURN
      END  


      REAL*8 FUNCTION EP3(A1,C1,A2,C2) 
      INCLUDE 'cbm4_ref_Parameters.h'               
      INCLUDE 'cbm4_ref_Global.h'
      
      REAL A1, C1, A2, C2
      REAL*8 K1, K2
      
      K1 = DBLE(A1) * EXP(-DBLE(C1)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      EP3 = K1 + K2*(1.0d6*CFACTOR)
      
      RETURN
      END    


      REAL*8 FUNCTION FALL ( A0,B0,C0,A1,B1,C1,CF)
      INCLUDE 'cbm4_ref_Parameters.h'                      
      INCLUDE 'cbm4_ref_Global.h'
      
      REAL A0,B0,C0,A1,B1,C1,CF
      REAL*8 K0, K1
      
      K0 = DBLE(A0) * EXP(-DBLE(B0)/TEMP)* (TEMP/300.0D0)**DBLE(C0)
      K1 = DBLE(A1) * EXP(-DBLE(B1)/TEMP)* (TEMP/300.0D0)**DBLE(C1)
      K0 = K0*CFACTOR*1.0D6
      K1 = K0/K1
      FALL = (K0/(1.0d0+K1))*
     *      DBLE(CF)**(1.0d0/(1.0d0+(DLOG10(K1))**2))
        
      RETURN
      END

C End Rate Law Functions from KPP_HOME/util/UserRateLaws           


C Begin INLINED Rate Law Functions                                 


C End INLINED Rate Law Functions                                   

C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C                                                                  
C Update_SUN - update SUN light using TIME                         
C   Arguments :                                                    
C                                                                  
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      SUBROUTINE Update_SUN()

      IMPLICIT NONE
      INCLUDE 'cbm4_ref_Parameters.h'
      INCLUDE 'cbm4_ref_Global.h'

      REAL*8 SunRise, SunSet
      REAL*8 Thour, Tlocal, Ttmp, PI
      PARAMETER (PI = 3.14159265358979d0) 
   
      SunRise = 4.5
      SunSet  = 19.5
      Thour = TIME/3600.
      Tlocal = Thour - (INT(Thour)/24)*24

      IF ((Tlocal.GE.SunRise).AND.(Tlocal.LE.SunSet)) THEN
        Ttmp = (2.0*Tlocal-SunRise-SunSet)/(SunSet-SunRise)
        IF (Ttmp.GT.0) THEN
          Ttmp =  Ttmp*Ttmp
        ELSE
          Ttmp = -Ttmp*Ttmp
        END IF
        SUN = ( 1.0 + COS(PI*Ttmp) )/2.0 
      ELSE
        SUN = 0.0
      END IF

      RETURN
      END

C End of Update_SUN function                                       
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C                                                                  
C Update_RCONST - function to update rate constants                
C   Arguments :                                                    
C                                                                  
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      SUBROUTINE Update_RCONST ( )

      IMPLICIT NONE
      INCLUDE 'cbm4_ref_Parameters.h'


      INCLUDE 'cbm4_ref_Global.h'
C  Definitions for User-defined Rate Law functions
C  To be inserted in funcions that call rate laws

      REAL*8 ARR, ARR2
      REAL*8 EP2, EP3, FALL
      EXTERNAL ARR, ARR2, EP2, EP3, FALL


C Begin INLINED RCONST                                             


C End INLINED RCONST                                               

      RCONST(1) = (8.89E-3*SUN)
      RCONST(2) = (ARR2(1.4E+3,1175.0))
      RCONST(3) = (ARR2(1.8E-12,-1370.0))
      RCONST(5) = (ARR2(1.6E-13,687.0))
      RCONST(6) = (ARR2(2.2E-13,602.0))
      RCONST(7) = (ARR2(1.2E-13,-2450.0))
      RCONST(8) = (3.556E-04*SUN)
      RCONST(9) = (2.489E-05*SUN)
      RCONST(10) = (ARR2(1.9E+8,390.0))
      RCONST(12) = (ARR2(1.6E-12,-940.0))
      RCONST(13) = (ARR2(1.4E-14,-580.0))
      RCONST(14) = (1.378E-01*SUN)
      RCONST(15) = (ARR2(1.3E-11,250.0))
      RCONST(16) = (ARR2(2.5E-14,-1230.0))
      RCONST(17) = (ARR2(5.3E-13,256.0))
      RCONST(19) = (ARR2(3.5E+14,-10897.0))
      RCONST(20) = (ARR2(1.8E-20,530.0))
      RCONST(22) = (ARR2(4.5E-13,806.0))
      RCONST(23) = (1.511e-03*SUN)
      RCONST(26) = (ARR2(1.0E-12,713.0))
      RCONST(27) = (ARR2(5.1E-15,1000.0))
      RCONST(28) = (ARR2(3.7E-12,240.0))
      RCONST(29) = (ARR2(1.2E-13,749.0))
      RCONST(30) = (ARR2(4.8E+13,-10121.0))
      RCONST(31) = (ARR2(1.3E-12,380.0))
      RCONST(32) = (ARR2(5.9E-14,1150.0))
      RCONST(33) = (ARR2(2.2E-38,5800.0))
      RCONST(34) = (6.312E-06*SUN)
      RCONST(35) = (ARR2(3.1E-12,-187.0))
      RCONST(38) = (2.845E-05*SUN)
      RCONST(39) = (3.734E-05*SUN)
      RCONST(40) = (ARR2(3.0E-11,-1550.0))
      RCONST(42) = (ARR2(1.2E-11,-986.0))
      RCONST(43) = (ARR2(7.0E-12,250.0))
      RCONST(45) = (4.00E-06*SUN)
      RCONST(46) = (ARR2(5.4E-12,250.0))
      RCONST(47) = (ARR2(8.0E-20,5500.0))
      RCONST(48) = (ARR2(9.4E+16,-14000.0))
      RCONST(51) = (ARR2(1.1E+2,-1710.0))
      RCONST(53) = (ARR2(1.0E+15,-8000.0))
      RCONST(56) = (ARR2(1.2E-11,-324.0))
      RCONST(57) = (ARR2(5.2E-12,504.0))
      RCONST(58) = (ARR2(1.4E-14,-2105.0))
      RCONST(60) = (ARR2(1.0E-11,-792.0))
      RCONST(61) = (ARR2(2.0E-12,411.0))
      RCONST(62) = (ARR2(1.3E-14,-2633.0))
      RCONST(63) = (ARR2(2.1E-12,322.0))
      RCONST(69) = (ARR2(1.7E-11,116.0))
      RCONST(71) = (5.334E-05*SUN)
      RCONST(72) = (ARR2(5.4E-17,-500.0))
      RCONST(74) = (1.654E-04*SUN)
      RCONST(80) = (ARR2(1.7E-14,1300.0))
      RETURN
      END

C End of Update_RCONST function                                    
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C                                                                  
C Update_PHOTO - function to update photolytical rate constants    
C   Arguments :                                                    
C                                                                  
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      SUBROUTINE Update_PHOTO ( )

      IMPLICIT NONE
      INCLUDE 'cbm4_ref_Parameters.h'


      INCLUDE 'cbm4_ref_Global.h'

      RCONST(1) = (8.89E-3*SUN)
      RCONST(8) = (3.556E-04*SUN)
      RCONST(9) = (2.489E-05*SUN)
      RCONST(14) = (1.378E-01*SUN)
      RCONST(23) = (1.511e-03*SUN)
      RCONST(34) = (6.312E-06*SUN)
      RCONST(38) = (2.845E-05*SUN)
      RCONST(39) = (3.734E-05*SUN)
      RCONST(45) = (4.00E-06*SUN)
      RCONST(71) = (5.334E-05*SUN)
      RCONST(74) = (1.654E-04*SUN)
      RETURN
      END

C End of Update_PHOTO function                                     
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


