C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C                                                                  
C Initialization File                                              
C                                                                  
C Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  
C       (http://www.cs.vt.edu/~asandu/Software/KPP)                
C KPP is distributed under GPL, the general public licence         
C       (http://www.gnu.org/copyleft/gpl.html)                     
C (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           
C (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            
C     With important contributions from:                           
C        M. Damian, Villanova University, USA                      
C        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
C                                                                  
C File                 : cbm4_ref_Initialize.f                     
C Time                 : Fri Sep  2 14:39:53 2022                  
C Working directory    : /home/kyriacos/CyprusInstitute/KPP/cbm4_ref
C Equation file        : cbm4_ref.kpp                              
C Output root filename : cbm4_ref                                  
C                                                                  
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C                                                                  
C Initialize - function to initialize concentrations               
C   Arguments :                                                    
C                                                                  
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      SUBROUTINE Initialize ( )

      IMPLICIT NONE
      INCLUDE 'cbm4_ref_Parameters.h'


      INCLUDE 'cbm4_ref_Global.h'
      INTEGER i
      REAL*8 x

      CFACTOR = 2.550000d+10

      x = (1.0E-8)*CFACTOR
      DO i = 1, NVAR
        VAR(i) = x
      END DO

      x = (1.0E-8)*CFACTOR
      DO i = 1, NFIX
        FIX(i) = x
      END DO

      VAR(3) = (1.0)*CFACTOR
      VAR(5) = (10.0)*CFACTOR
      VAR(7) = (10.0)*CFACTOR
      VAR(9) = (1.0)*CFACTOR
      VAR(16) = (300.0)*CFACTOR
      VAR(17) = (10.0)*CFACTOR
      VAR(20) = (50.0)*CFACTOR
      VAR(21) = (10.0)*CFACTOR
      VAR(22) = (10.0)*CFACTOR
      VAR(23) = (10.0)*CFACTOR
      VAR(24) = (10)*CFACTOR
      VAR(25) = (100.0)*CFACTOR
      VAR(26) = (20.0)*CFACTOR
      VAR(31) = (50.0)*CFACTOR
      FIX(1) = (1.25E+8)*CFACTOR
C constant rate coefficients                                       
      RCONST(4) = 9.3e-12
      RCONST(11) = 2.2e-10
      RCONST(18) = 1.3e-21
      RCONST(21) = 4.39999e-40
      RCONST(24) = 6.6e-12
      RCONST(25) = 1e-20
      RCONST(36) = 2.2e-13
      RCONST(37) = 1e-11
      RCONST(41) = 6.3e-16
      RCONST(44) = 2.5e-15
      RCONST(49) = 2e-12
      RCONST(50) = 6.5e-12
      RCONST(52) = 8.1e-13
      RCONST(54) = 1600
      RCONST(55) = 1.5e-11
      RCONST(59) = 7.7e-15
      RCONST(64) = 8.1e-12
      RCONST(65) = 4.2
      RCONST(66) = 4.1e-11
      RCONST(67) = 2.2e-11
      RCONST(68) = 1.4e-11
      RCONST(70) = 3e-11
      RCONST(73) = 1.7e-11
      RCONST(75) = 1.8e-11
      RCONST(76) = 9.6e-11
      RCONST(77) = 1.2e-17
      RCONST(78) = 3.2e-13
      RCONST(79) = 8.1e-12
      RCONST(81) = 6.8e-13
C END constant rate coefficients                                   

C INLINED initializations                                          

        TSTART = 12.D0*3600.D0
        TEND = TSTART + 24.D0*3600.D0 * 05.00
        DT = 3600.D0
        TEMP = 288.15

        STEPMIN=0.0001
        STEPMAX=3600.
        STEPSTART=STEPMIN

C End INLINED initializations                                      

      RETURN
      END

C End of Initialize function                                       
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


