C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C                                                                  
C Parameter Header File                                            
C                                                                  
C Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  
C       (http://www.cs.vt.edu/~asandu/Software/KPP)                
C KPP is distributed under GPL, the general public licence         
C       (http://www.gnu.org/copyleft/gpl.html)                     
C (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           
C (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            
C     With important contributions from:                           
C        M. Damian, Villanova University, USA                      
C        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
C                                                                  
C File                 : saprc_ref_Parameters.h                    
C Time                 : Wed Mar  9 12:16:09 2022                  
C Working directory    : /home/kyriacos/CyprusInstitute/kpp/saprc_ref
C Equation file        : saprc_ref.kpp                             
C Output root filename : saprc_ref                                 
C                                                                  
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




C NSPEC - Number of chemical species                               
      INTEGER NSPEC
      PARAMETER ( NSPEC = 79 )
C NVAR - Number of Variable species                                
      INTEGER NVAR
      PARAMETER ( NVAR = 74 )
C NVARACT - Number of Active species                               
      INTEGER NVARACT
      PARAMETER ( NVARACT = 66 )
C NFIX - Number of Fixed species                                   
      INTEGER NFIX
      PARAMETER ( NFIX = 5 )
C NREACT - Number of reactions                                     
      INTEGER NREACT
      PARAMETER ( NREACT = 211 )
C NVARST - Starting of variables in conc. vect.                    
      INTEGER NVARST
      PARAMETER ( NVARST = 1 )
C NFIXST - Starting of fixed in conc. vect.                        
      INTEGER NFIXST
      PARAMETER ( NFIXST = 75 )
C NONZERO - Number of nonzero entries in Jacobian                  
      INTEGER NONZERO
      PARAMETER ( NONZERO = 1 )
C LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
      INTEGER LU_NONZERO
      PARAMETER ( LU_NONZERO = 1 )
C CNVAR - (NVAR+1) Number of elements in compressed row format     
      INTEGER CNVAR
      PARAMETER ( CNVAR = 75 )
C CNEQN - (NREACT+1) Number stoicm elements in compressed col format
      INTEGER CNEQN
      PARAMETER ( CNEQN = 212 )
C NHESS - Length of Sparse Hessian                                 
      INTEGER NHESS
      PARAMETER ( NHESS = 848 )
C NLOOKAT - Number of species to look at                           
      INTEGER NLOOKAT
      PARAMETER ( NLOOKAT = 79 )
C NMONITOR - Number of species to monitor                          
      INTEGER NMONITOR
      PARAMETER ( NMONITOR = 4 )
C NMASS - Number of atoms to check mass balance                    
      INTEGER NMASS
      PARAMETER ( NMASS = 1 )

C Index declaration for variable species in C and VAR              
C   VAR(ind_spc) = C(ind_spc)                                      

      INTEGER ind_H2SO4
      PARAMETER ( ind_H2SO4 = 1 )
      INTEGER ind_HCOOH
      PARAMETER ( ind_HCOOH = 2 )
      INTEGER ind_CCO_OH
      PARAMETER ( ind_CCO_OH = 3 )
      INTEGER ind_RCO_OH
      PARAMETER ( ind_RCO_OH = 4 )
      INTEGER ind_CCO_OOH
      PARAMETER ( ind_CCO_OOH = 5 )
      INTEGER ind_RCO_OOH
      PARAMETER ( ind_RCO_OOH = 6 )
      INTEGER ind_XN
      PARAMETER ( ind_XN = 7 )
      INTEGER ind_XC
      PARAMETER ( ind_XC = 8 )
      INTEGER ind_SO2
      PARAMETER ( ind_SO2 = 9 )
      INTEGER ind_O1D
      PARAMETER ( ind_O1D = 10 )
      INTEGER ind_ALK1
      PARAMETER ( ind_ALK1 = 11 )
      INTEGER ind_BACL
      PARAMETER ( ind_BACL = 12 )
      INTEGER ind_PAN
      PARAMETER ( ind_PAN = 13 )
      INTEGER ind_PAN2
      PARAMETER ( ind_PAN2 = 14 )
      INTEGER ind_PBZN
      PARAMETER ( ind_PBZN = 15 )
      INTEGER ind_MA_PAN
      PARAMETER ( ind_MA_PAN = 16 )
      INTEGER ind_H2O2
      PARAMETER ( ind_H2O2 = 17 )
      INTEGER ind_N2O5
      PARAMETER ( ind_N2O5 = 18 )
      INTEGER ind_HONO
      PARAMETER ( ind_HONO = 19 )
      INTEGER ind_ALK2
      PARAMETER ( ind_ALK2 = 20 )
      INTEGER ind_ALK3
      PARAMETER ( ind_ALK3 = 21 )
      INTEGER ind_TBU_O
      PARAMETER ( ind_TBU_O = 22 )
      INTEGER ind_ALK5
      PARAMETER ( ind_ALK5 = 23 )
      INTEGER ind_ARO2
      PARAMETER ( ind_ARO2 = 24 )
      INTEGER ind_HNO4
      PARAMETER ( ind_HNO4 = 25 )
      INTEGER ind_COOH
      PARAMETER ( ind_COOH = 26 )
      INTEGER ind_HOCOO
      PARAMETER ( ind_HOCOO = 27 )
      INTEGER ind_BZNO2_O
      PARAMETER ( ind_BZNO2_O = 28 )
      INTEGER ind_MEOH
      PARAMETER ( ind_MEOH = 29 )
      INTEGER ind_ALK4
      PARAMETER ( ind_ALK4 = 30 )
      INTEGER ind_ARO1
      PARAMETER ( ind_ARO1 = 31 )
      INTEGER ind_DCB2
      PARAMETER ( ind_DCB2 = 32 )
      INTEGER ind_DCB3
      PARAMETER ( ind_DCB3 = 33 )
      INTEGER ind_CRES
      PARAMETER ( ind_CRES = 34 )
      INTEGER ind_DCB1
      PARAMETER ( ind_DCB1 = 35 )
      INTEGER ind_NPHE
      PARAMETER ( ind_NPHE = 36 )
      INTEGER ind_ROOH
      PARAMETER ( ind_ROOH = 37 )
      INTEGER ind_BALD
      PARAMETER ( ind_BALD = 38 )
      INTEGER ind_PHEN
      PARAMETER ( ind_PHEN = 39 )
      INTEGER ind_CO
      PARAMETER ( ind_CO = 40 )
      INTEGER ind_MGLY
      PARAMETER ( ind_MGLY = 41 )
      INTEGER ind_ACET
      PARAMETER ( ind_ACET = 42 )
      INTEGER ind_HNO3
      PARAMETER ( ind_HNO3 = 43 )
      INTEGER ind_ETHENE
      PARAMETER ( ind_ETHENE = 44 )
      INTEGER ind_GLY
      PARAMETER ( ind_GLY = 45 )
      INTEGER ind_BZ_O
      PARAMETER ( ind_BZ_O = 46 )
      INTEGER ind_ISOPRENE
      PARAMETER ( ind_ISOPRENE = 47 )
      INTEGER ind_R2O2
      PARAMETER ( ind_R2O2 = 48 )
      INTEGER ind_TERP
      PARAMETER ( ind_TERP = 49 )
      INTEGER ind_METHACRO
      PARAMETER ( ind_METHACRO = 50 )
      INTEGER ind_OLE1
      PARAMETER ( ind_OLE1 = 51 )
      INTEGER ind_ISOPROD
      PARAMETER ( ind_ISOPROD = 52 )
      INTEGER ind_OLE2
      PARAMETER ( ind_OLE2 = 53 )
      INTEGER ind_MVK
      PARAMETER ( ind_MVK = 54 )
      INTEGER ind_CCHO
      PARAMETER ( ind_CCHO = 55 )
      INTEGER ind_HCHO
      PARAMETER ( ind_HCHO = 56 )
      INTEGER ind_RNO3
      PARAMETER ( ind_RNO3 = 57 )
      INTEGER ind_O3P
      PARAMETER ( ind_O3P = 58 )
      INTEGER ind_RCHO
      PARAMETER ( ind_RCHO = 59 )
      INTEGER ind_MEK
      PARAMETER ( ind_MEK = 60 )
      INTEGER ind_PROD2
      PARAMETER ( ind_PROD2 = 61 )
      INTEGER ind_O3
      PARAMETER ( ind_O3 = 62 )
      INTEGER ind_HO2
      PARAMETER ( ind_HO2 = 63 )
      INTEGER ind_RO2_N
      PARAMETER ( ind_RO2_N = 64 )
      INTEGER ind_MA_RCO3
      PARAMETER ( ind_MA_RCO3 = 65 )
      INTEGER ind_C_O2
      PARAMETER ( ind_C_O2 = 66 )
      INTEGER ind_BZCO_O2
      PARAMETER ( ind_BZCO_O2 = 67 )
      INTEGER ind_RO2_R
      PARAMETER ( ind_RO2_R = 68 )
      INTEGER ind_NO
      PARAMETER ( ind_NO = 69 )
      INTEGER ind_NO2
      PARAMETER ( ind_NO2 = 70 )
      INTEGER ind_NO3
      PARAMETER ( ind_NO3 = 71 )
      INTEGER ind_CCO_O2
      PARAMETER ( ind_CCO_O2 = 72 )
      INTEGER ind_RCO_O2
      PARAMETER ( ind_RCO_O2 = 73 )
      INTEGER ind_OH
      PARAMETER ( ind_OH = 74 )

C Index declaration for fixed species in C                         
C   C(ind_spc)                                                     

      INTEGER ind_AIR
      PARAMETER ( ind_AIR = 75 )
      INTEGER ind_O2
      PARAMETER ( ind_O2 = 76 )
      INTEGER ind_H2O
      PARAMETER ( ind_H2O = 77 )
      INTEGER ind_H2
      PARAMETER ( ind_H2 = 78 )
      INTEGER ind_CH4
      PARAMETER ( ind_CH4 = 79 )

C Index declaration for fixed species in FIX                       
C    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)                 

      INTEGER indf_AIR
      PARAMETER ( indf_AIR = 1 )
      INTEGER indf_O2
      PARAMETER ( indf_O2 = 2 )
      INTEGER indf_H2O
      PARAMETER ( indf_H2O = 3 )
      INTEGER indf_H2
      PARAMETER ( indf_H2 = 4 )
      INTEGER indf_CH4
      PARAMETER ( indf_CH4 = 5 )

C NJVRP - Length of sparse Jacobian JVRP                           
      INTEGER NJVRP
      PARAMETER ( NJVRP = 363 )

C NSTOICM - Length of Sparse Stoichiometric Matrix                 
      INTEGER NSTOICM
      PARAMETER ( NSTOICM = 1024 )
