! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Sparse Stoichiometric Data Structures File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : chapman_f90_mp_StoichiomSP.f90
! Time                 : Thu Sep  8 14:55:46 2022
! Working directory    : /home/kyriacos/CyprusInstitute/KPP/chapman_f90_mp
! Equation file        : chapman_f90_mp.kpp
! Output root filename : chapman_f90_mp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE chapman_f90_mp_StoichiomSP

  USE chapman_f90_mp_Precision
  PUBLIC
  SAVE


! Row-compressed sparse data for the Jacobian of reaction products JVRP

  INTEGER, PARAMETER, DIMENSION(8) :: CROW_JVRP = (/ &
       1,  1,  2,  3,  5,  7,  9, 10 /)

  INTEGER, PARAMETER, DIMENSION(9) :: ICOL_JVRP = (/ &
       1,  2,  1,  2,  2,  3,  1,  4,  4 /)

  INTEGER, PARAMETER, DIMENSION(9) :: IROW_JVRP = (/ &
       2,  3,  4,  4,  5,  5,  6,  6,  7 /)



!  Stoichiometric Matrix in Compressed Column Sparse Format


  INTEGER, PARAMETER, DIMENSION(8) :: CCOL_STOICM = (/ &
       1,  2,  4,  6,  8, 11, 14, 17 /)

  INTEGER, PARAMETER, DIMENSION(16) :: IROW_STOICM = (/ &
       1,  1,  2,  1,  2,  1,  2,  2,  3,  4,  1,  3, &
       4,  1,  3,  4 /)

  INTEGER, PARAMETER, DIMENSION(16) :: ICOL_STOICM = (/ &
       1,  2,  2,  3,  3,  4,  4,  5,  5,  5,  6,  6, &
       6,  7,  7,  7 /)

  REAL(kind=sp), PARAMETER, DIMENSION(16) :: STOICM = (/ &
     2.000000e+00,-1.000000e+00,1.000000e+00,1.000000e+00,-1.000000e+00, &
     -1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,1.000000e+00, &
     -1.000000e+00,1.000000e+00,-1.000000e+00,1.000000e+00,1.000000e+00, &
     -1.000000e+00 /)


END MODULE chapman_f90_mp_StoichiomSP

