C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C                                                                  
C The Reaction Rates File                                          
C                                                                  
C Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  
C       (http://www.cs.vt.edu/~asandu/Software/KPP)                
C KPP is distributed under GPL, the general public licence         
C       (http://www.gnu.org/copyleft/gpl.html)                     
C (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           
C (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            
C     With important contributions from:                           
C        M. Damian, Villanova University, USA                      
C        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
C                                                                  
C File                 : tropo_ref_Rates.f                         
C Time                 : Wed Mar  9 12:16:32 2022                  
C Working directory    : /home/kyriacos/CyprusInstitute/kpp/tropo_ref
C Equation file        : tropo_ref.kpp                             
C Output root filename : tropo_ref                                 
C                                                                  
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




C Begin Rate Law Functions from KPP_HOME/util/UserRateLaws         

C  User-defined Rate Law functions
C  Note: the default argument type for rate laws, as read from the equations file, is single precision
C        but all the internal calculations are performed in REAL*8

C Arrhenius
      REAL*8 FUNCTION ARR( A0,B0,C0 )
      INCLUDE 'tropo_ref_Parameters.h'
      INCLUDE 'tropo_ref_Global.h'
                 
      REAL A0,B0,C0      
      ARR =  DBLE(A0) * EXP(-DBLE(B0)/TEMP) * (TEMP/300.0D0)**DBLE(C0)   
           
      RETURN
      END           


C Simplified Arrhenius, with two arguments
C Note: The argument B0 has a changed sign when compared to ARR
      REAL*8 FUNCTION ARR2( A0,B0 )
      INCLUDE 'tropo_ref_Parameters.h'
      INCLUDE 'tropo_ref_Global.h'
                 
      REAL A0,B0     
      ARR2 =  DBLE(A0) * EXP( DBLE(B0)/TEMP )   
           
      RETURN
      END           

      REAL*8 FUNCTION EP2(A0,C0,A2,C2,A3,C3)
      INCLUDE 'tropo_ref_Parameters.h'                       
      INCLUDE 'tropo_ref_Global.h'
      
      REAL A0,C0,A2,C2,A3,C3
      REAL*8 K0,K2,K3
      
      K0 = DBLE(A0) * EXP(-DBLE(C0)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      K3 = DBLE(A3) * EXP(-DBLE(C3)/TEMP)
      K3 = K3*CFACTOR*1.0d6
      EP2 = K0 + K3/(1.0d0+K3/K2 )
        
      RETURN
      END  


      REAL*8 FUNCTION EP3(A1,C1,A2,C2) 
      INCLUDE 'tropo_ref_Parameters.h'               
      INCLUDE 'tropo_ref_Global.h'
      
      REAL A1, C1, A2, C2
      REAL*8 K1, K2
      
      K1 = DBLE(A1) * EXP(-DBLE(C1)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      EP3 = K1 + K2*(1.0d6*CFACTOR)
      
      RETURN
      END    


      REAL*8 FUNCTION FALL ( A0,B0,C0,A1,B1,C1,CF)
      INCLUDE 'tropo_ref_Parameters.h'                      
      INCLUDE 'tropo_ref_Global.h'
      
      REAL A0,B0,C0,A1,B1,C1,CF
      REAL*8 K0, K1
      
      K0 = DBLE(A0) * EXP(-DBLE(B0)/TEMP)* (TEMP/300.0D0)**DBLE(C0)
      K1 = DBLE(A1) * EXP(-DBLE(B1)/TEMP)* (TEMP/300.0D0)**DBLE(C1)
      K0 = K0*CFACTOR*1.0D6
      K1 = K0/K1
      FALL = (K0/(1.0d0+K1))*
     *      DBLE(CF)**(1.0d0/(1.0d0+(DLOG10(K1))**2))
        
      RETURN
      END

C End Rate Law Functions from KPP_HOME/util/UserRateLaws           


C Begin INLINED Rate Law Functions                                 


C End INLINED Rate Law Functions                                   

C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C                                                                  
C Update_SUN - update SUN light using TIME                         
C   Arguments :                                                    
C                                                                  
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      SUBROUTINE Update_SUN()

      IMPLICIT NONE
      INCLUDE 'tropo_ref_Parameters.h'
      INCLUDE 'tropo_ref_Global.h'

      REAL*8 SunRise, SunSet
      REAL*8 Thour, Tlocal, Ttmp, PI
      PARAMETER (PI = 3.14159265358979d0) 
   
      SunRise = 4.5
      SunSet  = 19.5
      Thour = TIME/3600.
      Tlocal = Thour - (INT(Thour)/24)*24

      IF ((Tlocal.GE.SunRise).AND.(Tlocal.LE.SunSet)) THEN
        Ttmp = (2.0*Tlocal-SunRise-SunSet)/(SunSet-SunRise)
        IF (Ttmp.GT.0) THEN
          Ttmp =  Ttmp*Ttmp
        ELSE
          Ttmp = -Ttmp*Ttmp
        END IF
        SUN = ( 1.0 + COS(PI*Ttmp) )/2.0 
      ELSE
        SUN = 0.0
      END IF

      RETURN
      END

C End of Update_SUN function                                       
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C                                                                  
C Update_RCONST - function to update rate constants                
C   Arguments :                                                    
C                                                                  
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      SUBROUTINE Update_RCONST ( )

      IMPLICIT NONE
      INCLUDE 'tropo_ref_Parameters.h'


      INCLUDE 'tropo_ref_Global.h'
C  Definitions for User-defined Rate Law functions
C  To be inserted in funcions that call rate laws

      REAL*8 ARR, ARR2
      REAL*8 EP2, EP3, FALL
      EXTERNAL ARR, ARR2, EP2, EP3, FALL


C Begin INLINED RCONST                                             


C End INLINED RCONST                                               

      RCONST(1) = (1.765E-2*SUN)
      RCONST(2) = (ARR2(2.2E-12,-1430.0))
      RCONST(3) = (ARR2(1.2E-13,-2450.0))
      RCONST(4) = (ARR2(1.7E-11,150.0))
      RCONST(7) = (ARR2(2.5E-14,-1230.0))
      RCONST(8) = (3.29*RCONST[1])
      RCONST(10) = (1.5796E-7*SUN)
      RCONST(12) = (0.205*RCONST[1])
      RCONST(14) = (7.8E-7*SUN)
      RCONST(15) = (ARR2(9.4E-15,778.0))
      RCONST(18) = (ARR2(1.6E-12,-1000.0))
      RCONST(19) = (ARR2(3.7E-12,240.0))
      RCONST(22) = (ARR2(1.4E-14,-600.0))
      RCONST(24) = (1.366E-5*SUN)
      RCONST(25) = (ARR2(3.3E-12,-200.0))
      RCONST(27) = (1E-4*RCONST[1])
      RCONST(28) = (ARR2(1.3E-12,380.0))
      RCONST(30) = (2.7E-5*SUN)
      RCONST(31) = (1.1182E-4*SUN)
      RCONST(34) = (ARR2(4.2E-12,180.0))
      RCONST(39) = (ARR2(6.9E-12,250.0))
      RCONST(41) = (4.556E-6*SUN)
      RCONST(42) = (1.118E-4*SUN)
      RCONST(44) = (ARR2(2.2E16,-13435.0))
      RCONST(45) = (ARR2(4.2E-12,180.0))
      RCONST(46) = (ARR2(4.2E-12,180.0))
      RCONST(47) = (ARR2(2.4E-12,1710.0))
      RCONST(48) = (ARR2(1.7E-11,-1232.0))
      RCONST(49) = (ARR2(4.2E-12,180.0))
      RCONST(50) = (ARR2(1.18E-11,-679.0))
      RCONST(51) = (ARR2(4.2E-12,180.0))
      RCONST(52) = (ARR2(2E-11,-500.0))
      RCONST(53) = (ARR2(4.2E-12,180.0))
      RCONST(56) = (ARR2(4.2E-12,180.0))
      RCONST(57) = (ARR2(1.5E-13,220.0))
      RCONST(65) = (ARR2(1.2E-11,-890.0))
      RCONST(66) = (ARR2(4.2E-12,180.0))
      RCONST(67) = (2.6E-4*RCONST[1])
      RCONST(70) = (ARR2(1.66E-12,474.0))
      RCONST(71) = (ARR2(4.2E-12,180.0))
      RCONST(72) = (ARR2(4.1E-12,537.0))
      RCONST(73) = (ARR2(4.2E-12,180.0))
      RCONST(74) = (ARR2(1.2E-14,-2633.0))
      RCONST(75) = (ARR2(7.8E-14,-2105.0))
      RCONST(91) = (ARR2(4.2E-12,180.0))
      RCONST(97) = (ARR2(4.2E-12,180.0))
      RCONST(98) = (8.0E-3*RCONST[1])
      RCONST(100) = (1.9E-2*RCONST[1])
      RCONST(106) = (ARR2(2.2E16,-13435.0))
      RCONST(107) = (ARR2(4.2E-12,180.0))
      RCONST(108) = (ARR2(4.2E-12,180.0))
      RCONST(109) = (1E-2*RCONST[1])
      RCONST(113) = (1.5*1.)
      RCONST(114) = (ARR2(2.5E-11,409.0))
      RCONST(115) = (ARR2(4.2E-12,180.0))
      RCONST(117) = (ARR2(3.0E-12,500.0))
      RCONST(118) = (ARR2(4.2E-12,180.0))
      RCONST(122) = (ARR2(2.2E+16,-13435.0))
      RCONST(123) = (ARR2(4.2E-12,180.0))
      RCONST(125) = (ARR2(3.86E-12,500.0))
      RCONST(126) = (ARR2(4.2E-12,180.0))
      RCONST(130) = (ARR2(2.2E+16,-13435.0))
      RCONST(131) = (ARR2(4.2E-12,180.0))
      RCONST(133) = (ARR2(7.0E-15,-1900.0))
      RCONST(134) = (ARR2(4.0E-15,-2000.0))
      RCONST(135) = (ARR2(4.4E-15,-2500.0))
      RCONST(136) = (ARR2(4.2E-12,180.0))
      RCONST(137) = (ARR2(4.2E-13,180.0))
      RCONST(139) = (ARR2(4.2E-12,180.0))
      RCONST(140) = (ARR2(4.2E-13,180.0))
      RCONST(142) = (ARR2(4.2E-12,180.0))
      RCONST(143) = (ARR2(4.2E-13,180.0))
      RCONST(145) = (5E-4*RCONST[1])
      RCONST(146) = (0.15*RCONST[1])
      RCONST(148) = (ARR2(3.00E-12,-450.0))
      RCONST(149) = (ARR2(4.2E-12,180.0))
      RCONST(150) = (ARR2(4.2E-13,180.0))
      RCONST(153) = (ARR2(4.2E-12,180.0))
      RCONST(157) = (ARR2(4.2E-12,180.0))
      RCONST(165) = (ARR2(1.2E-11,500.0))
      RCONST(172) = (ARR2(4.6E-11,230.0))
      RCONST(173) = (5.00E-4*RCONST[1])
      RCONST(176) = (ARR2(8.5E-13,-2450.0))
      RCONST(177) = (ARR2(1.23E-12,-651.0))
      RCONST(178) = (ARR2(2.3E-12,170.0))
      RETURN
      END

C End of Update_RCONST function                                    
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C                                                                  
C Update_PHOTO - function to update photolytical rate constants    
C   Arguments :                                                    
C                                                                  
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      SUBROUTINE Update_PHOTO ( )

      IMPLICIT NONE
      INCLUDE 'tropo_ref_Parameters.h'


      INCLUDE 'tropo_ref_Global.h'

      RCONST(1) = (1.765E-2*SUN)
      RCONST(8) = (3.29*RCONST[1])
      RCONST(10) = (1.5796E-7*SUN)
      RCONST(12) = (0.205*RCONST[1])
      RCONST(14) = (7.8E-7*SUN)
      RCONST(24) = (1.366E-5*SUN)
      RCONST(27) = (1E-4*RCONST[1])
      RCONST(30) = (2.7E-5*SUN)
      RCONST(31) = (1.1182E-4*SUN)
      RCONST(41) = (4.556E-6*SUN)
      RCONST(42) = (1.118E-4*SUN)
      RCONST(67) = (2.6E-4*RCONST[1])
      RCONST(98) = (8.0E-3*RCONST[1])
      RCONST(100) = (1.9E-2*RCONST[1])
      RCONST(109) = (1E-2*RCONST[1])
      RCONST(145) = (5E-4*RCONST[1])
      RCONST(146) = (0.15*RCONST[1])
      RCONST(173) = (5.00E-4*RCONST[1])
      RETURN
      END

C End of Update_PHOTO function                                     
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


