C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C                                                                  
C Initialization File                                              
C                                                                  
C Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  
C       (http://www.cs.vt.edu/~asandu/Software/KPP)                
C KPP is distributed under GPL, the general public licence         
C       (http://www.gnu.org/copyleft/gpl.html)                     
C (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           
C (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            
C     With important contributions from:                           
C        M. Damian, Villanova University, USA                      
C        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
C                                                                  
C File                 : tropo_ref_Initialize.f                    
C Time                 : Wed Mar  9 12:16:32 2022                  
C Working directory    : /home/kyriacos/CyprusInstitute/kpp/tropo_ref
C Equation file        : tropo_ref.kpp                             
C Output root filename : tropo_ref                                 
C                                                                  
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C                                                                  
C Initialize - function to initialize concentrations               
C   Arguments :                                                    
C                                                                  
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      SUBROUTINE Initialize ( )

      IMPLICIT NONE
      INCLUDE 'tropo_ref_Parameters.h'


      INCLUDE 'tropo_ref_Global.h'
      INTEGER i
      REAL*8 x

      CFACTOR = 1.000000d+00

      x = (1.0E-8)*CFACTOR
      DO i = 1, NVAR
        VAR(i) = x
      END DO

      x = (1.0E-8)*CFACTOR
      DO i = 1, NFIX
        FIX(i) = x
      END DO

      VAR(1) = (1.0)*CFACTOR
      VAR(23) = (2.0)*CFACTOR
      VAR(29) = (1700)*CFACTOR
      VAR(31) = (1E-8)*CFACTOR
      VAR(41) = (100.0)*CFACTOR
      VAR(74) = (100.0)*CFACTOR
      VAR(76) = (0.05)*CFACTOR
      VAR(78) = (5.0)*CFACTOR
      VAR(81) = (0.05)*CFACTOR
      VAR(83) = (0.1)*CFACTOR
      FIX(1) = (2.E+8)*CFACTOR
      FIX(2) = (500.0)*CFACTOR
      FIX(3) = (5.E+7)*CFACTOR
      FIX(4) = (500)*CFACTOR
C constant rate coefficients                                       
      RCONST(5) = 1.45e-12
      RCONST(6) = 5e-06
      RCONST(9) = 2.5e-12
      RCONST(11) = 7.218e-12
      RCONST(13) = 1.2794e-11
      RCONST(16) = 1.3e-21
      RCONST(17) = 1.7823e-13
      RCONST(20) = 1.7851e-12
      RCONST(21) = 6.8868e-06
      RCONST(23) = 4.7165e-12
      RCONST(26) = 4e-24
      RCONST(29) = 1e-20
      RCONST(32) = 1e-11
      RCONST(33) = 1e-14
      RCONST(35) = 2e-12
      RCONST(36) = 1e-13
      RCONST(37) = 3.2e-13
      RCONST(38) = 6e-16
      RCONST(40) = 2.7e-15
      RCONST(43) = 4.7e-12
      RCONST(54) = 4e-17
      RCONST(55) = 2e-12
      RCONST(58) = 5e-14
      RCONST(59) = 5e-14
      RCONST(60) = 3e-12
      RCONST(61) = 3e-12
      RCONST(62) = 3e-12
      RCONST(63) = 3e-12
      RCONST(64) = 3e-12
      RCONST(68) = 7e-16
      RCONST(69) = 3e-12
      RCONST(76) = 7e-12
      RCONST(77) = 7e-13
      RCONST(78) = 4e-18
      RCONST(79) = 7e-12
      RCONST(80) = 7e-13
      RCONST(81) = 4e-18
      RCONST(82) = 5e-14
      RCONST(83) = 5e-14
      RCONST(84) = 3e-12
      RCONST(85) = 3e-12
      RCONST(86) = 7e-14
      RCONST(87) = 7e-14
      RCONST(88) = 1.26e-13
      RCONST(89) = 6.8e-12
      RCONST(90) = 3e-12
      RCONST(92) = 1.36e-14
      RCONST(93) = 1.36e-14
      RCONST(94) = 1.36e-14
      RCONST(95) = 1.36e-14
      RCONST(96) = 1.52e-11
      RCONST(99) = 1.15e-11
      RCONST(101) = 1.73e-11
      RCONST(102) = 4.25e-11
      RCONST(103) = 1e-11
      RCONST(104) = 2.8e-11
      RCONST(105) = 4.7e-12
      RCONST(110) = 4e-12
      RCONST(111) = 4e-12
      RCONST(112) = 1e-12
      RCONST(116) = 3e-12
      RCONST(119) = 3e-12
      RCONST(120) = 1.02e-11
      RCONST(121) = 4.7e-12
      RCONST(124) = 3e-12
      RCONST(127) = 3e-12
      RCONST(128) = 1.5e-11
      RCONST(129) = 4.7e-12
      RCONST(132) = 3e-12
      RCONST(138) = 3.4e-18
      RCONST(141) = 3.4e-18
      RCONST(144) = 3.4e-18
      RCONST(147) = 1.7e-11
      RCONST(151) = 3e-12
      RCONST(152) = 6e-14
      RCONST(154) = 3e-12
      RCONST(155) = 3.3e-15
      RCONST(156) = 6.7e-15
      RCONST(158) = 3e-12
      RCONST(159) = 5.2e-16
      RCONST(160) = 3e-12
      RCONST(161) = 3e-12
      RCONST(162) = 7e-14
      RCONST(163) = 7e-14
      RCONST(164) = 7e-14
      RCONST(166) = 5e-14
      RCONST(167) = 5.44e-17
      RCONST(168) = 3.46e-17
      RCONST(169) = 2.21e-17
      RCONST(170) = 1.03e-15
      RCONST(171) = 2.16e-16
      RCONST(174) = 1e-11
      RCONST(175) = 8.3e-12
C END constant rate coefficients                                   

C INLINED initializations                                          

	TSTART = 12.0*3600.0
	TEND = TSTART + 24.0*3600.0 * 5
	DT = 3600.0
        TEMP = 288.15

        STEPMIN=0.0001
        STEPMAX=3600.
        STEPSTART=STEPMIN

C End INLINED initializations                                      

      RETURN
      END

C End of Initialize function                                       
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


