C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C                                                                  
C Parameter Header File                                            
C                                                                  
C Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  
C       (http://www.cs.vt.edu/~asandu/Software/KPP)                
C KPP is distributed under GPL, the general public licence         
C       (http://www.gnu.org/copyleft/gpl.html)                     
C (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           
C (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            
C     With important contributions from:                           
C        M. Damian, Villanova University, USA                      
C        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
C                                                                  
C File                 : smog_ref_Parameters.h                     
C Time                 : Fri Mar 18 18:12:32 2022                  
C Working directory    : /home/kyriacos/CyprusInstitute/kpp/smog_ref
C Equation file        : smog_ref.kpp                              
C Output root filename : smog_ref                                  
C                                                                  
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




C NSPEC - Number of chemical species                               
      INTEGER NSPEC
      PARAMETER ( NSPEC = 16 )
C NVAR - Number of Variable species                                
      INTEGER NVAR
      PARAMETER ( NVAR = 12 )
C NVARACT - Number of Active species                               
      INTEGER NVARACT
      PARAMETER ( NVARACT = 11 )
C NFIX - Number of Fixed species                                   
      INTEGER NFIX
      PARAMETER ( NFIX = 4 )
C NREACT - Number of reactions                                     
      INTEGER NREACT
      PARAMETER ( NREACT = 12 )
C NVARST - Starting of variables in conc. vect.                    
      INTEGER NVARST
      PARAMETER ( NVARST = 1 )
C NFIXST - Starting of fixed in conc. vect.                        
      INTEGER NFIXST
      PARAMETER ( NFIXST = 13 )
C NONZERO - Number of nonzero entries in Jacobian                  
      INTEGER NONZERO
      PARAMETER ( NONZERO = 1 )
C LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
      INTEGER LU_NONZERO
      PARAMETER ( LU_NONZERO = 1 )
C CNVAR - (NVAR+1) Number of elements in compressed row format     
      INTEGER CNVAR
      PARAMETER ( CNVAR = 13 )
C CNEQN - (NREACT+1) Number stoicm elements in compressed col format
      INTEGER CNEQN
      PARAMETER ( CNEQN = 13 )
C NHESS - Length of Sparse Hessian                                 
      INTEGER NHESS
      PARAMETER ( NHESS = 28 )
C NLOOKAT - Number of species to look at                           
      INTEGER NLOOKAT
      PARAMETER ( NLOOKAT = 16 )
C NMONITOR - Number of species to monitor                          
      INTEGER NMONITOR
      PARAMETER ( NMONITOR = 1 )
C NMASS - Number of atoms to check mass balance                    
      INTEGER NMASS
      PARAMETER ( NMASS = 1 )

C Index declaration for variable species in C and VAR              
C   VAR(ind_spc) = C(ind_spc)                                      

      INTEGER ind_HNO3
      PARAMETER ( ind_HNO3 = 1 )
      INTEGER ind_O
      PARAMETER ( ind_O = 2 )
      INTEGER ind_RH
      PARAMETER ( ind_RH = 3 )
      INTEGER ind_RCOO2NO2
      PARAMETER ( ind_RCOO2NO2 = 4 )
      INTEGER ind_O3
      PARAMETER ( ind_O3 = 5 )
      INTEGER ind_HO2
      PARAMETER ( ind_HO2 = 6 )
      INTEGER ind_RCOO2
      PARAMETER ( ind_RCOO2 = 7 )
      INTEGER ind_RCHO
      PARAMETER ( ind_RCHO = 8 )
      INTEGER ind_RO2
      PARAMETER ( ind_RO2 = 9 )
      INTEGER ind_NO
      PARAMETER ( ind_NO = 10 )
      INTEGER ind_NO2
      PARAMETER ( ind_NO2 = 11 )
      INTEGER ind_OH
      PARAMETER ( ind_OH = 12 )

C Index declaration for fixed species in C                         
C   C(ind_spc)                                                     

      INTEGER ind_H2O
      PARAMETER ( ind_H2O = 13 )
      INTEGER ind_O2
      PARAMETER ( ind_O2 = 14 )
      INTEGER ind_CO
      PARAMETER ( ind_CO = 15 )
      INTEGER ind_CO2
      PARAMETER ( ind_CO2 = 16 )

C Index declaration for fixed species in FIX                       
C    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)                 

      INTEGER indf_H2O
      PARAMETER ( indf_H2O = 1 )
      INTEGER indf_O2
      PARAMETER ( indf_O2 = 2 )
      INTEGER indf_CO
      PARAMETER ( indf_CO = 3 )
      INTEGER indf_CO2
      PARAMETER ( indf_CO2 = 4 )

C NJVRP - Length of sparse Jacobian JVRP                           
      INTEGER NJVRP
      PARAMETER ( NJVRP = 20 )

C NSTOICM - Length of Sparse Stoichiometric Matrix                 
      INTEGER NSTOICM
      PARAMETER ( NSTOICM = 39 )
