/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Hessian File                                                     */
/*                                                                  */
/* Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : strato_single_Hessian.c                   */
/* Time                 : Thu Jan 27 10:54:15 2022                  */
/* Working directory    : /home/kyriacos/CyprusInstitute/kpp/strato_single */
/* Equation file        : strato_single.kpp                         */
/* Output root filename : strato_single                             */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "strato_single_Parameters.h"
#include "strato_single_Global.h"
#include "strato_single_Sparse.h"


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Hessian - function for Hessian (Jac derivative w.r.t. variables) */
/*   Arguments :                                                    */
/*      V         - Concentrations of variable species (local)      */
/*      F         - Concentrations of fixed species (local)         */
/*      RCT       - Rate constants (local)                          */
/*      HESS      - Hessian of Var (i.e. the 3-tensor d Jac / d Var) */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

void Hessian( 
  float V[],                             /* Concentrations of variable species (local) */
  float F[],                             /* Concentrations of fixed species (local) */
  float RCT[],                           /* Rate constants (local) */
  float HESS[]                           /* Hessian of Var (i.e. the 3-tensor d Jac / d Var) */
)
{
/* --------------------------------------------------------         */
/* Note: HESS is represented in coordinate sparse format:           */
/*       HESS(m) = d^2 f_i / dv_j dv_k = d Jac_{i,j} / dv_k         */
/*       where i = IHESS_I(m), j = IHESS_J(m), k = IHESS_K(m).      */
/* --------------------------------------------------------         */
/* Note: d^2 f_i / dv_j dv_k = d^2 f_i / dv_k dv_j,                 */
/*       therefore only the terms d^2 f_i / dv_j dv_k               */
/*       with j <= k are computed and stored in HESS.               */
/* --------------------------------------------------------         */

/* Local variables                                                  */
float D2A[61];                           /* Second derivatives of equation rates */

/* Computation of the second derivatives of equation rates          */
/* D2A(0) = d^2 A(1) / dV(28)dV(31)                                 */
  D2A[0] = 1.57571e-15;
/* D2A(1) = d^2 A(4) / dV(10)dV(28)                                 */
  D2A[1] = 1.2e-10;
/* D2A(2) = d^2 A(10) / dV(19)dV(28)                                */
  D2A[2] = 1.99835e-11;
/* D2A(3) = d^2 A(12) / dV(25)dV(28)                                */
  D2A[3] = 3.25993e-14;
/* D2A(4) = d^2 A(13) / dV(25)dV(31)                                */
  D2A[4] = 3.61646e-11;
/* D2A(5) = d^2 A(14)/{dV(25)dV(25)}                                */
  D2A[5] = 1.55427e-12*2;
/* D2A(6) = d^2 A(15) / dV(31)dV(32)                                */
  D2A[6] = 6.86894e-11;
/* D2A(7) = d^2 A(16) / dV(28)dV(32)                                */
  D2A[7] = 1.38667e-15;
/* D2A(8) = d^2 A(17) / dV(19)dV(32)                                */
  D2A[8] = 7e-11;
/* D2A(9) = d^2 A(18) / dV(25)dV(32)                                */
  D2A[9] = 1.35192e-10;
/* D2A(10) = d^2 A(19)/{dV(32)dV(32)}                               */
  D2A[10] = 2.76946e-12*2;
/* D2A(11) = d^2 A(20)/{dV(32)dV(32)}                               */
  D2A[11] = 3.51541e-29*2*F[0];
/* D2A(12) = d^2 A(21) / dV(16)dV(25)                               */
  D2A[12] = 1.4948e-12;
/* D2A(13) = d^2 A(22) / dV(28)dV(29)                               */
  D2A[13] = 6.06249e-15;
/* D2A(14) = d^2 A(23) / dV(29)dV(32)                               */
  D2A[14] = 1.04211e-11;
/* D2A(15) = d^2 A(24) / dV(31)dV(33)                               */
  D2A[15] = 1.0685e-11;
/* D2A(16) = d^2 A(25) / dV(28)dV(33)                               */
  D2A[16] = 4.69913e-18;
/* D2A(17) = d^2 A(26) / dV(25)dV(33)                               */
  D2A[17] = 3.72413e-13;
/* D2A(18) = d^2 A(27) / dV(32)dV(33)                               */
  D2A[18] = 2.69029e-14;
/* D2A(19) = d^2 A(28) / dV(22)dV(31)                               */
  D2A[19] = 1e-11;
/* D2A(20) = d^2 A(29) / dV(22)dV(29)                               */
  D2A[20] = 3.03315e-11;
/* D2A(21) = d^2 A(30) / dV(22)dV(33)                               */
  D2A[21] = 2.32597e-13;
/* D2A(22) = d^2 A(32) / dV(18)dV(25)                               */
  D2A[22] = 1.89006e-13;
/* D2A(23) = d^2 A(33) / dV(14)dV(25)                               */
  D2A[23] = 6.27341e-12;
/* D2A(24) = d^2 A(37) / dV(26)dV(28)                               */
  D2A[24] = 9.87868e-12;
/* D2A(25) = d^2 A(39) / dV(26)dV(32)                               */
  D2A[25] = 3.63979e-11;
/* D2A(26) = d^2 A(40) / dV(26)dV(32)                               */
  D2A[26] = 6.35777e-12;
/* D2A(27) = d^2 A(41) / dV(16)dV(26)                               */
  D2A[27] = 1.89901e-13;
/* D2A(28) = d^2 A(42) / dV(27)dV(31)                               */
  D2A[28] = 4.00904e-11;
/* D2A(29) = d^2 A(43) / dV(25)dV(27)                               */
  D2A[29] = 1.80823e-11;
/* D2A(30) = d^2 A(44) / dV(25)dV(27)                               */
  D2A[30] = 0;
/* D2A(31) = d^2 A(45) / dV(27)dV(32)                               */
  D2A[31] = 8.71828e-12;
/* D2A(32) = d^2 A(46) / dV(27)dV(29)                               */
  D2A[32] = 2.12738e-11;
/* D2A(33) = d^2 A(47) / dV(27)dV(33)                               */
  D2A[33] = 2.88645e-14;
/* D2A(34) = d^2 A(48)/{dV(27)dV(27)}                               */
  D2A[34] = 1.20131e-15*2;
/* D2A(35) = d^2 A(49)/{dV(27)dV(27)}                               */
  D2A[35] = 1.17478e-15*2;
/* D2A(36) = d^2 A(50)/{dV(27)dV(27)}                               */
  D2A[36] = 1.37988e-15*2;
/* D2A(37) = d^2 A(51)/{dV(27)dV(27)}                               */
  D2A[37] = 3.33034e-15*2;
/* D2A(38) = d^2 A(54) / dV(15)dV(25)                               */
  D2A[38] = 6.10068e-13;
/* D2A(39) = d^2 A(55) / dV(17)dV(25)                               */
  D2A[39] = 3.78181e-13;
/* D2A(40) = d^2 A(56) / dV(21)dV(31)                               */
  D2A[40] = 1.05517e-13;
/* D2A(41) = d^2 A(57) / dV(21)dV(25)                               */
  D2A[41] = 3.02111e-13;
/* D2A(42) = d^2 A(58) / dV(21)dV(26)                               */
  D2A[42] = 1.31924e-11;
/* D2A(43) = d^2 A(60) / dV(24)dV(28)                               */
  D2A[43] = 6.18551e-13;
/* D2A(44) = d^2 A(61) / dV(24)dV(32)                               */
  D2A[44] = 1.24964e-12;
/* D2A(45) = d^2 A(62) / dV(23)dV(24)                               */
  D2A[45] = 6.18551e-13;
/* D2A(46) = d^2 A(63) / dV(30)dV(31)                               */
  D2A[46] = 4.99054e-11;
/* D2A(47) = d^2 A(64) / dV(30)dV(32)                               */
  D2A[47] = 4.91828e-11;
/* D2A(48) = d^2 A(65) / dV(29)dV(30)                               */
  D2A[48] = 2.58334e-11;
/* D2A(49) = d^2 A(66) / dV(30)dV(33)                               */
  D2A[49] = 7.68422e-14;
/* D2A(50) = d^2 A(67) / dV(27)dV(30)                               */
  D2A[50] = 9.49778e-12;
/* D2A(51) = d^2 A(68) / dV(27)dV(30)                               */
  D2A[51] = 7.21345e-12;
/* D2A(52) = d^2 A(69) / dV(27)dV(30)                               */
  D2A[52] = 1.17282e-12;
/* D2A(53) = d^2 A(70)/{dV(30)dV(30)}                               */
  D2A[53] = 2.46725e-12*2;
/* D2A(54) = d^2 A(71) / dV(12)dV(25)                               */
  D2A[54] = 1.1e-11;
/* D2A(55) = d^2 A(74) / dV(23)dV(25)                               */
  D2A[55] = 1e-11;
/* D2A(56) = d^2 A(75) / dV(23)dV(31)                               */
  D2A[56] = 4.50123e-14;
/* D2A(57) = d^2 A(77) / dV(23)dV(26)                               */
  D2A[57] = 7.15352e-11;
/* D2A(58) = d^2 A(81) / dV(20)dV(29)                               */
  D2A[58] = 8.85199e-12;
/* D2A(59) = d^2 A(82) / dV(20)dV(32)                               */
  D2A[59] = 1.04438e-11;
/* D2A(60) = d^2 A(83) / dV(13)dV(25)                               */
  D2A[60] = 6.18205e-12;

/* Computation of the Jacobian derivative                           */
/* HESS(0) = d^2 Vdot(1)/{dV(21)dV(26)} = d^2 Vdot(1)/{dV(26)dV(21)} */
  HESS[0] = D2A[42];
/* HESS(1) = d^2 Vdot(1)/{dV(27)dV(27)} = d^2 Vdot(1)/{dV(27)dV(27)} */
  HESS[1] = D2A[36];
/* HESS(2) = d^2 Vdot(2)/{dV(27)dV(27)} = d^2 Vdot(2)/{dV(27)dV(27)} */
  HESS[2] = D2A[37];
/* HESS(3) = d^2 Vdot(3)/{dV(27)dV(27)} = d^2 Vdot(3)/{dV(27)dV(27)} */
  HESS[3] = D2A[35];
/* HESS(4) = d^2 Vdot(3)/{dV(27)dV(30)} = d^2 Vdot(3)/{dV(30)dV(27)} */
  HESS[4] = D2A[51];
/* HESS(5) = d^2 Vdot(4)/{dV(27)dV(27)} = d^2 Vdot(4)/{dV(27)dV(27)} */
  HESS[5] = D2A[34];
/* HESS(6) = d^2 Vdot(4)/{dV(27)dV(30)} = d^2 Vdot(4)/{dV(30)dV(27)} */
  HESS[6] = D2A[50];
/* HESS(7) = d^2 Vdot(5)/{dV(27)dV(30)} = d^2 Vdot(5)/{dV(30)dV(27)} */
  HESS[7] = D2A[52];
/* HESS(8) = d^2 Vdot(6)/{dV(30)dV(32)} = d^2 Vdot(6)/{dV(32)dV(30)} */
  HESS[8] = D2A[47];
/* HESS(9) = d^2 Vdot(7)/{dV(30)dV(33)} = d^2 Vdot(7)/{dV(33)dV(30)} */
  HESS[9] = D2A[49];
/* HESS(10) = d^2 Vdot(8)/{dV(23)dV(24)} = d^2 Vdot(8)/{dV(24)dV(23)} */
  HESS[10] = D2A[45];
/* HESS(11) = d^2 Vdot(8)/{dV(23)dV(25)} = d^2 Vdot(8)/{dV(25)dV(23)} */
  HESS[11] = D2A[55];
/* HESS(12) = d^2 Vdot(8)/{dV(23)dV(26)} = d^2 Vdot(8)/{dV(26)dV(23)} */
  HESS[12] = D2A[57];
/* HESS(13) = d^2 Vdot(8)/{dV(23)dV(31)} = d^2 Vdot(8)/{dV(31)dV(23)} */
  HESS[13] = D2A[56];
/* HESS(14) = d^2 Vdot(9)/{dV(20)dV(29)} = d^2 Vdot(9)/{dV(29)dV(20)} */
  HESS[14] = D2A[58];
/* HESS(15) = d^2 Vdot(10)/{dV(10)dV(28)} = d^2 Vdot(10)/{dV(28)dV(10)} */
  HESS[15] = -D2A[1];
/* HESS(16) = d^2 Vdot(11)/{dV(22)dV(33)} = d^2 Vdot(11)/{dV(33)dV(22)} */
  HESS[16] = D2A[21];
/* HESS(17) = d^2 Vdot(12)/{dV(12)dV(25)} = d^2 Vdot(12)/{dV(25)dV(12)} */
  HESS[17] = -D2A[54];
/* HESS(18) = d^2 Vdot(12)/{dV(23)dV(24)} = d^2 Vdot(12)/{dV(24)dV(23)} */
  HESS[18] = D2A[45];
/* HESS(19) = d^2 Vdot(12)/{dV(24)dV(32)} = d^2 Vdot(12)/{dV(32)dV(24)} */
  HESS[19] = D2A[44];
/* HESS(20) = d^2 Vdot(13)/{dV(13)dV(25)} = d^2 Vdot(13)/{dV(25)dV(13)} */
  HESS[20] = -D2A[60];
/* HESS(21) = d^2 Vdot(13)/{dV(20)dV(32)} = d^2 Vdot(13)/{dV(32)dV(20)} */
  HESS[21] = D2A[59];
/* HESS(22) = d^2 Vdot(14)/{dV(14)dV(25)} = d^2 Vdot(14)/{dV(25)dV(14)} */
  HESS[22] = -D2A[23];
/* HESS(23) = d^2 Vdot(14)/{dV(32)dV(33)} = d^2 Vdot(14)/{dV(33)dV(32)} */
  HESS[23] = D2A[18];
/* HESS(24) = d^2 Vdot(15)/{dV(15)dV(25)} = d^2 Vdot(15)/{dV(25)dV(15)} */
  HESS[24] = -D2A[38];
/* HESS(25) = d^2 Vdot(15)/{dV(16)dV(26)} = d^2 Vdot(15)/{dV(26)dV(16)} */
  HESS[25] = D2A[27];
/* HESS(26) = d^2 Vdot(15)/{dV(23)dV(26)} = d^2 Vdot(15)/{dV(26)dV(23)} */
  HESS[26] = D2A[57];
/* HESS(27) = d^2 Vdot(15)/{dV(25)dV(27)} = d^2 Vdot(15)/{dV(27)dV(25)} */
  HESS[27] = D2A[30];
/* HESS(28) = d^2 Vdot(15)/{dV(26)dV(32)} = d^2 Vdot(15)/{dV(32)dV(26)} */
  HESS[28] = D2A[25];
/* HESS(29) = d^2 Vdot(16)/{dV(16)dV(25)} = d^2 Vdot(16)/{dV(25)dV(16)} */
  HESS[29] = -D2A[12];
/* HESS(30) = d^2 Vdot(16)/{dV(16)dV(26)} = d^2 Vdot(16)/{dV(26)dV(16)} */
  HESS[30] = -D2A[27];
/* HESS(31) = d^2 Vdot(16)/{dV(32)dV(32)} = d^2 Vdot(16)/{dV(32)dV(32)} */
  HESS[31] = D2A[10]+D2A[11];
/* HESS(32) = d^2 Vdot(17)/{dV(17)dV(25)} = d^2 Vdot(17)/{dV(25)dV(17)} */
  HESS[32] = -D2A[39];
/* HESS(33) = d^2 Vdot(17)/{dV(21)dV(25)} = d^2 Vdot(17)/{dV(25)dV(21)} */
  HESS[33] = D2A[41];
/* HESS(34) = d^2 Vdot(17)/{dV(27)dV(32)} = d^2 Vdot(17)/{dV(32)dV(27)} */
  HESS[34] = D2A[31];
/* HESS(35) = d^2 Vdot(18)/{dV(18)dV(25)} = d^2 Vdot(18)/{dV(25)dV(18)} */
  HESS[35] = -D2A[22];
/* HESS(36) = d^2 Vdot(18)/{dV(25)dV(33)} = d^2 Vdot(18)/{dV(33)dV(25)} */
  HESS[36] = D2A[17];
/* HESS(37) = d^2 Vdot(19)/{dV(19)dV(28)} = d^2 Vdot(19)/{dV(28)dV(19)} */
  HESS[37] = -D2A[2];
/* HESS(38) = d^2 Vdot(19)/{dV(19)dV(32)} = d^2 Vdot(19)/{dV(32)dV(19)} */
  HESS[38] = -D2A[8];
/* HESS(39) = d^2 Vdot(19)/{dV(25)dV(31)} = d^2 Vdot(19)/{dV(31)dV(25)} */
  HESS[39] = D2A[4];
/* HESS(40) = d^2 Vdot(20)/{dV(13)dV(25)} = d^2 Vdot(20)/{dV(25)dV(13)} */
  HESS[40] = D2A[60];
/* HESS(41) = d^2 Vdot(20)/{dV(20)dV(29)} = d^2 Vdot(20)/{dV(29)dV(20)} */
  HESS[41] = -D2A[58];
/* HESS(42) = d^2 Vdot(20)/{dV(20)dV(32)} = d^2 Vdot(20)/{dV(32)dV(20)} */
  HESS[42] = -D2A[59];
/* HESS(43) = d^2 Vdot(21)/{dV(21)dV(25)} = d^2 Vdot(21)/{dV(25)dV(21)} */
  HESS[43] = -D2A[41];
/* HESS(44) = d^2 Vdot(21)/{dV(21)dV(26)} = d^2 Vdot(21)/{dV(26)dV(21)} */
  HESS[44] = -D2A[42];
/* HESS(45) = d^2 Vdot(21)/{dV(21)dV(31)} = d^2 Vdot(21)/{dV(31)dV(21)} */
  HESS[45] = -D2A[40];
/* HESS(46) = d^2 Vdot(21)/{dV(27)dV(33)} = d^2 Vdot(21)/{dV(33)dV(27)} */
  HESS[46] = D2A[33];
/* HESS(47) = d^2 Vdot(22)/{dV(18)dV(25)} = d^2 Vdot(22)/{dV(25)dV(18)} */
  HESS[47] = D2A[22];
/* HESS(48) = d^2 Vdot(22)/{dV(21)dV(25)} = d^2 Vdot(22)/{dV(25)dV(21)} */
  HESS[48] = D2A[41];
/* HESS(49) = d^2 Vdot(22)/{dV(21)dV(26)} = d^2 Vdot(22)/{dV(26)dV(21)} */
  HESS[49] = D2A[42];
/* HESS(50) = d^2 Vdot(22)/{dV(21)dV(31)} = d^2 Vdot(22)/{dV(31)dV(21)} */
  HESS[50] = D2A[40];
/* HESS(51) = d^2 Vdot(22)/{dV(22)dV(29)} = d^2 Vdot(22)/{dV(29)dV(22)} */
  HESS[51] = -D2A[20];
/* HESS(52) = d^2 Vdot(22)/{dV(22)dV(31)} = d^2 Vdot(22)/{dV(31)dV(22)} */
  HESS[52] = -D2A[19];
/* HESS(53) = d^2 Vdot(22)/{dV(22)dV(33)} = d^2 Vdot(22)/{dV(33)dV(22)} */
  HESS[53] = -D2A[21];
/* HESS(54) = d^2 Vdot(22)/{dV(28)dV(33)} = d^2 Vdot(22)/{dV(33)dV(28)} */
  HESS[54] = D2A[16];
/* HESS(55) = d^2 Vdot(23)/{dV(23)dV(24)} = d^2 Vdot(23)/{dV(24)dV(23)} */
  HESS[55] = -D2A[45];
/* HESS(56) = d^2 Vdot(23)/{dV(23)dV(25)} = d^2 Vdot(23)/{dV(25)dV(23)} */
  HESS[56] = -D2A[55];
/* HESS(57) = d^2 Vdot(23)/{dV(23)dV(26)} = d^2 Vdot(23)/{dV(26)dV(23)} */
  HESS[57] = -D2A[57];
/* HESS(58) = d^2 Vdot(23)/{dV(23)dV(31)} = d^2 Vdot(23)/{dV(31)dV(23)} */
  HESS[58] = -D2A[56];
/* HESS(59) = d^2 Vdot(24)/{dV(12)dV(25)} = d^2 Vdot(24)/{dV(25)dV(12)} */
  HESS[59] = D2A[54];
/* HESS(60) = d^2 Vdot(24)/{dV(23)dV(24)} = d^2 Vdot(24)/{dV(24)dV(23)} */
  HESS[60] = -D2A[45];
/* HESS(61) = d^2 Vdot(24)/{dV(24)dV(28)} = d^2 Vdot(24)/{dV(28)dV(24)} */
  HESS[61] = -D2A[43];
/* HESS(62) = d^2 Vdot(24)/{dV(24)dV(32)} = d^2 Vdot(24)/{dV(32)dV(24)} */
  HESS[62] = -D2A[44];
/* HESS(63) = d^2 Vdot(24)/{dV(27)dV(30)} = d^2 Vdot(24)/{dV(30)dV(27)} */
  HESS[63] = D2A[50]+D2A[51];
/* HESS(64) = d^2 Vdot(24)/{dV(29)dV(30)} = d^2 Vdot(24)/{dV(30)dV(29)} */
  HESS[64] = D2A[48];
/* HESS(65) = d^2 Vdot(24)/{dV(30)dV(30)} = d^2 Vdot(24)/{dV(30)dV(30)} */
  HESS[65] = 2*D2A[53];
/* HESS(66) = d^2 Vdot(24)/{dV(30)dV(31)} = d^2 Vdot(24)/{dV(31)dV(30)} */
  HESS[66] = D2A[46];
/* HESS(67) = d^2 Vdot(25)/{dV(12)dV(25)} = d^2 Vdot(25)/{dV(25)dV(12)} */
  HESS[67] = -D2A[54];
/* HESS(68) = d^2 Vdot(25)/{dV(13)dV(25)} = d^2 Vdot(25)/{dV(25)dV(13)} */
  HESS[68] = -D2A[60];
/* HESS(69) = d^2 Vdot(25)/{dV(14)dV(25)} = d^2 Vdot(25)/{dV(25)dV(14)} */
  HESS[69] = -D2A[23];
/* HESS(70) = d^2 Vdot(25)/{dV(15)dV(25)} = d^2 Vdot(25)/{dV(25)dV(15)} */
  HESS[70] = -D2A[38];
/* HESS(71) = d^2 Vdot(25)/{dV(16)dV(25)} = d^2 Vdot(25)/{dV(25)dV(16)} */
  HESS[71] = -D2A[12];
/* HESS(72) = d^2 Vdot(25)/{dV(17)dV(25)} = d^2 Vdot(25)/{dV(25)dV(17)} */
  HESS[72] = -D2A[39];
/* HESS(73) = d^2 Vdot(25)/{dV(18)dV(25)} = d^2 Vdot(25)/{dV(25)dV(18)} */
  HESS[73] = -D2A[22];
/* HESS(74) = d^2 Vdot(25)/{dV(19)dV(28)} = d^2 Vdot(25)/{dV(28)dV(19)} */
  HESS[74] = D2A[2];
/* HESS(75) = d^2 Vdot(25)/{dV(19)dV(32)} = d^2 Vdot(25)/{dV(32)dV(19)} */
  HESS[75] = 2*D2A[8];
/* HESS(76) = d^2 Vdot(25)/{dV(21)dV(25)} = d^2 Vdot(25)/{dV(25)dV(21)} */
  HESS[76] = -D2A[41];
/* HESS(77) = d^2 Vdot(25)/{dV(23)dV(25)} = d^2 Vdot(25)/{dV(25)dV(23)} */
  HESS[77] = -D2A[55];
/* HESS(78) = d^2 Vdot(25)/{dV(23)dV(31)} = d^2 Vdot(25)/{dV(31)dV(23)} */
  HESS[78] = D2A[56];
/* HESS(79) = d^2 Vdot(25)/{dV(25)dV(25)} = d^2 Vdot(25)/{dV(25)dV(25)} */
  HESS[79] = -2*D2A[5];
/* HESS(80) = d^2 Vdot(25)/{dV(25)dV(27)} = d^2 Vdot(25)/{dV(27)dV(25)} */
  HESS[80] = -D2A[29]-D2A[30];
/* HESS(81) = d^2 Vdot(25)/{dV(25)dV(28)} = d^2 Vdot(25)/{dV(28)dV(25)} */
  HESS[81] = -D2A[3];
/* HESS(82) = d^2 Vdot(25)/{dV(25)dV(31)} = d^2 Vdot(25)/{dV(31)dV(25)} */
  HESS[82] = -D2A[4];
/* HESS(83) = d^2 Vdot(25)/{dV(25)dV(32)} = d^2 Vdot(25)/{dV(32)dV(25)} */
  HESS[83] = -D2A[9];
/* HESS(84) = d^2 Vdot(25)/{dV(25)dV(33)} = d^2 Vdot(25)/{dV(33)dV(25)} */
  HESS[84] = -D2A[17];
/* HESS(85) = d^2 Vdot(25)/{dV(26)dV(32)} = d^2 Vdot(25)/{dV(32)dV(26)} */
  HESS[85] = D2A[26];
/* HESS(86) = d^2 Vdot(25)/{dV(28)dV(32)} = d^2 Vdot(25)/{dV(32)dV(28)} */
  HESS[86] = D2A[7];
/* HESS(87) = d^2 Vdot(25)/{dV(29)dV(32)} = d^2 Vdot(25)/{dV(32)dV(29)} */
  HESS[87] = D2A[14];
/* HESS(88) = d^2 Vdot(25)/{dV(31)dV(32)} = d^2 Vdot(25)/{dV(32)dV(31)} */
  HESS[88] = D2A[6];
/* HESS(89) = d^2 Vdot(26)/{dV(15)dV(25)} = d^2 Vdot(26)/{dV(25)dV(15)} */
  HESS[89] = D2A[38];
/* HESS(90) = d^2 Vdot(26)/{dV(16)dV(26)} = d^2 Vdot(26)/{dV(26)dV(16)} */
  HESS[90] = -D2A[27];
/* HESS(91) = d^2 Vdot(26)/{dV(21)dV(26)} = d^2 Vdot(26)/{dV(26)dV(21)} */
  HESS[91] = -D2A[42];
/* HESS(92) = d^2 Vdot(26)/{dV(23)dV(26)} = d^2 Vdot(26)/{dV(26)dV(23)} */
  HESS[92] = -D2A[57];
/* HESS(93) = d^2 Vdot(26)/{dV(25)dV(27)} = d^2 Vdot(26)/{dV(27)dV(25)} */
  HESS[93] = D2A[29];
/* HESS(94) = d^2 Vdot(26)/{dV(26)dV(28)} = d^2 Vdot(26)/{dV(28)dV(26)} */
  HESS[94] = -D2A[24];
/* HESS(95) = d^2 Vdot(26)/{dV(26)dV(32)} = d^2 Vdot(26)/{dV(32)dV(26)} */
  HESS[95] = -D2A[25]-D2A[26];
/* HESS(96) = d^2 Vdot(26)/{dV(27)dV(27)} = d^2 Vdot(26)/{dV(27)dV(27)} */
  HESS[96] = D2A[34]+D2A[35];
/* HESS(97) = d^2 Vdot(26)/{dV(27)dV(29)} = d^2 Vdot(26)/{dV(29)dV(27)} */
  HESS[97] = D2A[32];
/* HESS(98) = d^2 Vdot(26)/{dV(27)dV(31)} = d^2 Vdot(26)/{dV(31)dV(27)} */
  HESS[98] = D2A[28];
/* HESS(99) = d^2 Vdot(27)/{dV(17)dV(25)} = d^2 Vdot(27)/{dV(25)dV(17)} */
  HESS[99] = D2A[39];
/* HESS(100) = d^2 Vdot(27)/{dV(21)dV(31)} = d^2 Vdot(27)/{dV(31)dV(21)} */
  HESS[100] = D2A[40];
/* HESS(101) = d^2 Vdot(27)/{dV(25)dV(27)} = d^2 Vdot(27)/{dV(27)dV(25)} */
  HESS[101] = -D2A[29]-D2A[30];
/* HESS(102) = d^2 Vdot(27)/{dV(26)dV(28)} = d^2 Vdot(27)/{dV(28)dV(26)} */
  HESS[102] = D2A[24];
/* HESS(103) = d^2 Vdot(27)/{dV(26)dV(32)} = d^2 Vdot(27)/{dV(32)dV(26)} */
  HESS[103] = D2A[26];
/* HESS(104) = d^2 Vdot(27)/{dV(27)dV(27)} = d^2 Vdot(27)/{dV(27)dV(27)} */
  HESS[104] = -2*D2A[34]-2*D2A[35]-2*D2A[36]-2*D2A[37];
/* HESS(105) = d^2 Vdot(27)/{dV(27)dV(29)} = d^2 Vdot(27)/{dV(29)dV(27)} */
  HESS[105] = -D2A[32];
/* HESS(106) = d^2 Vdot(27)/{dV(27)dV(30)} = d^2 Vdot(27)/{dV(30)dV(27)} */
  HESS[106] = -D2A[50]-D2A[51]-D2A[52];
/* HESS(107) = d^2 Vdot(27)/{dV(27)dV(31)} = d^2 Vdot(27)/{dV(31)dV(27)} */
  HESS[107] = -D2A[28];
/* HESS(108) = d^2 Vdot(27)/{dV(27)dV(32)} = d^2 Vdot(27)/{dV(32)dV(27)} */
  HESS[108] = -D2A[31];
/* HESS(109) = d^2 Vdot(27)/{dV(27)dV(33)} = d^2 Vdot(27)/{dV(33)dV(27)} */
  HESS[109] = -D2A[33];
/* HESS(110) = d^2 Vdot(28)/{dV(10)dV(28)} = d^2 Vdot(28)/{dV(28)dV(10)} */
  HESS[110] = -D2A[1];
/* HESS(111) = d^2 Vdot(28)/{dV(19)dV(28)} = d^2 Vdot(28)/{dV(28)dV(19)} */
  HESS[111] = -D2A[2];
/* HESS(112) = d^2 Vdot(28)/{dV(24)dV(28)} = d^2 Vdot(28)/{dV(28)dV(24)} */
  HESS[112] = -D2A[43];
/* HESS(113) = d^2 Vdot(28)/{dV(25)dV(28)} = d^2 Vdot(28)/{dV(28)dV(25)} */
  HESS[113] = -D2A[3];
/* HESS(114) = d^2 Vdot(28)/{dV(26)dV(28)} = d^2 Vdot(28)/{dV(28)dV(26)} */
  HESS[114] = -D2A[24];
/* HESS(115) = d^2 Vdot(28)/{dV(28)dV(29)} = d^2 Vdot(28)/{dV(29)dV(28)} */
  HESS[115] = -D2A[13];
/* HESS(116) = d^2 Vdot(28)/{dV(28)dV(31)} = d^2 Vdot(28)/{dV(31)dV(28)} */
  HESS[116] = -D2A[0];
/* HESS(117) = d^2 Vdot(28)/{dV(28)dV(32)} = d^2 Vdot(28)/{dV(32)dV(28)} */
  HESS[117] = -D2A[7];
/* HESS(118) = d^2 Vdot(28)/{dV(28)dV(33)} = d^2 Vdot(28)/{dV(33)dV(28)} */
  HESS[118] = -D2A[16];
/* HESS(119) = d^2 Vdot(29)/{dV(20)dV(29)} = d^2 Vdot(29)/{dV(29)dV(20)} */
  HESS[119] = -D2A[58];
/* HESS(120) = d^2 Vdot(29)/{dV(22)dV(29)} = d^2 Vdot(29)/{dV(29)dV(22)} */
  HESS[120] = -D2A[20];
/* HESS(121) = d^2 Vdot(29)/{dV(27)dV(29)} = d^2 Vdot(29)/{dV(29)dV(27)} */
  HESS[121] = -D2A[32];
/* HESS(122) = d^2 Vdot(29)/{dV(28)dV(29)} = d^2 Vdot(29)/{dV(29)dV(28)} */
  HESS[122] = -D2A[13];
/* HESS(123) = d^2 Vdot(29)/{dV(29)dV(30)} = d^2 Vdot(29)/{dV(30)dV(29)} */
  HESS[123] = -D2A[48];
/* HESS(124) = d^2 Vdot(29)/{dV(29)dV(32)} = d^2 Vdot(29)/{dV(32)dV(29)} */
  HESS[124] = -D2A[14];
/* HESS(125) = d^2 Vdot(29)/{dV(31)dV(33)} = d^2 Vdot(29)/{dV(33)dV(31)} */
  HESS[125] = D2A[15];
/* HESS(126) = d^2 Vdot(30)/{dV(24)dV(28)} = d^2 Vdot(30)/{dV(28)dV(24)} */
  HESS[126] = D2A[43];
/* HESS(127) = d^2 Vdot(30)/{dV(27)dV(30)} = d^2 Vdot(30)/{dV(30)dV(27)} */
  HESS[127] = -D2A[50]-D2A[51]-D2A[52];
/* HESS(128) = d^2 Vdot(30)/{dV(29)dV(30)} = d^2 Vdot(30)/{dV(30)dV(29)} */
  HESS[128] = -D2A[48];
/* HESS(129) = d^2 Vdot(30)/{dV(30)dV(30)} = d^2 Vdot(30)/{dV(30)dV(30)} */
  HESS[129] = -2*D2A[53];
/* HESS(130) = d^2 Vdot(30)/{dV(30)dV(31)} = d^2 Vdot(30)/{dV(31)dV(30)} */
  HESS[130] = -D2A[46];
/* HESS(131) = d^2 Vdot(30)/{dV(30)dV(32)} = d^2 Vdot(30)/{dV(32)dV(30)} */
  HESS[131] = -D2A[47];
/* HESS(132) = d^2 Vdot(30)/{dV(30)dV(33)} = d^2 Vdot(30)/{dV(33)dV(30)} */
  HESS[132] = -D2A[49];
/* HESS(133) = d^2 Vdot(31)/{dV(21)dV(31)} = d^2 Vdot(31)/{dV(31)dV(21)} */
  HESS[133] = -D2A[40];
/* HESS(134) = d^2 Vdot(31)/{dV(22)dV(31)} = d^2 Vdot(31)/{dV(31)dV(22)} */
  HESS[134] = -D2A[19];
/* HESS(135) = d^2 Vdot(31)/{dV(23)dV(31)} = d^2 Vdot(31)/{dV(31)dV(23)} */
  HESS[135] = -D2A[56];
/* HESS(136) = d^2 Vdot(31)/{dV(25)dV(25)} = d^2 Vdot(31)/{dV(25)dV(25)} */
  HESS[136] = D2A[5];
/* HESS(137) = d^2 Vdot(31)/{dV(25)dV(31)} = d^2 Vdot(31)/{dV(31)dV(25)} */
  HESS[137] = -D2A[4];
/* HESS(138) = d^2 Vdot(31)/{dV(27)dV(31)} = d^2 Vdot(31)/{dV(31)dV(27)} */
  HESS[138] = -D2A[28];
/* HESS(139) = d^2 Vdot(31)/{dV(28)dV(31)} = d^2 Vdot(31)/{dV(31)dV(28)} */
  HESS[139] = -D2A[0];
/* HESS(140) = d^2 Vdot(31)/{dV(30)dV(31)} = d^2 Vdot(31)/{dV(31)dV(30)} */
  HESS[140] = -D2A[46];
/* HESS(141) = d^2 Vdot(31)/{dV(31)dV(32)} = d^2 Vdot(31)/{dV(32)dV(31)} */
  HESS[141] = -D2A[6];
/* HESS(142) = d^2 Vdot(31)/{dV(31)dV(33)} = d^2 Vdot(31)/{dV(33)dV(31)} */
  HESS[142] = -D2A[15];
/* HESS(143) = d^2 Vdot(32)/{dV(16)dV(25)} = d^2 Vdot(32)/{dV(25)dV(16)} */
  HESS[143] = D2A[12];
/* HESS(144) = d^2 Vdot(32)/{dV(16)dV(26)} = d^2 Vdot(32)/{dV(26)dV(16)} */
  HESS[144] = D2A[27];
/* HESS(145) = d^2 Vdot(32)/{dV(19)dV(32)} = d^2 Vdot(32)/{dV(32)dV(19)} */
  HESS[145] = -D2A[8];
/* HESS(146) = d^2 Vdot(32)/{dV(20)dV(32)} = d^2 Vdot(32)/{dV(32)dV(20)} */
  HESS[146] = -D2A[59];
/* HESS(147) = d^2 Vdot(32)/{dV(24)dV(32)} = d^2 Vdot(32)/{dV(32)dV(24)} */
  HESS[147] = -D2A[44];
/* HESS(148) = d^2 Vdot(32)/{dV(25)dV(27)} = d^2 Vdot(32)/{dV(27)dV(25)} */
  HESS[148] = D2A[29];
/* HESS(149) = d^2 Vdot(32)/{dV(25)dV(28)} = d^2 Vdot(32)/{dV(28)dV(25)} */
  HESS[149] = D2A[3];
/* HESS(150) = d^2 Vdot(32)/{dV(25)dV(32)} = d^2 Vdot(32)/{dV(32)dV(25)} */
  HESS[150] = -D2A[9];
/* HESS(151) = d^2 Vdot(32)/{dV(26)dV(32)} = d^2 Vdot(32)/{dV(32)dV(26)} */
  HESS[151] = -D2A[25]-D2A[26];
/* HESS(152) = d^2 Vdot(32)/{dV(27)dV(32)} = d^2 Vdot(32)/{dV(32)dV(27)} */
  HESS[152] = -D2A[31];
/* HESS(153) = d^2 Vdot(32)/{dV(28)dV(32)} = d^2 Vdot(32)/{dV(32)dV(28)} */
  HESS[153] = -D2A[7];
/* HESS(154) = d^2 Vdot(32)/{dV(29)dV(32)} = d^2 Vdot(32)/{dV(32)dV(29)} */
  HESS[154] = -D2A[14];
/* HESS(155) = d^2 Vdot(32)/{dV(30)dV(32)} = d^2 Vdot(32)/{dV(32)dV(30)} */
  HESS[155] = -D2A[47];
/* HESS(156) = d^2 Vdot(32)/{dV(31)dV(32)} = d^2 Vdot(32)/{dV(32)dV(31)} */
  HESS[156] = -D2A[6];
/* HESS(157) = d^2 Vdot(32)/{dV(32)dV(32)} = d^2 Vdot(32)/{dV(32)dV(32)} */
  HESS[157] = -2*D2A[10]-2*D2A[11];
/* HESS(158) = d^2 Vdot(32)/{dV(32)dV(33)} = d^2 Vdot(32)/{dV(33)dV(32)} */
  HESS[158] = -D2A[18];
/* HESS(159) = d^2 Vdot(33)/{dV(14)dV(25)} = d^2 Vdot(33)/{dV(25)dV(14)} */
  HESS[159] = D2A[23];
/* HESS(160) = d^2 Vdot(33)/{dV(20)dV(29)} = d^2 Vdot(33)/{dV(29)dV(20)} */
  HESS[160] = D2A[58];
/* HESS(161) = d^2 Vdot(33)/{dV(22)dV(29)} = d^2 Vdot(33)/{dV(29)dV(22)} */
  HESS[161] = 2*D2A[20];
/* HESS(162) = d^2 Vdot(33)/{dV(22)dV(31)} = d^2 Vdot(33)/{dV(31)dV(22)} */
  HESS[162] = D2A[19];
/* HESS(163) = d^2 Vdot(33)/{dV(22)dV(33)} = d^2 Vdot(33)/{dV(33)dV(22)} */
  HESS[163] = -D2A[21];
/* HESS(164) = d^2 Vdot(33)/{dV(25)dV(33)} = d^2 Vdot(33)/{dV(33)dV(25)} */
  HESS[164] = -D2A[17];
/* HESS(165) = d^2 Vdot(33)/{dV(27)dV(29)} = d^2 Vdot(33)/{dV(29)dV(27)} */
  HESS[165] = D2A[32];
/* HESS(166) = d^2 Vdot(33)/{dV(27)dV(33)} = d^2 Vdot(33)/{dV(33)dV(27)} */
  HESS[166] = -D2A[33];
/* HESS(167) = d^2 Vdot(33)/{dV(28)dV(29)} = d^2 Vdot(33)/{dV(29)dV(28)} */
  HESS[167] = D2A[13];
/* HESS(168) = d^2 Vdot(33)/{dV(28)dV(33)} = d^2 Vdot(33)/{dV(33)dV(28)} */
  HESS[168] = -D2A[16];
/* HESS(169) = d^2 Vdot(33)/{dV(29)dV(30)} = d^2 Vdot(33)/{dV(30)dV(29)} */
  HESS[169] = D2A[48];
/* HESS(170) = d^2 Vdot(33)/{dV(29)dV(32)} = d^2 Vdot(33)/{dV(32)dV(29)} */
  HESS[170] = D2A[14];
/* HESS(171) = d^2 Vdot(33)/{dV(30)dV(33)} = d^2 Vdot(33)/{dV(33)dV(30)} */
  HESS[171] = -D2A[49];
/* HESS(172) = d^2 Vdot(33)/{dV(31)dV(33)} = d^2 Vdot(33)/{dV(33)dV(31)} */
  HESS[172] = -D2A[15];
/* HESS(173) = d^2 Vdot(33)/{dV(32)dV(33)} = d^2 Vdot(33)/{dV(33)dV(32)} */
  HESS[173] = -D2A[18];
}

/* End of Hessian function                                          */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* HessTR_Vec - Hessian transposed times user vectors               */
/*   Arguments :                                                    */
/*      HESS      - Hessian of Var (i.e. the 3-tensor d Jac / d Var) */
/*      U1        - User vector                                     */
/*      U2        - User vector                                     */
/*      HTU       - Transposed Hessian times user vectors: (Hess x U2)^T * U1 = [d (Jac^T*U1)/d Var] * U2  */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

void HessTR_Vec( 
  float HESS[],                          /* Hessian of Var (i.e. the 3-tensor d Jac / d Var) */
  float U1[],                            /* User vector */
  float U2[],                            /* User vector */
  float HTU[]                            /* Transposed Hessian times user vectors: (Hess x U2)^T * U1 = [d (Jac^T*U1)/d Var] * U2  */
)
{
/* Compute the vector HTU =(Hess x U2)^T * U1 = d (Jac^T*U1)/d Var * U2  */
  HTU[0] = 0;
  HTU[1] = 0;
  HTU[2] = 0;
  HTU[3] = 0;
  HTU[4] = 0;
  HTU[5] = 0;
  HTU[6] = 0;
  HTU[7] = 0;
  HTU[8] = 0;
  HTU[9] = 0;
  HTU[10] = HESS[15]*(U1[10]*U2[28])+HESS[110]*(U1[28]*U2[28]);
  HTU[11] = 0;
  HTU[12] = HESS[17]*(U1[12]*U2[25])+HESS[59]*(U1[24]*U2[25])+HESS[67]
           *(U1[25]*U2[25]);
  HTU[13] = HESS[20]*(U1[13]*U2[25])+HESS[40]*(U1[20]*U2[25])+HESS[68]
           *(U1[25]*U2[25]);
  HTU[14] = HESS[22]*(U1[14]*U2[25])+HESS[69]*(U1[25]*U2[25])+HESS[159]
           *(U1[33]*U2[25]);
  HTU[15] = HESS[24]*(U1[15]*U2[25])+HESS[70]*(U1[25]*U2[25])+HESS[89]
           *(U1[26]*U2[25]);
  HTU[16] = HESS[25]*(U1[15]*U2[26])+HESS[29]*(U1[16]*U2[25])+HESS[30]
           *(U1[16]*U2[26])+HESS[71]*(U1[25]*U2[25])+HESS[90]*(U1[26]
           *U2[26])+HESS[143]*(U1[32]*U2[25])+HESS[144]*(U1[32]*U2[26]);
  HTU[17] = HESS[32]*(U1[17]*U2[25])+HESS[72]*(U1[25]*U2[25])+HESS[99]
           *(U1[27]*U2[25]);
  HTU[18] = HESS[35]*(U1[18]*U2[25])+HESS[47]*(U1[22]*U2[25])+HESS[73]
           *(U1[25]*U2[25]);
  HTU[19] = HESS[37]*(U1[19]*U2[28])+HESS[38]*(U1[19]*U2[32])+HESS[74]
           *(U1[25]*U2[28])+HESS[75]*(U1[25]*U2[32])+HESS[111]*(U1[28]
           *U2[28])+HESS[145]*(U1[32]*U2[32]);
  HTU[20] = HESS[14]*(U1[9]*U2[29])+HESS[21]*(U1[13]*U2[32])+HESS[41]
           *(U1[20]*U2[29])+HESS[42]*(U1[20]*U2[32])+HESS[119]*(U1[29]
           *U2[29])+HESS[146]*(U1[32]*U2[32])+HESS[160]*(U1[33]*U2[29]);
  HTU[21] = HESS[0]*(U1[1]*U2[26])+HESS[33]*(U1[17]*U2[25])+HESS[43]
           *(U1[21]*U2[25])+HESS[44]*(U1[21]*U2[26])+HESS[45]*(U1[21]
           *U2[31])+HESS[48]*(U1[22]*U2[25])+HESS[49]*(U1[22]*U2[26])
           +HESS[50]*(U1[22]*U2[31])+HESS[76]*(U1[25]*U2[25])+HESS[91]
           *(U1[26]*U2[26])+HESS[100]*(U1[27]*U2[31])+HESS[133]*(U1[31]
           *U2[31]);
  HTU[22] = HESS[16]*(U1[11]*U2[33])+HESS[51]*(U1[22]*U2[29])+HESS[52]
           *(U1[22]*U2[31])+HESS[53]*(U1[22]*U2[33])+HESS[120]*(U1[29]
           *U2[29])+HESS[134]*(U1[31]*U2[31])+HESS[161]*(U1[33]*U2[29])
           +HESS[162]*(U1[33]*U2[31])+HESS[163]*(U1[33]*U2[33]);
  HTU[23] = HESS[10]*(U1[8]*U2[24])+HESS[11]*(U1[8]*U2[25])+HESS[12]
           *(U1[8]*U2[26])+HESS[13]*(U1[8]*U2[31])+HESS[18]*(U1[12]
           *U2[24])+HESS[26]*(U1[15]*U2[26])+HESS[55]*(U1[23]*U2[24])
           +HESS[56]*(U1[23]*U2[25])+HESS[57]*(U1[23]*U2[26])+HESS[58]
           *(U1[23]*U2[31])+HESS[60]*(U1[24]*U2[24])+HESS[77]*(U1[25]
           *U2[25])+HESS[78]*(U1[25]*U2[31])+HESS[92]*(U1[26]*U2[26])
           +HESS[135]*(U1[31]*U2[31]);
  HTU[24] = HESS[10]*(U1[8]*U2[23])+HESS[18]*(U1[12]*U2[23])+HESS[19]
           *(U1[12]*U2[32])+HESS[55]*(U1[23]*U2[23])+HESS[60]*(U1[24]
           *U2[23])+HESS[61]*(U1[24]*U2[28])+HESS[62]*(U1[24]*U2[32])
           +HESS[112]*(U1[28]*U2[28])+HESS[126]*(U1[30]*U2[28])
           +HESS[147]*(U1[32]*U2[32]);
  HTU[25] = HESS[11]*(U1[8]*U2[23])+HESS[17]*(U1[12]*U2[12])+HESS[20]
           *(U1[13]*U2[13])+HESS[22]*(U1[14]*U2[14])+HESS[24]*(U1[15]
           *U2[15])+HESS[27]*(U1[15]*U2[27])+HESS[29]*(U1[16]*U2[16])
           +HESS[32]*(U1[17]*U2[17])+HESS[33]*(U1[17]*U2[21])+HESS[35]
           *(U1[18]*U2[18])+HESS[36]*(U1[18]*U2[33])+HESS[39]*(U1[19]
           *U2[31])+HESS[40]*(U1[20]*U2[13])+HESS[43]*(U1[21]*U2[21])
           +HESS[47]*(U1[22]*U2[18])+HESS[48]*(U1[22]*U2[21])+HESS[56]
           *(U1[23]*U2[23])+HESS[59]*(U1[24]*U2[12])+HESS[67]*(U1[25]
           *U2[12])+HESS[68]*(U1[25]*U2[13])+HESS[69]*(U1[25]*U2[14])
           +HESS[70]*(U1[25]*U2[15])+HESS[71]*(U1[25]*U2[16])+HESS[72]
           *(U1[25]*U2[17])+HESS[73]*(U1[25]*U2[18])+HESS[76]*(U1[25]
           *U2[21])+HESS[77]*(U1[25]*U2[23])+HESS[79]*(U1[25]*U2[25])
           +HESS[80]*(U1[25]*U2[27])+HESS[81]*(U1[25]*U2[28])+HESS[82]
           *(U1[25]*U2[31])+HESS[83]*(U1[25]*U2[32])+HESS[84]*(U1[25]
           *U2[33])+HESS[89]*(U1[26]*U2[15])+HESS[93]*(U1[26]*U2[27])
           +HESS[99]*(U1[27]*U2[17])+HESS[101]*(U1[27]*U2[27])
           +HESS[113]*(U1[28]*U2[28])+HESS[136]*(U1[31]*U2[25])
           +HESS[137]*(U1[31]*U2[31])+HESS[143]*(U1[32]*U2[16])
           +HESS[148]*(U1[32]*U2[27])+HESS[149]*(U1[32]*U2[28])
           +HESS[150]*(U1[32]*U2[32])+HESS[159]*(U1[33]*U2[14])
           +HESS[164]*(U1[33]*U2[33]);
  HTU[26] = HESS[0]*(U1[1]*U2[21])+HESS[12]*(U1[8]*U2[23])+HESS[25]
           *(U1[15]*U2[16])+HESS[26]*(U1[15]*U2[23])+HESS[28]*(U1[15]
           *U2[32])+HESS[30]*(U1[16]*U2[16])+HESS[44]*(U1[21]*U2[21])
           +HESS[49]*(U1[22]*U2[21])+HESS[57]*(U1[23]*U2[23])+HESS[85]
           *(U1[25]*U2[32])+HESS[90]*(U1[26]*U2[16])+HESS[91]*(U1[26]
           *U2[21])+HESS[92]*(U1[26]*U2[23])+HESS[94]*(U1[26]*U2[28])
           +HESS[95]*(U1[26]*U2[32])+HESS[102]*(U1[27]*U2[28])
           +HESS[103]*(U1[27]*U2[32])+HESS[114]*(U1[28]*U2[28])
           +HESS[144]*(U1[32]*U2[16])+HESS[151]*(U1[32]*U2[32]);
  HTU[27] = HESS[1]*(U1[1]*U2[27])+HESS[2]*(U1[2]*U2[27])+HESS[3]
           *(U1[3]*U2[27])+HESS[4]*(U1[3]*U2[30])+HESS[5]*(U1[4]
           *U2[27])+HESS[6]*(U1[4]*U2[30])+HESS[7]*(U1[5]*U2[30])
           +HESS[27]*(U1[15]*U2[25])+HESS[34]*(U1[17]*U2[32])+HESS[46]
           *(U1[21]*U2[33])+HESS[63]*(U1[24]*U2[30])+HESS[80]*(U1[25]
           *U2[25])+HESS[93]*(U1[26]*U2[25])+HESS[96]*(U1[26]*U2[27])
           +HESS[97]*(U1[26]*U2[29])+HESS[98]*(U1[26]*U2[31])+HESS[101]
           *(U1[27]*U2[25])+HESS[104]*(U1[27]*U2[27])+HESS[105]*(U1[27]
           *U2[29])+HESS[106]*(U1[27]*U2[30])+HESS[107]*(U1[27]*U2[31])
           +HESS[108]*(U1[27]*U2[32])+HESS[109]*(U1[27]*U2[33])
           +HESS[121]*(U1[29]*U2[29])+HESS[127]*(U1[30]*U2[30])
           +HESS[138]*(U1[31]*U2[31])+HESS[148]*(U1[32]*U2[25])
           +HESS[152]*(U1[32]*U2[32])+HESS[165]*(U1[33]*U2[29])
           +HESS[166]*(U1[33]*U2[33]);
  HTU[28] = HESS[15]*(U1[10]*U2[10])+HESS[37]*(U1[19]*U2[19])+HESS[54]
           *(U1[22]*U2[33])+HESS[61]*(U1[24]*U2[24])+HESS[74]*(U1[25]
           *U2[19])+HESS[81]*(U1[25]*U2[25])+HESS[86]*(U1[25]*U2[32])
           +HESS[94]*(U1[26]*U2[26])+HESS[102]*(U1[27]*U2[26])
           +HESS[110]*(U1[28]*U2[10])+HESS[111]*(U1[28]*U2[19])
           +HESS[112]*(U1[28]*U2[24])+HESS[113]*(U1[28]*U2[25])
           +HESS[114]*(U1[28]*U2[26])+HESS[115]*(U1[28]*U2[29])
           +HESS[116]*(U1[28]*U2[31])+HESS[117]*(U1[28]*U2[32])
           +HESS[118]*(U1[28]*U2[33])+HESS[122]*(U1[29]*U2[29])
           +HESS[126]*(U1[30]*U2[24])+HESS[139]*(U1[31]*U2[31])
           +HESS[149]*(U1[32]*U2[25])+HESS[153]*(U1[32]*U2[32])
           +HESS[167]*(U1[33]*U2[29])+HESS[168]*(U1[33]*U2[33]);
  HTU[29] = HESS[14]*(U1[9]*U2[20])+HESS[41]*(U1[20]*U2[20])+HESS[51]
           *(U1[22]*U2[22])+HESS[64]*(U1[24]*U2[30])+HESS[87]*(U1[25]
           *U2[32])+HESS[97]*(U1[26]*U2[27])+HESS[105]*(U1[27]*U2[27])
           +HESS[115]*(U1[28]*U2[28])+HESS[119]*(U1[29]*U2[20])
           +HESS[120]*(U1[29]*U2[22])+HESS[121]*(U1[29]*U2[27])
           +HESS[122]*(U1[29]*U2[28])+HESS[123]*(U1[29]*U2[30])
           +HESS[124]*(U1[29]*U2[32])+HESS[128]*(U1[30]*U2[30])
           +HESS[154]*(U1[32]*U2[32])+HESS[160]*(U1[33]*U2[20])
           +HESS[161]*(U1[33]*U2[22])+HESS[165]*(U1[33]*U2[27])
           +HESS[167]*(U1[33]*U2[28])+HESS[169]*(U1[33]*U2[30])
           +HESS[170]*(U1[33]*U2[32]);
  HTU[30] = HESS[4]*(U1[3]*U2[27])+HESS[6]*(U1[4]*U2[27])+HESS[7]
           *(U1[5]*U2[27])+HESS[8]*(U1[6]*U2[32])+HESS[9]*(U1[7]
           *U2[33])+HESS[63]*(U1[24]*U2[27])+HESS[64]*(U1[24]*U2[29])
           +HESS[65]*(U1[24]*U2[30])+HESS[66]*(U1[24]*U2[31])+HESS[106]
           *(U1[27]*U2[27])+HESS[123]*(U1[29]*U2[29])+HESS[127]*(U1[30]
           *U2[27])+HESS[128]*(U1[30]*U2[29])+HESS[129]*(U1[30]*U2[30])
           +HESS[130]*(U1[30]*U2[31])+HESS[131]*(U1[30]*U2[32])
           +HESS[132]*(U1[30]*U2[33])+HESS[140]*(U1[31]*U2[31])
           +HESS[155]*(U1[32]*U2[32])+HESS[169]*(U1[33]*U2[29])
           +HESS[171]*(U1[33]*U2[33]);
  HTU[31] = HESS[13]*(U1[8]*U2[23])+HESS[39]*(U1[19]*U2[25])+HESS[45]
           *(U1[21]*U2[21])+HESS[50]*(U1[22]*U2[21])+HESS[52]*(U1[22]
           *U2[22])+HESS[58]*(U1[23]*U2[23])+HESS[66]*(U1[24]*U2[30])
           +HESS[78]*(U1[25]*U2[23])+HESS[82]*(U1[25]*U2[25])+HESS[88]
           *(U1[25]*U2[32])+HESS[98]*(U1[26]*U2[27])+HESS[100]*(U1[27]
           *U2[21])+HESS[107]*(U1[27]*U2[27])+HESS[116]*(U1[28]*U2[28])
           +HESS[125]*(U1[29]*U2[33])+HESS[130]*(U1[30]*U2[30])
           +HESS[133]*(U1[31]*U2[21])+HESS[134]*(U1[31]*U2[22])
           +HESS[135]*(U1[31]*U2[23])+HESS[137]*(U1[31]*U2[25])
           +HESS[138]*(U1[31]*U2[27])+HESS[139]*(U1[31]*U2[28])
           +HESS[140]*(U1[31]*U2[30])+HESS[141]*(U1[31]*U2[32])
           +HESS[142]*(U1[31]*U2[33])+HESS[156]*(U1[32]*U2[32])
           +HESS[162]*(U1[33]*U2[22])+HESS[172]*(U1[33]*U2[33]);
  HTU[32] = HESS[8]*(U1[6]*U2[30])+HESS[19]*(U1[12]*U2[24])+HESS[21]
           *(U1[13]*U2[20])+HESS[23]*(U1[14]*U2[33])+HESS[28]*(U1[15]
           *U2[26])+HESS[31]*(U1[16]*U2[32])+HESS[34]*(U1[17]*U2[27])
           +HESS[38]*(U1[19]*U2[19])+HESS[42]*(U1[20]*U2[20])+HESS[62]
           *(U1[24]*U2[24])+HESS[75]*(U1[25]*U2[19])+HESS[83]*(U1[25]
           *U2[25])+HESS[85]*(U1[25]*U2[26])+HESS[86]*(U1[25]*U2[28])
           +HESS[87]*(U1[25]*U2[29])+HESS[88]*(U1[25]*U2[31])+HESS[95]
           *(U1[26]*U2[26])+HESS[103]*(U1[27]*U2[26])+HESS[108]*(U1[27]
           *U2[27])+HESS[117]*(U1[28]*U2[28])+HESS[124]*(U1[29]*U2[29])
           +HESS[131]*(U1[30]*U2[30])+HESS[141]*(U1[31]*U2[31])
           +HESS[145]*(U1[32]*U2[19])+HESS[146]*(U1[32]*U2[20])
           +HESS[147]*(U1[32]*U2[24])+HESS[150]*(U1[32]*U2[25])
           +HESS[151]*(U1[32]*U2[26])+HESS[152]*(U1[32]*U2[27])
           +HESS[153]*(U1[32]*U2[28])+HESS[154]*(U1[32]*U2[29])
           +HESS[155]*(U1[32]*U2[30])+HESS[156]*(U1[32]*U2[31])
           +HESS[157]*(U1[32]*U2[32])+HESS[158]*(U1[32]*U2[33])
           +HESS[170]*(U1[33]*U2[29])+HESS[173]*(U1[33]*U2[33]);
  HTU[33] = HESS[9]*(U1[7]*U2[30])+HESS[16]*(U1[11]*U2[22])+HESS[23]
           *(U1[14]*U2[32])+HESS[36]*(U1[18]*U2[25])+HESS[46]*(U1[21]
           *U2[27])+HESS[53]*(U1[22]*U2[22])+HESS[54]*(U1[22]*U2[28])
           +HESS[84]*(U1[25]*U2[25])+HESS[109]*(U1[27]*U2[27])
           +HESS[118]*(U1[28]*U2[28])+HESS[125]*(U1[29]*U2[31])
           +HESS[132]*(U1[30]*U2[30])+HESS[142]*(U1[31]*U2[31])
           +HESS[158]*(U1[32]*U2[32])+HESS[163]*(U1[33]*U2[22])
           +HESS[164]*(U1[33]*U2[25])+HESS[166]*(U1[33]*U2[27])
           +HESS[168]*(U1[33]*U2[28])+HESS[171]*(U1[33]*U2[30])
           +HESS[172]*(U1[33]*U2[31])+HESS[173]*(U1[33]*U2[32]);
}

/* End of HessTR_Vec function                                       */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Hess_Vec - Hessian times user vectors                            */
/*   Arguments :                                                    */
/*      HESS      - Hessian of Var (i.e. the 3-tensor d Jac / d Var) */
/*      U1        - User vector                                     */
/*      U2        - User vector                                     */
/*      HU        - Hessian times user vectors: (Hess x U2) * U1 = [d (Jac*U1)/d Var] * U2 */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

void Hess_Vec( 
  float HESS[],                          /* Hessian of Var (i.e. the 3-tensor d Jac / d Var) */
  float U1[],                            /* User vector */
  float U2[],                            /* User vector */
  float HU[]                             /* Hessian times user vectors: (Hess x U2) * U1 = [d (Jac*U1)/d Var] * U2 */
)
{
/* Compute the vector HU =(Hess x U2) * U1 = d (Jac*U1)/d Var * U2  */
  HU[0] = 0;
  HU[1] = HESS[0]*(U1[21]*U2[26])+HESS[0]*(U1[26]*U2[21])+HESS[1]
         *(U1[27]*U2[27]);
  HU[2] = HESS[2]*(U1[27]*U2[27]);
  HU[3] = HESS[3]*(U1[27]*U2[27])+HESS[4]*(U1[27]*U2[30])+HESS[4]
         *(U1[30]*U2[27]);
  HU[4] = HESS[5]*(U1[27]*U2[27])+HESS[6]*(U1[27]*U2[30])+HESS[6]
         *(U1[30]*U2[27]);
  HU[5] = HESS[7]*(U1[27]*U2[30])+HESS[7]*(U1[30]*U2[27]);
  HU[6] = HESS[8]*(U1[30]*U2[32])+HESS[8]*(U1[32]*U2[30]);
  HU[7] = HESS[9]*(U1[30]*U2[33])+HESS[9]*(U1[33]*U2[30]);
  HU[8] = HESS[10]*(U1[23]*U2[24])+HESS[10]*(U1[24]*U2[23])+HESS[11]
         *(U1[23]*U2[25])+HESS[11]*(U1[25]*U2[23])+HESS[12]*(U1[23]
         *U2[26])+HESS[12]*(U1[26]*U2[23])+HESS[13]*(U1[23]*U2[31])
         +HESS[13]*(U1[31]*U2[23]);
  HU[9] = HESS[14]*(U1[20]*U2[29])+HESS[14]*(U1[29]*U2[20]);
  HU[10] = HESS[15]*(U1[10]*U2[28])+HESS[15]*(U1[28]*U2[10]);
  HU[11] = HESS[16]*(U1[22]*U2[33])+HESS[16]*(U1[33]*U2[22]);
  HU[12] = HESS[17]*(U1[12]*U2[25])+HESS[17]*(U1[25]*U2[12])+HESS[18]
          *(U1[23]*U2[24])+HESS[18]*(U1[24]*U2[23])+HESS[19]*(U1[24]
          *U2[32])+HESS[19]*(U1[32]*U2[24]);
  HU[13] = HESS[20]*(U1[13]*U2[25])+HESS[20]*(U1[25]*U2[13])+HESS[21]
          *(U1[20]*U2[32])+HESS[21]*(U1[32]*U2[20]);
  HU[14] = HESS[22]*(U1[14]*U2[25])+HESS[22]*(U1[25]*U2[14])+HESS[23]
          *(U1[32]*U2[33])+HESS[23]*(U1[33]*U2[32]);
  HU[15] = HESS[24]*(U1[15]*U2[25])+HESS[24]*(U1[25]*U2[15])+HESS[25]
          *(U1[16]*U2[26])+HESS[25]*(U1[26]*U2[16])+HESS[26]*(U1[23]
          *U2[26])+HESS[26]*(U1[26]*U2[23])+HESS[27]*(U1[25]*U2[27])
          +HESS[27]*(U1[27]*U2[25])+HESS[28]*(U1[26]*U2[32])+HESS[28]
          *(U1[32]*U2[26]);
  HU[16] = HESS[29]*(U1[16]*U2[25])+HESS[29]*(U1[25]*U2[16])+HESS[30]
          *(U1[16]*U2[26])+HESS[30]*(U1[26]*U2[16])+HESS[31]*(U1[32]
          *U2[32]);
  HU[17] = HESS[32]*(U1[17]*U2[25])+HESS[32]*(U1[25]*U2[17])+HESS[33]
          *(U1[21]*U2[25])+HESS[33]*(U1[25]*U2[21])+HESS[34]*(U1[27]
          *U2[32])+HESS[34]*(U1[32]*U2[27]);
  HU[18] = HESS[35]*(U1[18]*U2[25])+HESS[35]*(U1[25]*U2[18])+HESS[36]
          *(U1[25]*U2[33])+HESS[36]*(U1[33]*U2[25]);
  HU[19] = HESS[37]*(U1[19]*U2[28])+HESS[37]*(U1[28]*U2[19])+HESS[38]
          *(U1[19]*U2[32])+HESS[38]*(U1[32]*U2[19])+HESS[39]*(U1[25]
          *U2[31])+HESS[39]*(U1[31]*U2[25]);
  HU[20] = HESS[40]*(U1[13]*U2[25])+HESS[40]*(U1[25]*U2[13])+HESS[41]
          *(U1[20]*U2[29])+HESS[41]*(U1[29]*U2[20])+HESS[42]*(U1[20]
          *U2[32])+HESS[42]*(U1[32]*U2[20]);
  HU[21] = HESS[43]*(U1[21]*U2[25])+HESS[43]*(U1[25]*U2[21])+HESS[44]
          *(U1[21]*U2[26])+HESS[44]*(U1[26]*U2[21])+HESS[45]*(U1[21]
          *U2[31])+HESS[45]*(U1[31]*U2[21])+HESS[46]*(U1[27]*U2[33])
          +HESS[46]*(U1[33]*U2[27]);
  HU[22] = HESS[47]*(U1[18]*U2[25])+HESS[47]*(U1[25]*U2[18])+HESS[48]
          *(U1[21]*U2[25])+HESS[48]*(U1[25]*U2[21])+HESS[49]*(U1[21]
          *U2[26])+HESS[49]*(U1[26]*U2[21])+HESS[50]*(U1[21]*U2[31])
          +HESS[50]*(U1[31]*U2[21])+HESS[51]*(U1[22]*U2[29])+HESS[51]
          *(U1[29]*U2[22])+HESS[52]*(U1[22]*U2[31])+HESS[52]*(U1[31]
          *U2[22])+HESS[53]*(U1[22]*U2[33])+HESS[53]*(U1[33]*U2[22])
          +HESS[54]*(U1[28]*U2[33])+HESS[54]*(U1[33]*U2[28]);
  HU[23] = HESS[55]*(U1[23]*U2[24])+HESS[55]*(U1[24]*U2[23])+HESS[56]
          *(U1[23]*U2[25])+HESS[56]*(U1[25]*U2[23])+HESS[57]*(U1[23]
          *U2[26])+HESS[57]*(U1[26]*U2[23])+HESS[58]*(U1[23]*U2[31])
          +HESS[58]*(U1[31]*U2[23]);
  HU[24] = HESS[59]*(U1[12]*U2[25])+HESS[59]*(U1[25]*U2[12])+HESS[60]
          *(U1[23]*U2[24])+HESS[60]*(U1[24]*U2[23])+HESS[61]*(U1[24]
          *U2[28])+HESS[61]*(U1[28]*U2[24])+HESS[62]*(U1[24]*U2[32])
          +HESS[62]*(U1[32]*U2[24])+HESS[63]*(U1[27]*U2[30])+HESS[63]
          *(U1[30]*U2[27])+HESS[64]*(U1[29]*U2[30])+HESS[64]*(U1[30]
          *U2[29])+HESS[65]*(U1[30]*U2[30])+HESS[66]*(U1[30]*U2[31])
          +HESS[66]*(U1[31]*U2[30]);
  HU[25] = HESS[67]*(U1[12]*U2[25])+HESS[67]*(U1[25]*U2[12])+HESS[68]
          *(U1[13]*U2[25])+HESS[68]*(U1[25]*U2[13])+HESS[69]*(U1[14]
          *U2[25])+HESS[69]*(U1[25]*U2[14])+HESS[70]*(U1[15]*U2[25])
          +HESS[70]*(U1[25]*U2[15])+HESS[71]*(U1[16]*U2[25])+HESS[71]
          *(U1[25]*U2[16])+HESS[72]*(U1[17]*U2[25])+HESS[72]*(U1[25]
          *U2[17])+HESS[73]*(U1[18]*U2[25])+HESS[73]*(U1[25]*U2[18])
          +HESS[74]*(U1[19]*U2[28])+HESS[74]*(U1[28]*U2[19])+HESS[75]
          *(U1[19]*U2[32])+HESS[75]*(U1[32]*U2[19])+HESS[76]*(U1[21]
          *U2[25])+HESS[76]*(U1[25]*U2[21])+HESS[77]*(U1[23]*U2[25])
          +HESS[77]*(U1[25]*U2[23])+HESS[78]*(U1[23]*U2[31])+HESS[78]
          *(U1[31]*U2[23])+HESS[79]*(U1[25]*U2[25])+HESS[80]*(U1[25]
          *U2[27])+HESS[80]*(U1[27]*U2[25])+HESS[81]*(U1[25]*U2[28])
          +HESS[81]*(U1[28]*U2[25])+HESS[82]*(U1[25]*U2[31])+HESS[82]
          *(U1[31]*U2[25])+HESS[83]*(U1[25]*U2[32])+HESS[83]*(U1[32]
          *U2[25])+HESS[84]*(U1[25]*U2[33])+HESS[84]*(U1[33]*U2[25])
          +HESS[85]*(U1[26]*U2[32])+HESS[85]*(U1[32]*U2[26])+HESS[86]
          *(U1[28]*U2[32])+HESS[86]*(U1[32]*U2[28])+HESS[87]*(U1[29]
          *U2[32])+HESS[87]*(U1[32]*U2[29])+HESS[88]*(U1[31]*U2[32])
          +HESS[88]*(U1[32]*U2[31]);
  HU[26] = HESS[89]*(U1[15]*U2[25])+HESS[89]*(U1[25]*U2[15])+HESS[90]
          *(U1[16]*U2[26])+HESS[90]*(U1[26]*U2[16])+HESS[91]*(U1[21]
          *U2[26])+HESS[91]*(U1[26]*U2[21])+HESS[92]*(U1[23]*U2[26])
          +HESS[92]*(U1[26]*U2[23])+HESS[93]*(U1[25]*U2[27])+HESS[93]
          *(U1[27]*U2[25])+HESS[94]*(U1[26]*U2[28])+HESS[94]*(U1[28]
          *U2[26])+HESS[95]*(U1[26]*U2[32])+HESS[95]*(U1[32]*U2[26])
          +HESS[96]*(U1[27]*U2[27])+HESS[97]*(U1[27]*U2[29])+HESS[97]
          *(U1[29]*U2[27])+HESS[98]*(U1[27]*U2[31])+HESS[98]*(U1[31]
          *U2[27]);
  HU[27] = HESS[99]*(U1[17]*U2[25])+HESS[99]*(U1[25]*U2[17])+HESS[100]
          *(U1[21]*U2[31])+HESS[100]*(U1[31]*U2[21])+HESS[101]*(U1[25]
          *U2[27])+HESS[101]*(U1[27]*U2[25])+HESS[102]*(U1[26]*U2[28])
          +HESS[102]*(U1[28]*U2[26])+HESS[103]*(U1[26]*U2[32])
          +HESS[103]*(U1[32]*U2[26])+HESS[104]*(U1[27]*U2[27])
          +HESS[105]*(U1[27]*U2[29])+HESS[105]*(U1[29]*U2[27])
          +HESS[106]*(U1[27]*U2[30])+HESS[106]*(U1[30]*U2[27])
          +HESS[107]*(U1[27]*U2[31])+HESS[107]*(U1[31]*U2[27])
          +HESS[108]*(U1[27]*U2[32])+HESS[108]*(U1[32]*U2[27])
          +HESS[109]*(U1[27]*U2[33])+HESS[109]*(U1[33]*U2[27]);
  HU[28] = HESS[110]*(U1[10]*U2[28])+HESS[110]*(U1[28]*U2[10])
          +HESS[111]*(U1[19]*U2[28])+HESS[111]*(U1[28]*U2[19])
          +HESS[112]*(U1[24]*U2[28])+HESS[112]*(U1[28]*U2[24])
          +HESS[113]*(U1[25]*U2[28])+HESS[113]*(U1[28]*U2[25])
          +HESS[114]*(U1[26]*U2[28])+HESS[114]*(U1[28]*U2[26])
          +HESS[115]*(U1[28]*U2[29])+HESS[115]*(U1[29]*U2[28])
          +HESS[116]*(U1[28]*U2[31])+HESS[116]*(U1[31]*U2[28])
          +HESS[117]*(U1[28]*U2[32])+HESS[117]*(U1[32]*U2[28])
          +HESS[118]*(U1[28]*U2[33])+HESS[118]*(U1[33]*U2[28]);
  HU[29] = HESS[119]*(U1[20]*U2[29])+HESS[119]*(U1[29]*U2[20])
          +HESS[120]*(U1[22]*U2[29])+HESS[120]*(U1[29]*U2[22])
          +HESS[121]*(U1[27]*U2[29])+HESS[121]*(U1[29]*U2[27])
          +HESS[122]*(U1[28]*U2[29])+HESS[122]*(U1[29]*U2[28])
          +HESS[123]*(U1[29]*U2[30])+HESS[123]*(U1[30]*U2[29])
          +HESS[124]*(U1[29]*U2[32])+HESS[124]*(U1[32]*U2[29])
          +HESS[125]*(U1[31]*U2[33])+HESS[125]*(U1[33]*U2[31]);
  HU[30] = HESS[126]*(U1[24]*U2[28])+HESS[126]*(U1[28]*U2[24])
          +HESS[127]*(U1[27]*U2[30])+HESS[127]*(U1[30]*U2[27])
          +HESS[128]*(U1[29]*U2[30])+HESS[128]*(U1[30]*U2[29])
          +HESS[129]*(U1[30]*U2[30])+HESS[130]*(U1[30]*U2[31])
          +HESS[130]*(U1[31]*U2[30])+HESS[131]*(U1[30]*U2[32])
          +HESS[131]*(U1[32]*U2[30])+HESS[132]*(U1[30]*U2[33])
          +HESS[132]*(U1[33]*U2[30]);
  HU[31] = HESS[133]*(U1[21]*U2[31])+HESS[133]*(U1[31]*U2[21])
          +HESS[134]*(U1[22]*U2[31])+HESS[134]*(U1[31]*U2[22])
          +HESS[135]*(U1[23]*U2[31])+HESS[135]*(U1[31]*U2[23])
          +HESS[136]*(U1[25]*U2[25])+HESS[137]*(U1[25]*U2[31])
          +HESS[137]*(U1[31]*U2[25])+HESS[138]*(U1[27]*U2[31])
          +HESS[138]*(U1[31]*U2[27])+HESS[139]*(U1[28]*U2[31])
          +HESS[139]*(U1[31]*U2[28])+HESS[140]*(U1[30]*U2[31])
          +HESS[140]*(U1[31]*U2[30])+HESS[141]*(U1[31]*U2[32])
          +HESS[141]*(U1[32]*U2[31])+HESS[142]*(U1[31]*U2[33])
          +HESS[142]*(U1[33]*U2[31]);
  HU[32] = HESS[143]*(U1[16]*U2[25])+HESS[143]*(U1[25]*U2[16])
          +HESS[144]*(U1[16]*U2[26])+HESS[144]*(U1[26]*U2[16])
          +HESS[145]*(U1[19]*U2[32])+HESS[145]*(U1[32]*U2[19])
          +HESS[146]*(U1[20]*U2[32])+HESS[146]*(U1[32]*U2[20])
          +HESS[147]*(U1[24]*U2[32])+HESS[147]*(U1[32]*U2[24])
          +HESS[148]*(U1[25]*U2[27])+HESS[148]*(U1[27]*U2[25])
          +HESS[149]*(U1[25]*U2[28])+HESS[149]*(U1[28]*U2[25])
          +HESS[150]*(U1[25]*U2[32])+HESS[150]*(U1[32]*U2[25])
          +HESS[151]*(U1[26]*U2[32])+HESS[151]*(U1[32]*U2[26])
          +HESS[152]*(U1[27]*U2[32])+HESS[152]*(U1[32]*U2[27])
          +HESS[153]*(U1[28]*U2[32])+HESS[153]*(U1[32]*U2[28])
          +HESS[154]*(U1[29]*U2[32])+HESS[154]*(U1[32]*U2[29])
          +HESS[155]*(U1[30]*U2[32])+HESS[155]*(U1[32]*U2[30])
          +HESS[156]*(U1[31]*U2[32])+HESS[156]*(U1[32]*U2[31])
          +HESS[157]*(U1[32]*U2[32])+HESS[158]*(U1[32]*U2[33])
          +HESS[158]*(U1[33]*U2[32]);
  HU[33] = HESS[159]*(U1[14]*U2[25])+HESS[159]*(U1[25]*U2[14])
          +HESS[160]*(U1[20]*U2[29])+HESS[160]*(U1[29]*U2[20])
          +HESS[161]*(U1[22]*U2[29])+HESS[161]*(U1[29]*U2[22])
          +HESS[162]*(U1[22]*U2[31])+HESS[162]*(U1[31]*U2[22])
          +HESS[163]*(U1[22]*U2[33])+HESS[163]*(U1[33]*U2[22])
          +HESS[164]*(U1[25]*U2[33])+HESS[164]*(U1[33]*U2[25])
          +HESS[165]*(U1[27]*U2[29])+HESS[165]*(U1[29]*U2[27])
          +HESS[166]*(U1[27]*U2[33])+HESS[166]*(U1[33]*U2[27])
          +HESS[167]*(U1[28]*U2[29])+HESS[167]*(U1[29]*U2[28])
          +HESS[168]*(U1[28]*U2[33])+HESS[168]*(U1[33]*U2[28])
          +HESS[169]*(U1[29]*U2[30])+HESS[169]*(U1[30]*U2[29])
          +HESS[170]*(U1[29]*U2[32])+HESS[170]*(U1[32]*U2[29])
          +HESS[171]*(U1[30]*U2[33])+HESS[171]*(U1[33]*U2[30])
          +HESS[172]*(U1[31]*U2[33])+HESS[172]*(U1[33]*U2[31])
          +HESS[173]*(U1[32]*U2[33])+HESS[173]*(U1[33]*U2[32]);
}

/* End of Hess_Vec function                                         */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


