/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Auxiliary Routines File                                          */
/*                                                                  */
/* Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : strato_single_Util.c                      */
/* Time                 : Thu Jan 27 11:06:30 2022                  */
/* Working directory    : /home/kyriacos/CyprusInstitute/kpp/strato_single */
/* Equation file        : strato_single.kpp                         */
/* Output root filename : strato_single                             */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include <sys/time.h>
#include "strato_single_Parameters.h"
#include "strato_single_Global.h"
#include "strato_single_Sparse.h"



/* User INLINED Utility Functions                                   */

/* End INLINED Utility Functions                                    */

/* Utility Functions from KPP_HOME/util/util                        */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* UTIL - Utility functions                                         */
/*   Arguments :                                                    */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/*
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
*/
float min( float x, float y )
{
  return ( x <= y ) ? x : y;
}

float max( float x, float y )
{
  return ( x >= y ) ? x : y;
}

double
Stopwatch(double t0)
{
  struct timeval t;
  gettimeofday(&t, NULL);
  return (double)t.tv_sec + (double)t.tv_usec / 1e6 - t0;
}


static FILE *fpDat = 0;

int InitSaveData()
{
  fpDat = fopen("strato_single.dat", "w");
  if( fpDat == 0 ) {
    printf("\n Can't create file : strato_single.dat");
    exit(1);
  }
  return 0;
}

int SaveData()
{
int i;

  fprintf( fpDat, "%6.1f ", TIME/3600.0 );
  for( i = 0; i < NLOOKAT; i++ )
    fprintf( fpDat, "%24.16e ", C[ LOOKAT[i] ]/CFACTOR );
  fprintf( fpDat, "\n");
  return 0;
}

int CloseSaveData()
{
  fclose( fpDat );
  return 0;
}

int GenerateMatlab( char * prefix )
{
int i;
FILE *fpMatlab;
  
  fpMatlab = fopen("strato_single.m", "w");
  if( fpMatlab == 0 ) {
    printf("\n Can't create file : strato_single.m");
    exit(1);
  }

  fprintf(fpMatlab, "load strato_single.dat;\n");
  fprintf(fpMatlab, "%sc = strato_single;\n", prefix);
  fprintf(fpMatlab, "clear strato_single;\n");
  fprintf(fpMatlab, "%st=%sc(:,1);\n", prefix, prefix);
  fprintf(fpMatlab, "%sc(:,1)=[];\n", prefix);
  
  for( i = 0; i < NLOOKAT; i++ )
    fprintf( fpMatlab, "%s%s = %sc(:,%d);\n", 
            prefix, SPC_NAMES[LOOKAT[i]], 
            prefix, i+1 );
  
  fclose( fpMatlab );
  return 0;
}

/* End Utility Functions from KPP_HOME/util/util                    */
/* End of UTIL function                                             */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Shuffle_user2kpp - function to copy concentrations from USER to KPP */
/*   Arguments :                                                    */
/*      V_USER    - Concentration of variable species in USER's order */
/*      V         - Concentrations of variable species (local)      */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

void Shuffle_user2kpp( 
  float V_USER[],                        /* Concentration of variable species in USER's order */
  float V[]                              /* Concentrations of variable species (local) */
)
{
  V[31] = V_USER[0];
  V[10] = V_USER[1];
  V[28] = V_USER[2];
  V[29] = V_USER[3];
  V[33] = V_USER[4];
  V[22] = V_USER[5];
  V[11] = V_USER[6];
  V[18] = V_USER[7];
  V[14] = V_USER[8];
  V[19] = V_USER[9];
  V[25] = V_USER[10];
  V[32] = V_USER[11];
  V[16] = V_USER[12];
  V[0] = V_USER[13];
  V[9] = V_USER[14];
  V[20] = V_USER[15];
  V[13] = V_USER[16];
  V[8] = V_USER[17];
  V[23] = V_USER[18];
  V[26] = V_USER[19];
  V[1] = V_USER[20];
  V[27] = V_USER[21];
  V[3] = V_USER[22];
  V[4] = V_USER[23];
  V[2] = V_USER[24];
  V[15] = V_USER[25];
  V[17] = V_USER[26];
  V[21] = V_USER[27];
  V[24] = V_USER[28];
  V[5] = V_USER[29];
  V[30] = V_USER[30];
  V[12] = V_USER[31];
  V[6] = V_USER[32];
  V[7] = V_USER[33];
}

/* End of Shuffle_user2kpp function                                 */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Shuffle_kpp2user - function to restore concentrations from KPP to USER */
/*   Arguments :                                                    */
/*      V         - Concentrations of variable species (local)      */
/*      V_USER    - Concentration of variable species in USER's order */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

void Shuffle_kpp2user( 
  float V[],                             /* Concentrations of variable species (local) */
  float V_USER[]                         /* Concentration of variable species in USER's order */
)
{
  V_USER[0] = V[31];
  V_USER[1] = V[10];
  V_USER[2] = V[28];
  V_USER[3] = V[29];
  V_USER[4] = V[33];
  V_USER[5] = V[22];
  V_USER[6] = V[11];
  V_USER[7] = V[18];
  V_USER[8] = V[14];
  V_USER[9] = V[19];
  V_USER[10] = V[25];
  V_USER[11] = V[32];
  V_USER[12] = V[16];
  V_USER[13] = V[0];
  V_USER[14] = V[9];
  V_USER[15] = V[20];
  V_USER[16] = V[13];
  V_USER[17] = V[8];
  V_USER[18] = V[23];
  V_USER[19] = V[26];
  V_USER[20] = V[1];
  V_USER[21] = V[27];
  V_USER[22] = V[3];
  V_USER[23] = V[4];
  V_USER[24] = V[2];
  V_USER[25] = V[15];
  V_USER[26] = V[17];
  V_USER[27] = V[21];
  V_USER[28] = V[24];
  V_USER[29] = V[5];
  V_USER[30] = V[30];
  V_USER[31] = V[12];
  V_USER[32] = V[6];
  V_USER[33] = V[7];
}

/* End of Shuffle_kpp2user function                                 */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* GetMass - compute total mass of selected atoms                   */
/*   Arguments :                                                    */
/*      CL        - Concentration of all species (local)            */
/*      Mass      - value of mass balance                           */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

void GetMass( 
  float CL[],                            /* Concentration of all species (local) */
  float Mass[]                           /* value of mass balance */
)
{
}

/* End of GetMass function                                          */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


