C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C                                                                  
C The ODE Function of Chemical Model File                          
C                                                                  
C Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  
C       (http://www.cs.vt.edu/~asandu/Software/KPP)                
C KPP is distributed under GPL, the general public licence         
C       (http://www.gnu.org/copyleft/gpl.html)                     
C (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           
C (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            
C     With important contributions from:                           
C        M. Damian, Villanova University, USA                      
C        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
C                                                                  
C File                 : strato_ref_Function.f                     
C Time                 : Fri Sep  2 14:40:07 2022                  
C Working directory    : /home/kyriacos/CyprusInstitute/KPP/strato_ref
C Equation file        : strato_ref.kpp                            
C Output root filename : strato_ref                                
C                                                                  
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C                                                                  
C Fun - time derivatives of variables - Agregate form              
C   Arguments :                                                    
C      V         - Concentrations of variable species (local)      
C      F         - Concentrations of fixed species (local)         
C      RCT       - Rate constants (local)                          
C      Vdot      - Time derivative of variable species concentrations
C                                                                  
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      SUBROUTINE Fun ( V, F, RCT, Vdot )

      IMPLICIT NONE
      INCLUDE 'strato_ref_Parameters.h'

C V - Concentrations of variable species (local)                   
      REAL*8 V(NVAR)
C F - Concentrations of fixed species (local)                      
      REAL*8 F(NFIX)
C RCT - Rate constants (local)                                     
      REAL*8 RCT(NREACT)
C Vdot - Time derivative of variable species concentrations        
      REAL*8 Vdot(NVAR)


C Local variables                                                  
C A - Rate for each equation                                       
      REAL*8 A(NREACT)

C Computation of equation rates                                    
      A(1) = 8.01822e-17*V(32)*F(3)
      A(2) = 1.57571e-15*V(29)*V(32)
      A(3) = 2.83887e-11*V(11)*F(4)
      A(4) = 4.27631e-11*V(11)*F(3)
      A(5) = 1.2e-10*V(11)*V(29)
      A(6) = 2.2e-10*V(11)*F(1)
      A(7) = 1e-10*V(11)*F(2)
      A(8) = 7.5e-12*V(11)*F(5)
      A(9) = 1.425e-10*V(11)*F(5)
      A(10) = 6.35388e-15*V(20)*F(3)
      A(11) = 1.99835e-11*V(20)*V(29)
      A(12) = 1.38892e-15*V(26)*F(2)
      A(13) = 3.25993e-14*V(26)*V(29)
      A(14) = 3.61646e-11*V(26)*V(32)
      A(15) = 1.55427e-12*V(26)*V(26)
      A(16) = 6.86894e-11*V(32)*V(33)
      A(17) = 1.38667e-15*V(29)*V(33)
      A(18) = 7e-11*V(20)*V(33)
      A(19) = 1.35192e-10*V(26)*V(33)
      A(20) = 2.76946e-12*V(33)*V(33)
      A(21) = 3.51541e-29*V(33)*V(33)*F(1)
      A(22) = 1.4948e-12*V(17)*V(26)
      A(23) = 6.06249e-15*V(29)*V(30)
      A(24) = 1.04211e-11*V(30)*V(33)
      A(25) = 1.0685e-11*V(32)*V(34)
      A(26) = 4.69913e-18*V(29)*V(34)
      A(27) = 3.72413e-13*V(26)*V(34)
      A(28) = 2.69029e-14*V(33)*V(34)
      A(29) = 1e-11*V(23)*V(32)
      A(30) = 3.03315e-11*V(23)*V(30)
      A(31) = 2.32597e-13*V(23)*V(34)
      A(32) = 1.40599e-06*V(12)
      A(33) = 1.89006e-13*V(19)*V(26)
      A(34) = 6.27341e-12*V(15)*V(26)
      A(35) = 3.1633e-07*V(15)
      A(36) = 0
      A(37) = 3.03268e-16*V(27)*F(3)
      A(38) = 9.87868e-12*V(27)*V(29)
      A(39) = 2.6969e-15*V(27)*F(2)
      A(40) = 3.63979e-11*V(27)*V(33)
      A(41) = 6.35777e-12*V(27)*V(33)
      A(42) = 1.89901e-13*V(17)*V(27)
      A(43) = 4.00904e-11*V(28)*V(32)
      A(44) = 1.80823e-11*V(26)*V(28)
      A(45) = 0
      A(46) = 8.71828e-12*V(28)*V(33)
      A(47) = 2.12738e-11*V(28)*V(30)
      A(48) = 2.88645e-14*V(28)*V(34)
      A(49) = 1.20131e-15*V(28)*V(28)
      A(50) = 1.17478e-15*V(28)*V(28)
      A(51) = 1.37988e-15*V(28)*V(28)
      A(52) = 3.33034e-15*V(28)*V(28)
      A(53) = 16948.7*V(4)
      A(54) = 0.000477396*V(3)
      A(55) = 6.10068e-13*V(16)*V(26)
      A(56) = 3.78181e-13*V(18)*V(26)
      A(57) = 1.05517e-13*V(22)*V(32)
      A(58) = 3.02111e-13*V(22)*V(26)
      A(59) = 1.31924e-11*V(22)*V(27)
      A(60) = 0
      A(61) = 6.18551e-13*V(25)*V(29)
      A(62) = 1.24964e-12*V(25)*V(33)
      A(63) = 6.18551e-13*V(24)*V(25)
      A(64) = 4.99054e-11*V(31)*V(32)
      A(65) = 4.91828e-11*V(31)*V(33)
      A(66) = 2.58334e-11*V(30)*V(31)
      A(67) = 7.68422e-14*V(31)*V(34)
      A(68) = 9.49778e-12*V(28)*V(31)
      A(69) = 7.21345e-12*V(28)*V(31)
      A(70) = 1.17282e-12*V(28)*V(31)
      A(71) = 2.46725e-12*V(31)*V(31)
      A(72) = 1.1e-11*V(13)*V(26)
      A(73) = 1.5024e-13*V(26)*F(6)
      A(74) = 1.53225e-15*V(26)*F(5)
      A(75) = 1e-11*V(24)*V(26)
      A(76) = 4.50123e-14*V(24)*V(32)
      A(77) = 3.33437e-14*V(27)*F(5)
      A(78) = 7.15352e-11*V(24)*V(27)
      A(79) = 6.25037e-12*V(9)*F(3)
      A(80) = 5.88365e-14*V(1)*F(3)
      A(81) = 9.37792e-16*V(10)*F(3)
      A(82) = 8.85199e-12*V(21)*V(30)
      A(83) = 1.04438e-11*V(21)*V(33)
      A(84) = 6.18205e-12*V(14)*V(26)
      A(85) = RCT(85)*F(3)
      A(86) = RCT(86)*V(29)
      A(87) = RCT(87)*V(29)
      A(88) = RCT(88)*V(33)
      A(89) = RCT(89)*V(17)
      A(90) = RCT(90)*V(34)
      A(91) = RCT(91)*V(23)
      A(92) = RCT(92)*V(23)
      A(93) = RCT(93)*V(12)
      A(94) = RCT(94)*V(19)
      A(95) = RCT(95)*V(15)
      A(96) = RCT(96)*V(15)
      A(97) = RCT(97)*V(2)
      A(98) = RCT(98)*V(5)
      A(99) = RCT(99)*V(3)
      A(100) = RCT(100)*V(18)
      A(101) = RCT(101)*V(22)
      A(102) = RCT(102)*V(22)
      A(103) = RCT(103)*V(6)
      A(104) = RCT(104)*V(31)
      A(105) = RCT(105)*V(7)
      A(106) = RCT(106)*V(8)
      A(107) = RCT(107)*V(24)
      A(108) = RCT(108)*V(24)
      A(109) = RCT(109)*V(14)

C Aggregate function                                               
      Vdot(1) = A(9)+A(74)+A(77)-A(80)
      Vdot(2) = A(51)+A(59)-A(97)
      Vdot(3) = A(52)-A(54)-A(99)
      Vdot(4) = A(37)+A(50)-A(53)+A(69)+A(99)
      Vdot(5) = A(49)+A(68)-A(98)
      Vdot(6) = A(70)-A(103)
      Vdot(7) = A(65)-A(105)
      Vdot(8) = A(67)-A(106)
      Vdot(9) = A(63)+A(75)+A(76)+A(78)-A(79)+A(107)
      Vdot(10) = -A(81)+A(82)+A(109)
      Vdot(11) = -A(3)-A(4)-A(5)-A(6)-A(7)-A(8)-A(9)+A(87)
      Vdot(12) = A(31)-A(32)-A(36)-A(93)
      Vdot(13) = A(62)+A(63)-A(72)
      Vdot(14) = A(83)-A(84)-A(109)
      Vdot(15) = A(28)-A(34)-A(35)-A(95)-A(96)
      Vdot(16) = A(39)+A(40)+A(42)+A(45)-A(55)+A(77)+A(78)
      Vdot(17) = A(20)+A(21)-A(22)-A(42)-A(89)
      Vdot(18) = A(46)-A(56)+A(58)+A(60)-A(100)
      Vdot(19) = A(27)-A(33)+2*A(36)+A(60)-A(94)
      Vdot(20) = A(7)-A(10)-A(11)+A(12)+A(14)-A(18)+A(39)+A(73)+A(107)
      Vdot(21) = A(80)-A(82)-A(83)+A(84)
      Vdot(22) = A(48)-A(57)-A(58)-A(59)-A(60)-A(101)-A(102)
      Vdot(23) = A(26)-A(29)-A(30)-A(31)+A(32)+A(33)+A(57)+A(58)+A(59)
     &          -A(91)-A(92)+A(93)+A(95)+A(101)+A(106)
      Vdot(24) = A(8)-A(63)-A(75)-A(76)-A(78)+A(81)-A(107)-A(108)
      Vdot(25) = -A(61)-A(62)-A(63)+A(64)+A(66)+A(68)+A(69)+2*A(71)
     &          +A(72)+A(103)+A(104)+A(105)+A(106)
      Vdot(26) = 2*A(6)+A(7)+A(9)+A(11)-A(12)-A(13)-A(14)-2*A(15)
     &          +A(16)+A(17)+2*A(18)-A(19)-A(22)+A(24)-A(27)-A(33)
     &          -A(34)+A(41)-A(44)-A(45)-A(55)-A(56)-A(58)-A(72)-A(73)
     &          -A(74)-A(75)+A(76)-A(84)+A(88)+2*A(89)+A(94)+A(95)
     &          +A(100)+A(105)+A(109)
      Vdot(27) = -A(37)-A(38)-A(39)-A(40)-A(41)-A(42)+A(43)+A(44)
     &          +A(47)+A(49)+A(50)+A(53)+A(55)-A(59)-A(77)-A(78)+2
     &          *A(97)+A(99)+A(100)+A(101)+A(102)+A(103)
      Vdot(28) = A(38)+A(41)-A(43)-A(44)-A(45)-A(46)-A(47)-A(48)-2
     &          *A(49)-2*A(50)-2*A(51)-2*A(52)+2*A(54)+A(56)+A(57)
     &          -A(68)-A(69)-A(70)+A(98)
      Vdot(29) = A(1)-A(2)-A(5)-A(11)-A(13)-A(17)-A(23)-A(26)-A(38)
     &          -A(61)-A(86)-A(87)
      Vdot(30) = -A(23)-A(24)+A(25)-A(30)-A(47)-A(66)-A(82)+A(90)
     &          +A(92)
      Vdot(31) = A(61)-A(64)-A(65)-A(66)-A(67)-A(68)-A(69)-A(70)-2
     &          *A(71)-A(104)
      Vdot(32) = -A(1)-A(2)+A(3)+A(4)-A(14)+A(15)-A(16)-A(25)-A(29)
     &          -A(43)-A(57)-A(64)-A(76)+2*A(85)+A(86)+A(88)+A(90)
     &          +A(91)+A(98)+A(102)+A(104)
      Vdot(33) = A(10)+A(13)-A(16)-A(17)-A(18)-A(19)-2*A(20)-2*A(21)
     &          +A(22)-A(24)-A(28)+A(35)-A(40)-A(41)+A(42)+A(44)-A(46)
     &          -A(62)-A(65)+A(79)+A(81)-A(83)-A(88)+A(96)
      Vdot(34) = A(23)+A(24)-A(25)-A(26)-A(27)-A(28)+A(29)+2*A(30)
     &          -A(31)+A(32)+A(34)+A(35)+A(47)-A(48)+A(66)-A(67)+A(82)
     &          -A(90)+A(91)+A(93)+A(94)+A(96)+A(102)
      RETURN
      END

C End of Fun function                                              
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


